Add jaeger and enable tracing by default in Tilt
OpenNMS-Cloud/lokahi pull request #1167
Opened 2023-05-29 03:38 UTC by deejgregor

Main focus:
- Add jaeger and enable tracing by default in Tilt

Examples:
- Add span attributes and set status code in certificate verifier
- inventory: add basic span attributes and status handling for minion heartbeat
- minion-gateway: improve root span details for dispatch traces
- minion-gateway: add location as a span attribute when we have it
- minion-gateway: heartbeat kafka forwarder: add message to span
- datachoices: @WithSpan example: add tenant_ids_count attribute to span

Cleanups:
- Remove dev environment flow URLs
- Don't regenerate certificates/secrets if they already exist unless -f is passed
- inventory: quiet: don't spit out stacktrace for LocationNotFoundException

## Description

This adds Jaeger to Tilt (https://jaeger.local:1443/) and adds a few more
examples of adding some tracing bits to a few services. It also has a few
small improvements.

## Jira link(s)
- https://issues.opennms.org/browse/HS-xx

## Flagged for review

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts

2023-05-29 15:07 UTC, geraldhumphries requested changes

2023-05-29 15:07 UTC, geraldhumphries commented on Tiltfile
> +watch_file("tilt-jaeger-values.yaml")
No need for `watch_file`, the extension calls `k8s_yaml` which sets up the same filewatch.

2023-05-29 16:22 UTC, deejgregor commented on charts/opennms/values.yaml
> -    FlowsUrl: flows.onms-dp-dev.dev.nonprod.dataservice.opennms.com:443
Tried that first. Can’t do that yet because the service won’t start. :( Shoulda noted that.

Oh, yeah: so, we need to add a way to disable the flows feature. :) I’ll add a ticket for that.

2023-05-29 16:25 UTC, deejgregor commented on charts/opennms/templates/opennms/metricsprocessor/metricsprocessor-deployment.yaml
> +              value: "flows-not-enabled"
The services come up but requests immediately fail. Which is the same that happened with the dev URL that was in the values file.

2023-05-29 16:27 UTC, deejgregor commented on Tiltfile
> +watch_file("tilt-jaeger-values.yaml")
It doesn’t in my experience, which is why I added it (after wondering for a bit why the heck my config changes weren’t being reflected before I dug in and saw it wasn’t running anything on changes to the values file).

I’ll re-test to make sure.

2023-05-29 18:08 UTC, deejgregor commented on charts/opennms/values.yaml
> -    FlowsUrl: flows.onms-dp-dev.dev.nonprod.dataservice.opennms.com:443
https://opennms.atlassian.net/browse/HS-1664

2023-05-29 18:19 UTC, deejgregor commented on Tiltfile
> +load('ext://helm_remote', 'helm_remote') # for simple charts like jaeger
Fixed.

2023-05-29 18:20 UTC, deejgregor commented on charts/opennms/templates/opennms/metricsprocessor/metricsprocessor-deployment.yaml
> +              value: "flows-not-enabled"
Added notes on the failures seen if I set the flow url values and **don't** make this change to https://opennms.atlassian.net/browse/HS-1664?focusedCommentId=97902

2023-05-29 18:21 UTC, deejgregor commented on Tiltfile
> +watch_file("tilt-jaeger-values.yaml")
Ah, you are correct! It *does* properly deal with updates to the values file when using `helm_remote`. The problem I saw was with a different change I was working on that used `helm_resource` (which you just specify a list of command-line arguments, so it makes sense that it doesn't know there is a values file it should watch). Fixed.

2023-05-29 21:54 UTC, splatch approved these changes
LGTM, just one remark on attribute naming.

2023-05-29 21:54 UTC, splatch commented on minion-certificate-verifier/main/src/main/java/org/opennms/horizon/minioncertverifier/controller/CertificateController.java
> +            span.setAttribute("user", tenant);
Small note - from consistency point of view I think its better to use `tenant-id` as an attribute key, user can be easily mixed with far too many things. We refer `tenant-id` later on in grpc headers at minion gateway so it might be easier to connect dots together.

2023-05-29 21:54 UTC, splatch commented on minion-certificate-verifier/main/src/main/java/org/opennms/horizon/minioncertverifier/controller/CertificateController.java
> +            span.setStatus(StatusCode.ERROR);
Do we have manually specify error status, even if we return HTTP 404 code?

2023-05-30 20:48 UTC, geraldhumphries commented on charts/opennms/templates/opennms/metricsprocessor/metricsprocessor-deployment.yaml
> +              value: "flows-not-enabled"
Can the "flows-not-enabled" value be moved to `charts/opennms/values.yaml` as the default? That way you wouldn't need the if statement.

2023-06-01 04:53 UTC, deejgregor commented on charts/opennms/templates/opennms/metricsprocessor/metricsprocessor-deployment.yaml
> +              value: "flows-not-enabled"
I see @freddy61025 already took care of this with 9bd8b507cedee7d6149d552ecad0b019434f0d4c. :)

2023-06-01 05:14 UTC, deejgregor commented on minion-certificate-verifier/main/src/main/java/org/opennms/horizon/minioncertverifier/controller/CertificateController.java
> +            span.setStatus(StatusCode.ERROR);
We don’t have to (you can always leave the status unset), but I wanted to be explicit since this was authentication—a more critical function.

I looked to see how the [instrumentation would act](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#status), and it’s not supposed to set a status in this case, so it’s good that we are.

> For HTTP status codes in the 4xx range span status MUST be left unset in case of SpanKind.SERVER and MUST be set to Error in case of SpanKind.CLIENT.

2023-06-01 05:22 UTC, deejgregor commented on minion-certificate-verifier/main/src/main/java/org/opennms/horizon/minioncertverifier/controller/CertificateController.java
> +            span.setAttribute("user", tenant);
We should definitely try to be consistent where we can, but the challenge is that we have a few other components that already use “user”: Cortex and TSaaS. We had the same debate awhile back with TSaaS and standardized on user there (because we could easily change TSaaS but could not in Cortex).

We should at some point see if this is the pattern we want to follow or if we want to deviate. We don’t need to be consistent but it helps the users of traces if we are consistent.

One thing I will **definitely** do on the next tracing thing I do in the code is add our own SemanticAttributes class and add a constant there for tenant-id/user, location, etc.. it will help us be consistent and make it easy to change if we want to in the future.

2023-06-01 14:39 UTC, geraldhumphries approved these changes

2023-06-01 14:41 UTC, merged