HS-1601: Taskset updates through Kafka
OpenNMS-Cloud/lokahi pull request #1171
Opened 2023-05-30 14:24 UTC by cgorantla

## Description
Inventory will update taskset updates through kafka instead of relying on gRPC API.

## Jira link(s)
- https://issues.opennms.org/browse/HS-1601

## Flagged for review

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts

2023-06-05 19:46 UTC, artnaseef requested changes
This review is not complete.  One of the comments raises some architectural questions which need to be resolved.

2023-06-05 19:46 UTC, artnaseef commented on shared-lib/protobuf/src/main/proto/taskSet.proto
> +}
Why not reuse the task-set-service definitions, AddSingleTaskOp and RemoveSingleTaskOp instead of creating entirely new ones?  Also, why send the complete task definition for removal?

2023-06-06 16:09 UTC, cgorantla commented on minion-gateway/task-set-service/src/main/java/org/opennms/miniongateway/taskset/service/TaskSetPublishKafkaConsumer.java
> +public class TaskSetPublishKafkaConsumer {
Consumer by default use `latest` for `auto.offset.reset`
Starting with `latest` doesn't mean it will always miss records. If there is no offset for a given consumer group recorded, it will start consuming from latest.  But once it starts consuming, it will start from last offset recorded for the given consumer group on a given partition.

Addressed other issue of distribution of messages to be in order for a given  tenant, location by using key.

2023-06-06 17:10 UTC, splatch commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/taskset/publisher/KafkaTaskSetPublisher.java
> +        var tasksetPub = TaskDefPub.newBuilder()
We do not require `TaskDefPub`, we have `UpdateTasksRequest` which allows to specify update context and `UpdateSingleTaskOp` which provides add and remove syntax which is 1:1 to newly introduced `TaskDefPub`.

2023-06-06 17:11 UTC, splatch requested changes
@cgorantla I think we need to clarify contract to make it consistent, there is `taskset-service.proto` which could be re-used with your changes. Is there any reason why it does not fit kafka approach?

2023-06-06 17:50 UTC, cgorantla commented
> @cgorantla I think we need to clarify contract to make it consistent, there is `taskset-service.proto` which could be re-used with your changes. Is there any reason why it does not fit kafka approach?

Yeah, I updated the code to use the same contract. Do you still see anything missing here ?

2023-06-06 17:54 UTC, splatch commented
> > @cgorantla I think we need to clarify contract to make it consistent, there is `taskset-service.proto` which could be re-used with your changes. Is there any reason why it does not fit kafka approach?
> 
> Yeah, I updated the code to use the same contract. Do you still see anything missing here ?

It looks good, maybe I was stuck with earlier SHA, LGTM!

2023-06-06 17:54 UTC, splatch approved these changes

2023-06-06 21:51 UTC, artnaseef approved these changes
There are some changes in here that I would like to see, but they are not important enough to block the merge.

2023-06-06 21:51 UTC, artnaseef commented on inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/kafkahelper/KafkaConsumerRunner.java
> +    private final List<byte[]> values = new ArrayList<>();
The following will fix it - and is adequate since this is a test tool:

    private final List<byte[]> values = Collections.synchronizedList(new LinkedList<>());

2023-06-06 21:51 UTC, artnaseef commented on inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/kafkahelper/KafkaConsumerRunner.java
> +        return this.values;
Returning a copy of the list is a good idea here so that callers don't get confused by a list that is changing while they access it:

    return new LinkedList<>(this.values);

2023-06-06 21:51 UTC, artnaseef commented on inventory/main/src/test/java/org/opennms/horizon/inventory/service/taskset/publisher/GrpcTaskSetPublisherTest.java
> +@Disabled
Same as above - if it's unused, please remove it.

2023-06-06 21:51 UTC, artnaseef commented on minion-gateway/task-set-service/src/main/java/org/opennms/miniongateway/taskset/service/TaskSetPublishKafkaConsumer.java
> +public class TaskSetPublishKafkaConsumer {
I brought this up in the StreamSquad channel - I think we need some more attention on the architectural pattern.  So for now, I'll remove my objection to this change.

2023-06-14 14:57 UTC, merged