HS-1613 Create Karaf-Command to empty Udp/Tcp Parser Sessions
OpenNMS-Cloud/lokahi pull request #1192
Opened 2023-06-05 12:53 UTC by FrancescoBuc86

https://opennms.atlassian.net/browse/HS-1613

2023-06-06 02:05 UTC, freddy61025 reviewed
I would like to know is that will happen in real world? Or it just a test issue.

2023-06-06 02:05 UTC, freddy61025 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/TelemetryRegistryImpl.java
> +                listeners.add(listener);
I have been told that lifecycle of a listener is managed by karaf. If you keep a reference here it may affect resources release. Please verify if it is the case with fooker.

2023-06-06 10:41 UTC, fooker requested changes
Can we just simplify this mechanism by just selecting a parser by name (the tuple of listeners name and parser name is unique) and flush all sessions for this parser?

2023-06-06 10:41 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/listeners/TcpParser.java
> +    Set<TcpSession> getSessions();
Can we move this to the `Parser` base class and unify the handling between protocols?
This would be like `Set<Session> getSessions()`

2023-06-06 10:41 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/IpfixTcpParser.java
> +        final TcpSession session = new TcpSession(remoteAddress.getAddress(), localAddress, this::sequenceNumberTracker);
This feels wired. local address should come as first param.

2023-06-06 10:41 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/IpfixUdpParser.java
> -                    Objects.equal(this.remoteAddress, that.remoteAddress);
Do not always reformat.

2023-06-06 10:41 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/IpfixUdpParser.java
> -                    .add("remoteAddress", remoteAddress)
Same. Reformatting is additional burden for review.

2023-06-06 10:41 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/ParserBase.java
> +        return this.protocol.shortName;
Having a "short name" for a parser that is just the protocol seems wrong? What is the meaning of this?

2023-06-06 10:41 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/Protocol.java
> +    IPFIX(org.opennms.horizon.minion.flows.parser.ipfix.proto.Header.VERSION, "IPFix", "IPFIX");
If we really need this, let's call this `keyword`, and use it just for protocol names in the command line. Then it should be `netflow9` etc.

2023-06-06 10:41 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/TelemetryRegistry.java
> +    List<TcpParser> getTcpParsers();
If `getSessions` is unified, this can be unified, too.

2023-06-06 10:41 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/TelemetryRegistryImpl.java
> +                if (parser instanceof UdpParser) {
Oh, please don`t.

2023-06-06 10:41 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/TelemetryRegistryImpl.java
> +                listeners.add(listener);
In the current impl, we inject the factories without OSGI anyways. So there is no need to worry about the lifecycle of the factories.

Bot this will just add the listeners (and the parsers below) without ever removing them. The list of active listeners may be altered during runtime as soon an updated task-set is pushed.

2023-06-06 10:41 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/TelemetryRegistryImpl.java
> +                    tcpParsers.add((TcpParser) parser);
Can we just get the active parsers from the listeners by calling `getParsers()`?

2023-06-06 10:41 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/UdpParserBase.java
> +        sessionKeyHashMap.put(sessionKey, session);
The session manager already keeps track of the sessions.

2023-06-06 10:41 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/shell/ClearSessionCmd.java
> +                    tcpParser.dumpInternalState();
`dumpInternalState` will not clear the session. This is a method to dump the internal state of the parsers to something that is JSON serializable for debugging.

Really, there is no real way of clearing a session for TCP beside closing the connection.

2023-06-06 10:41 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/shell/ClearSessionCmd.java
> +    @Option(name = "-f", aliases = "--feature", description = "specify feature short name")
What do you mean by "feature"?

2023-06-06 10:41 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/shell/ClearSessionCmd.java
> +                    udpParser.getSessionKeyHashMap().clear();
Clearing the map on every element seems wrong.

2023-06-06 10:41 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/shell/ClearSessionCmd.java
> +                    entry.getKey().getLocalAddress().getPort() == portNumber
This could match multiple parsers if they are bound to different local addresses.

2023-06-06 10:41 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/shell/ClearSessionCmd.java
> +            udpParsers.forEach(udpParser -> udpParser.getSessionKeyHashMap().entrySet()
Just give the session manager

2023-06-07 10:41 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/TelemetryRegistryImpl.java
> +                listeners.add(listener);
Ok probably I can remove the active listeners based on the related task-set

2023-06-07 10:41 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/listeners/TcpParser.java
> +    Set<TcpSession> getSessions();
sure

2023-06-07 10:41 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/IpfixTcpParser.java
> +        final TcpSession session = new TcpSession(remoteAddress.getAddress(), localAddress, this::sequenceNumberTracker);
sure

2023-06-07 10:42 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/IpfixUdpParser.java
> -                    Objects.equal(this.remoteAddress, that.remoteAddress);
ok

2023-06-07 10:42 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/IpfixUdpParser.java
> -                    .add("remoteAddress", remoteAddress)
ok

2023-06-07 10:43 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/Protocol.java
> +    IPFIX(org.opennms.horizon.minion.flows.parser.ipfix.proto.Header.VERSION, "IPFix", "IPFIX");
good idea, will do

2023-06-07 10:43 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/TelemetryRegistry.java
> +    List<TcpParser> getTcpParsers();
yes makes sense

2023-06-07 10:44 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/TelemetryRegistryImpl.java
> +                if (parser instanceof UdpParser) {
ok, I'll find another solution

2023-06-07 10:44 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/TelemetryRegistryImpl.java
> +                    tcpParsers.add((TcpParser) parser);
probably yes, let me check

2023-06-07 10:44 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/UdpParserBase.java
> +        sessionKeyHashMap.put(sessionKey, session);
noticed that

2023-06-07 10:45 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/shell/ClearSessionCmd.java
> +                    tcpParser.dumpInternalState();
Thanks for sharing that, I'll change it

2023-06-07 10:52 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/shell/ClearSessionCmd.java
> +                    tcpParser.dumpInternalState();
what if I just remove them from the sessions set? Something like:
tcpParser.getSessions().clear();

2023-06-07 14:22 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/shell/ClearSessionCmd.java
> +                    tcpParser.dumpInternalState();
It will not work. The session is tightly bound to the TCP session. With TCP the whole problem does not even exists.

2023-06-12 09:19 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/shell/ClearSessionCmd.java
> +                    udpParser.getSessionKeyHashMap().clear();
right

2023-06-12 12:28 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/shell/ClearSessionCmd.java
> +                    tcpParser.dumpInternalState();
ok, but then we need this only for the udp session. I'll remove the part about the tcp

2023-06-13 14:13 UTC, fooker requested changes

2023-06-13 14:13 UTC, fooker commented on metrics-processor/flows/src/test/java/org/opennms/horizon/flows/integration/FlowRepositoryImplTest.java
> -                TenantLocationSpecificFlowDocumentLog.newBuilder()
Please revert reformatting.

2023-06-13 14:13 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/listeners/Parser.java
> +    String getKeyword();
Still don't get what the keyword is for. Just use the name.

2023-06-13 14:13 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/listeners/TcpParser.java
> +import org.opennms.horizon.minion.flows.parser.session.Session;
Remove unused imports.

2023-06-13 14:13 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/listeners/UdpParser.java
> +    UdpSessionManager.SessionKey buildSessionKey(final InetSocketAddress remoteAddress, final InetSocketAddress localAddress);
Don't need this. Also revert all related changes.

2023-06-13 14:13 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/IpfixTcpParser.java
>      private final Set<TcpSession> sessions = Sets.newConcurrentHashSet();
Don`t need that to be exposed

2023-06-13 14:13 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/session/Session.java
> +    InetSocketAddress getLocalAddress();
No longer used.

2023-06-13 14:13 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/TelemetryRegistry.java
> +
Unused imports

2023-06-13 14:13 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/session/UdpSessionManager.java
> +    @Getter
What does `@Getter` on a class even mean?

2023-06-13 14:13 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/shell/ClearUdpSessionCmd.java
> +    @Option(name = "-f", aliases = "--keyword", description = "specify protocol keyword")
Make this the parser name.

2023-06-13 14:13 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/shell/ClearUdpSessionCmd.java
> +    int portNumber;
No longer needed.

2023-06-13 14:13 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/shell/ClearUdpSessionCmd.java
> +                if (udpParsers.isEmpty()) {
This indention is cursed.

2023-06-13 14:13 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/shell/ClearUdpSessionCmd.java
> +        flowsListener.getListeners()
We can simplify this if we use the parser name. It we resolve to a single parser. Then you just have to ensure this parser is a udp parser or bail.

2023-06-14 14:03 UTC, fooker requested changes
Haven't looked at the test yet.

2023-06-14 14:03 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/shell/ClearUdpSessionCmd.java
> +        flowsListener.getListeners()
`flatMap` -> `filter(parserName...)` -> `findFirst` should do the trick.
After that, check for udp parser class.

2023-06-14 14:03 UTC, fooker commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/NMS13006_Test.java
> +import java.net.InetSocketAddress;
Unused.

2023-06-14 14:03 UTC, fooker commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ParserTest.java
> +import java.net.InetSocketAddress;
Unused.

2023-06-14 14:03 UTC, fooker commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/PayloadTest.java
> +import java.net.InetSocketAddress;
Unused.

2023-06-14 14:03 UTC, fooker commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ipfix/BlackboxTest.java
> +import java.net.InetSocketAddress;
Unused.

2023-06-14 14:03 UTC, fooker commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/netflow9/BlackboxTest.java
> +import java.net.InetSocketAddress;
Unused.

2023-06-14 14:05 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/IpfixUdpParser.java
> -    protected UdpSessionManager.SessionKey buildSessionKey(final InetSocketAddress remoteAddress, final InetSocketAddress localAddress) {
sure

2023-06-14 14:05 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/IpfixTcpParser.java
> +import lombok.Getter;
right

2023-06-14 14:08 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/TelemetryRegistryImpl.java
> -import org.opennms.horizon.flows.document.FlowDocumentLog;
removed

2023-06-14 14:26 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/session/TcpSession.java
> +import java.net.InetSocketAddress;
removed

2023-06-14 14:28 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/session/TcpSession.java
> -import org.opennms.horizon.shared.utils.InetAddressUtils;
sure

2023-06-14 14:28 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/session/UdpSessionManager.java
> +import java.net.InetSocketAddress;
removed

2023-06-14 14:45 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/PayloadTest.java
> +import java.net.InetSocketAddress;
right

2023-06-14 14:45 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ipfix/BlackboxTest.java
> +import java.net.InetSocketAddress;
right

2023-06-14 14:45 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/netflow9/BlackboxTest.java
> +import java.net.InetSocketAddress;
right

2023-06-14 14:45 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ParserTest.java
> +import java.net.InetSocketAddress;
right

2023-06-14 14:46 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/NMS13006_Test.java
> +import java.net.InetSocketAddress;
right

2023-06-15 09:20 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/ParserBase.java
> +        return this.protocol.shortName;
removed

2023-06-15 09:20 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/shell/ClearSessionCmd.java
> +    @Option(name = "-f", aliases = "--feature", description = "specify feature short name")
removed

2023-06-15 09:20 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/shell/ClearSessionCmd.java
> +                    entry.getKey().getLocalAddress().getPort() == portNumber
removed

2023-06-15 09:20 UTC, FrancescoBuc86 commented on metrics-processor/flows/src/test/java/org/opennms/horizon/flows/integration/FlowRepositoryImplTest.java
> -                TenantLocationSpecificFlowDocumentLog.newBuilder()
done

2023-06-15 09:20 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/listeners/TcpParser.java
> +import org.opennms.horizon.minion.flows.parser.session.Session;
done

2023-06-15 09:21 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/IpfixTcpParser.java
>      private final Set<TcpSession> sessions = Sets.newConcurrentHashSet();
sure

2023-06-15 09:21 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/session/Session.java
> +    InetSocketAddress getLocalAddress();
right

2023-06-15 09:21 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/TelemetryRegistry.java
> +
removed

2023-06-15 09:21 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/TelemetryRegistryImpl.java
> +import org.opennms.horizon.minion.flows.listeners.TcpParser;
removed

2023-06-15 09:21 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/session/TcpSession.java
> +import lombok.Getter;
removed

2023-06-15 09:21 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/session/UdpSessionManager.java
> +    @Getter
removed

2023-06-15 09:21 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/session/UdpSessionManager.java
> +        @Getter
removed

2023-06-15 09:21 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/session/UdpSessionManager.java
> +    @Getter
removed

2023-06-15 09:21 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/shell/ClearUdpSessionCmd.java
> +    @Option(name = "-f", aliases = "--keyword", description = "specify protocol keyword")
done

2023-06-15 09:22 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/shell/ClearUdpSessionCmd.java
> +    int portNumber;
right, removed

2023-06-15 09:22 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/shell/ClearUdpSessionCmd.java
> +                if (udpParsers.isEmpty()) {
updated

2023-06-15 10:50 UTC, FrancescoBuc86 commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/session/UdpSessionManager.java
> +    @Getter
Well I could use this to check that the test to clean up the templates from sessions worked

2023-06-15 11:59 UTC, fooker requested changes

2023-06-15 11:59 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/session/TcpSession.java
> +
Revert.

2023-06-15 11:59 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/TelemetryRegistryImpl.java
> -import org.opennms.horizon.flows.document.FlowDocumentLog;
Still there.

2023-06-15 11:59 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/UdpParserBase.java
> +
Revert.

2023-06-15 11:59 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/session/UdpSessionManager.java
> +    @Getter
Sounds like overkill. no need to test JDK functions

2023-06-15 11:59 UTC, fooker commented on minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/shell/ClearUdpSessionCmd.java
> +        }
```suggestion
        final var matchedParser = flowsListener.getListeners().stream()
            .flatMap(listener -> listener.getParsers().stream())
            .filter(parser -> parserName.equals(parser.getName()))
            .findFirst();

        if (matchedParser.isEmpty()) {
            System.err.println("Parser not found: " + parserName);
            return null;
        }
        
        if (!UdpParser.class.isInstance(matchedParser)) {
        	System.err.println("Parser is not a UDP parser, silly: " + parserName);
        	return null;
        }
```

2023-06-15 11:59 UTC, fooker commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ParserTest.java
> -import com.google.common.base.Throwables;
Revert.

2023-06-15 11:59 UTC, fooker commented on minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/PayloadTest.java
> -import static org.hamcrest.CoreMatchers.containsString;
Revert.

2023-06-15 13:23 UTC, merged