Tilt: fix adding test location to database
OpenNMS-Cloud/lokahi pull request #1211
Opened 2023-06-09 22:12 UTC by deejgregor

Use the same code used in tests/minion-cert.sh for adding a location
and call it in the initContainer for the minion that sets up
certificates.

There are two known issues that can happen:
1. The ingress-nginx, keycloak, rest service, inventory service, and
   database aren't up when the init script runs.
2. If the rest service can't add the location to the inventory service,
   the rest service for any reasons, the rest service still returns a 200.
   So, this can appear to work but still fail. :( I'll open up a bug for
   that.

The workaround for both of these issues is to just delete the minion pod
or rollout restart the minion service and you should be good. E.g.:

    kubectl rollout restart deployment opennms-minion

This should ideally wait for the services to be up and/or retry a few
times, but for now, this is definitely better than the (completely broken)
solution that I had in place previously, and in my experience, it usually
works because the minion is one of the last things to be deployed. Oh,
fixing the service dependencies in Tilt might also help, but that might
add a lot of unnecessay deploys.

## Description

## Jira link(s)
- https://opennms.atlassian.net/browse/HS-xx

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts

2023-06-12 16:12 UTC, splatch requested changes
I'm a bit suspicious on making extra headers flying to clients thus I would like to clarify that point, and ideally remove them from http response to avoid people using these, even if its development level setting.

2023-06-12 16:12 UTC, splatch commented on tilt-helm-values.yaml
> +        add_header x-location "$authHeader1" always;
I am not very familiar with nginx, beyond all exercises I needed for this project, yet I am not sure if we need output headers for that. The `nginx.ingress.kubernetes.io/auth-response-headers` automatically maps `tenant-id` and `location` under the neath, without the need to use `$authHeaderN`, it also sets up `$upstream_http_tenant_id` variable:
```
			auth_request_set $authHeader0 $upstream_http_tenant_id;
			grpc_set_header 'tenant-id' $authHeader0;
			auth_request_set $authHeader1 $upstream_http_location;
			grpc_set_header 'location' $authHeader1;
```
Can we rely on `$upstream_http_location`? Regardless of this I'd consider getting the `more_clear_header` or `proxy_hide_header` just to avoid people trying to use these headers on client side.

2023-06-12 20:56 UTC, deejgregor commented on tilt-helm-values.yaml
> +        add_header x-location "$authHeader1" always;
> The nginx.ingress.kubernetes.io/auth-response-headers automatically maps tenant-id and location under the neath, without the need to use $authHeaderN, it also sets up $upstream_http_tenant_id variable

The `auth-response-headers` annotation doesn’t setup the `$upstream_http_tenant_id` variable—the [`auth_request_set`](https://nginx.org/en/docs/http/ngx_http_auth_request_module.html#auth_request_set) command **consumes** it to create a new variable, `$authHeader0`.

This is a challenge, I think, because the data we want to log is part of the **auth sub-request response**, and those don’t seem to be available with `$upstream_*` outside of the location that block that handles the sub-request. I couldn’t find a way to access headers from the **proxied request**. And I couldn’t use `$authHeader*` directly in the log format because it’s not available globally—only on authenticated minion requests.

I tried a **bunch** of permutations and this was the only one that I got working. :( And I didn’t find any examples of anyone else trying to do the same type of thing, unfortunately.

There probably is another, better way to do this, but I haven’t found it yet—maybe with a hack with a map to deal with the case when $authHeader* is unset, or there is a way to access proxied request headers, or toss some Lua code at it. But for now, I found this extremely useful, and it’s only in Tilt for now (and we can decide if/when we want to deploy it in our cloud environments).

2023-06-13 16:32 UTC, splatch commented on tilt-helm-values.yaml
> +        add_header x-location "$authHeader1" always;
Fair, I do understand implications, your reasoning is perfectly fine. Knowing a bit of ingress-nginx I'd rather stick with what you did rather than look for perfect solution which might not exist. 
I do think that long term solution should go towards use of secrets, instead of init containers, however this might be deferred.

2023-06-13 16:33 UTC, splatch approved these changes

2023-06-13 22:18 UTC, merged