HS-1674: Welcome screen queries
OpenNMS-Cloud/lokahi pull request #1213
Opened 2023-06-12 20:20 UTC by mikewrosey

## Description
Welcome screen queries.

## Jira link(s)
- https://opennms.atlassian.net/browse/HS-1674

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts

2023-06-16 20:47 UTC, mikewrosey commented on ui/src/App.vue
> +    v-if="ready"
There might be a better way.. this just hides the UI until the setup status for the welcome page is determined.

2023-06-16 20:53 UTC, mikewrosey commented on ui/src/store/Views/welcomeStore.ts
> +            tags
Our backend currently does not support a community string or port field. Created this task here to track https://opennms.atlassian.net/browse/HS-1736

2023-06-16 20:56 UTC, mikewrosey commented on ui/src/store/Views/welcomeStore.ts
> +        // is this preview supposed to be 'faked'?
We'll have to bring this up for discussion. I'm not sure how we would render a real status here, unless we do something hacky like add the default tag for monitoring ahead of time, and then delete it if the user chooses to 'skip' to the dashboard.

2023-06-16 20:58 UTC, mikewrosey commented on ui/src/store/Queries/welcomeQueries.ts
> +  const defaultLocationName = 'TestLocation'
The name here will likely change before EAR. TBD

2023-06-16 20:59 UTC, mikewrosey commented on ui/src/store/Views/welcomeStore.ts
> +      return `docker run --rm -p 8181:8181 -p 8101:8101 -p 1162:1162/udp -p 8877:8877/udp -p 4729:4729/udp -p 9999:9999/udp -p 162:162/udp -e TZ='America/New_York' -e USE_KUBERNETES="false" -e MINION
Will not be able to test this with tilt. I did test the command on dev and it spun up the minion.

2023-06-22 20:42 UTC, scthompsonopen commented on ui/src/App.vue
> +    v-if="ready"
It's a fine way for now. :) I have some timeouts in place to hopefully prevent the flash of the dashboard before it's hidden for the welcome guide, but I'd rather have something definitive in place instead of timeouts.

2023-06-22 20:43 UTC, scthompsonopen commented on ui/src/store/Views/welcomeStore.ts
> +            tags
Swapped for a Discovery instead of a Device, so all good here.

2023-06-22 20:43 UTC, scthompsonopen commented on ui/src/store/Views/welcomeStore.ts
> +        // is this preview supposed to be 'faked'?
Went with a discovery for now which has enough of the information for us to display this component.

2023-06-22 20:43 UTC, scthompsonopen commented on ui/src/store/Queries/welcomeQueries.ts
> +  const defaultLocationName = 'TestLocation'
It's now 'default'

2023-06-22 20:44 UTC, scthompsonopen commented on ui/src/store/Views/welcomeStore.ts
> +      return `docker run --rm -p 8181:8181 -p 8101:8101 -p 1162:1162/udp -p 8877:8877/udp -p 4729:4729/udp -p 9999:9999/udp -p 162:162/udp -e TZ='America/New_York' -e USE_KUBERNETES="false" -e MINION
I have a local command in place now which should work for a local setup, but should not display when the code is in dev/prod.

2023-06-23 15:02 UTC, mikewrosey commented on ui/src/store/Views/welcomeStore.ts
> +      if (location.origin === 'https://onmshs.local:1443') {
Not sure if I missed something but for me it only worked using `location.origin.includes('localhost')` here. Not sure how else it would pick up the `VITE_MINION_PATH` var in the local env file.

2023-06-23 15:04 UTC, mikewrosey commented
A couple small rendering issues..

These buttons overlap with the box, on my laptop.
![screenshot-localhost_3009-2023 06 23-10_55_10](https://github.com/OpenNMS-Cloud/lokahi/assets/8680122/f67781f4-de06-4041-86aa-1d7b9ecb2761)

This seems stuck in a loading state, even though the call is returning with the discovery. Could still continue though.
![screenshot-localhost_3009-2023 06 23-10_55_53](https://github.com/OpenNMS-Cloud/lokahi/assets/8680122/5cc5c808-af00-4a0c-a850-30fcdca23d00)

2023-06-23 15:10 UTC, mikewrosey commented on ui/src/services/validationService.ts
> +import { ValidationError } from "yup";
not a big deal but in terms of style we've so far avoided semi-colons throughout

2023-06-23 15:22 UTC, mikewrosey commented on ui/src/store/Queries/locationQueries.ts
> +  }
So far we've attempted to match the queries files to a specific view. For example, all the queries in this file would be for the Locations page, the queries in monitoringPolicyQueries.ts would be for the MP page, etc. 
A different way of doing it would be like how you have here - we'd use the file for fetchLocationsForWelcome, fetchLocationsForDiscovery, fetchLocationsForMinionsPage, etc. 
I'm really ok with either but if we do it the second way, some rearrangement will be needed to make things consistent.

2023-06-23 15:29 UTC, mikewrosey commented on ui/src/store/Views/welcomeStore.ts
> +        { title: 'SNMP Uptime', status: 'Normal', statusColor: '#cee3ce', statusText: '#0b720c' }
We might want to use some variables listed here https://feather.nanthealth.com/demos#/Styles-Status which should help us with dark mode. These are not well documented yet, and we might need to update the feather packages to get them, so maybe in a subsequent PR.

2023-06-23 18:41 UTC, scthompsonopen commented on ui/src/store/Views/welcomeStore.ts
> +      if (location.origin === 'https://onmshs.local:1443') {
I've updated to look for either the local https or http address. I wanted to make them relatively specific so there would be no chance of it trigger incorrectly in PROD.

Ideally we'd move this check to a build-time env variable that would be definitively set for local development so there's no guessing.

2023-06-23 20:48 UTC, Bonrob2 requested changes
A few minor text changes. Thanks!
Additional questions. I realize some of these are non-happy path questions, but asking them anyway.

1. Should the "Start Setup" button be on the right instead of the left?
2. What is the message if a Minion is not detected?
3. Do we need a warning or information to pop up if they click "Skip" in the setup device section?
4. Where do they go if they do click "Skip" in the start first discovery section?
5. What happens if the discovery doesn't find anything?

2023-06-23 20:48 UTC, Bonrob2 commented on ui/src/components/Welcome/WelcomeSlideOne.vue
> +        <CollapsingCard title="Requirements: Before you Begin" :open="welcomeStore.slideOneCollapseVisible"
```suggestion
        <CollapsingCard title="Requirements: Before You Begin" :open="welcomeStore.slideOneCollapseVisible"
```

2023-06-23 20:48 UTC, Bonrob2 commented on ui/src/components/Welcome/WelcomeSlideTwo.vue
> +                    <pre>Replace pathToFile with the path to the certificate. (e.g. /tmp/)</pre>
```suggestion
                    <pre>Replace pathToFile with the path to the certificate. (e.g., /tmp/)</pre>
```

2023-06-23 20:48 UTC, Bonrob2 commented on ui/src/components/Welcome/WelcomeSlideOne.vue
> +                <a href="#">How to set up Docker
Where is this link going to go?

2023-06-23 20:48 UTC, Bonrob2 commented on ui/src/components/Welcome/WelcomeSlideOne.vue
> +                for distributed network monitoring. We'll walk you through that setup, which only takes a
```suggestion
                for distributed network monitoring. We'll walk you through that setup, which takes only a
```

2023-06-23 20:48 UTC, Bonrob2 commented on ui/src/components/Welcome/WelcomeSlideTwo.vue
> +                    <a href="#">Learn More About Locations</a>
where does this link go?

2023-06-23 20:48 UTC, Bonrob2 commented on ui/src/store/Views/welcomeStore.ts
> +        this.minionStatusCopy = 'Minion Detected.'
```suggestion
        this.minionStatusCopy = 'Minion detected.'
```

2023-06-23 20:48 UTC, Bonrob2 commented on ui/src/components/Welcome/WelcomeSlideThree.vue
> +                <p>We've populated the fields from your Minion deployement.</p>
```suggestion
                <p>We've populated the fields from your Minion deployment.</p>
```

2023-06-23 20:48 UTC, Bonrob2 commented on ui/src/components/Welcome/WelcomeSlideThree.vue
> +                <h2>Start your first discovery</h2>
```suggestion
                <h2>Start Your First Discovery</h2>
```

2023-06-23 20:48 UTC, Bonrob2 commented on ui/src/store/Views/welcomeStore.ts
> +        this.minionStatusCopy = 'Please wait while we detect your minion'
```suggestion
        this.minionStatusCopy = 'Please wait while we detect your Minion.'
```

2023-06-23 20:48 UTC, Bonrob2 commented on ui/src/components/Common/ItemPreview.vue
> +      <div>Loading first discovery</div>
```suggestion
      <div>Loading first discovery.</div>
```

2023-06-26 10:13 UTC, scthompsonopen commented on ui/src/components/Welcome/WelcomeSlideOne.vue
> +                <a href="#">How to set up Docker
I don't have a link for that yet. I assume it will go to some kind of documentation we have for setting up Docker? Or possibly some documentation from Docker's website?

2023-06-26 10:14 UTC, scthompsonopen commented on ui/src/components/Welcome/WelcomeSlideTwo.vue
> +                    <a href="#">Learn More About Locations</a>
Same as above. I'm not sure, I didn't receive links from anyone. So I assume some documentation we have about Locations?

2023-06-26 10:27 UTC, scthompsonopen commented
> A few minor text changes. Thanks! Additional questions. I realize some of these are non-happy path questions, but asking them anyway.
> 
>     1. Should the "Start Setup" button be on the right instead of the left?
> 
>     2. What is the message if a Minion is not detected?
> 
>     3. Do we need a warning or information to pop up if they click "Skip" in the setup device section?
> 
>     4. Where do they go if they do click "Skip" in the start first discovery section?
> 
>     5. What happens if the discovery doesn't find anything?

1. It's on the left in the approved design, so I'll leave it there until that changes. 
![image](https://github.com/OpenNMS-Cloud/lokahi/assets/86311553/2113a517-8af3-4b85-a7bf-fa1cd286d422)

2. There isn't one. As far as I can tell we need to trigger the Pendo failure state in that scenario and load the Minion Help guide? I don't have any of the details for that yet though, so right now it just waits an infinite amount of time for a minion to come up.

To remedy that, I just need to know how long we wait total before triggering the pendo failure state (10 minutes?) and then the snippet of Pendo Javascript code/API that triggers the Pendo guide (if you don't have that, we can work together I imagine to put it together. It's mostly likely a single line of code or at most 2 or 3)

3. I'll leave that answer to UX. Currently the only thing that happens when you click Skip is we close the Welcome Guide/Wizard and show you the dashboard.

4. The Dashboard, but we could send them anywhere if the dashboard is no good.

5. As far as I can tell how a Discovery works, is no matter what you put in to those boxes (assuming they're accepted by the FE validation), you'll get a Discovery back from the BE, but it will be in a DOWN state until it gets traffic from it. What I do, is I don't show that DOWN state right away, I wait for a full minute and a half to see if the Discovery ever changes to the UP state. If after a full minute and a half goes by with no UP state, we show the DOWN state of the discovery.

In terms of edge cases beyond these, this particular feature changed multiple times within a single sprint (including changes to functionality and UX), so I was attempting to hit a very fast moving target operating outside of any standard development procedures. So what's in this PR is very much happy-path only, and we can nail down edge cases in upcoming sprints.

2023-06-26 14:50 UTC, Bonrob2 commented on ui/src/components/Welcome/WelcomeSlideOne.vue
> +                <a href="#">How to set up Docker
Yes, probably should go to the Docker docs. Looks like their install links are OS-specific (no general topic). Here's one for now: https://docs.docker.com/desktop/install/mac-install/

2023-06-26 14:53 UTC, Bonrob2 commented on ui/src/components/Welcome/WelcomeSlideTwo.vue
> +                    <a href="#">Learn More About Locations</a>
Yes. Links should be included with this work, so I'll talk to UX again to make sure they ask me for the links so I can include them. 
Most are place holders until we have the docs available, but they will work once that happens.
This is the stub: `/cloud/locations.html` (it will eventually be `docs.opennms.com/cloud/locations.html`).

2023-06-26 14:54 UTC, Bonrob2 approved these changes
Thanks for the text updates. I've added suggestions for links in my comments.

2023-06-26 17:20 UTC, Bonrob2 commented
> To remedy that, I just need to know how long we wait total before triggering the pendo failure state (10 minutes?) and then the snippet of Pendo Javascript code/API that triggers the Pendo guide (if you don't have that, we can work together I imagine to put it together. It's mostly likely a single line of code or at most 2 or 3)
> 

Thanks. Yes, you're correct. It will go to a Pendo guide (see PEN-28). @joseOpenNMS could you remind me what the timeout for detecting a Minion would be before we trigger a guide?

2023-06-26 17:20 UTC, Bonrob2 approved these changes
Text changes LGTM. Thanks!

2023-06-27 15:39 UTC, scthompsonopen approved these changes
This PR is in a weird approval state because Mike opened it, but I finished it. He's approved it a few times now, so we're going ahead with the merge.

2023-06-27 15:41 UTC, merged