HS-1627
OpenNMS-Cloud/lokahi pull request #1234
Opened 2023-06-21 01:30 UTC by freddy61025

## Description
Align with PKI add revoke certificate and validate certificate serial number in certificate manger
BFF delete location will trigger revoke certificate if location successfully removed 

Will followup with https://opennms.atlassian.net/browse/HS-1737

## Jira link(s)
- https://opennms.atlassian.net/browse/HS-1626
- https://opennms.atlassian.net/browse/HS-1627

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts

2023-06-21 18:26 UTC, artnaseef reviewed
Didn't finish; want to catch up offline to discuss...

2023-06-21 18:26 UTC, artnaseef commented on minion-certificate-manager/main/src/main/java/org/opennms/horizon/minioncertmanager/certificate/SerialNumberRepository.java
> +        LOG.info("Begin to init rocksDB of {}", rootDir);
Grammar nit.  Maybe reword to "Beginning init of rocksDB at {}".

Another thought - I personally use the logging syntax "<message>: <key>=<value>; ..." - goes back to using Splunk.  So in this case, I would personally do something like this - `Beginning init of rocksDB: db-path={}`

2023-06-21 18:26 UTC, artnaseef commented on minion-certificate-manager/main/src/main/java/org/opennms/horizon/minioncertmanager/certificate/SerialNumberRepository.java
> +        db.put(meta.getSerial().getBytes(), mapper.writeValueAsBytes(meta));
Can the key use the tenant-id and location-id so lookups avoid the linear search?  If rocks DB doesn't support a composite key, then we could format something like `TENANT-ID=<tenant>|LOCATION=<location>` - a syntax like that should make conflicting keys almost impossible, and completely infeasible.

Another question - is it possible in rocks DB to have the value be a list?  If not, perhaps we can store the value as JSON text containing a list of the valid certificate serial numbers?

Looking ahead, I see there's a need to be able to lookup the cert just by serial number... I'm going to reach out offline to discuss more.

2023-06-21 18:48 UTC, freddy61025 commented on minion-certificate-manager/main/src/main/java/org/opennms/horizon/minioncertmanager/certificate/SerialNumberRepository.java
> +        db.put(meta.getSerial().getBytes(), mapper.writeValueAsBytes(meta));
The main target is to make certificate don't contain any custom values in subject. We only use serial number as key.

2023-06-21 18:56 UTC, freddy61025 commented on minion-certificate-manager/main/src/main/java/org/opennms/horizon/minioncertmanager/certificate/SerialNumberRepository.java
> +    public SerialNumberRepository(@Value("${grpc.server.db:/app/db}") String rootDir) throws RocksDBException{
I will change it. It just my personal preference to make names more generic. That switching backend will not affect paths.

2023-06-21 19:30 UTC, artnaseef requested changes

2023-06-21 19:30 UTC, artnaseef commented on minion-certificate-manager/main/src/main/java/org/opennms/horizon/minioncertmanager/certificate/SerialNumberRepository.java
> +        db.put(meta.getSerial().getBytes(), mapper.writeValueAsBytes(meta));
On follow-up, we don't need to optimize this solution, so no changes needed here.

2023-06-21 19:30 UTC, artnaseef commented on minion-certificate-manager/main/src/test/resources/test-output-dir/client.signed.cert
Is this file a test input or test output?

If output, then please delete.  I recommend also adding the folder to the `.gitignore` file.  Or, better yet, move the test path to use the `target/` folder instead of `src/test/resources` for test output - tests should never write to any place under `src/`.

2023-06-21 19:30 UTC, artnaseef commented on rest-server/src/main/java/org/opennms/horizon/server/service/GrpcLocationService.java
> +        if (status) {
It might be good to call revoke even if delete fails, because it is possible the location could get deleted but the certificate doesn't get revoked due to a service crash or other scenario.

2023-06-21 19:55 UTC, freddy61025 commented on minion-certificate-manager/main/src/test/resources/test-output-dir/client.signed.cert
It is a test input. It is for PKCS12GeneratorTest.
PKCS12GeneratorTest itself is mocking the CommandExecutor, openssl is never be called. That said getX509Certificate will never able to find the real cert. The only way i can think of is put a fake file in test output folder. The other way is to spy PKCS12Generator and override getX509Certificate. (However for PKCS12GeneratorTest, I don't want to spy PKCS12Generator)

2023-06-21 20:02 UTC, freddy61025 commented on minion-certificate-manager/main/src/main/java/org/opennms/horizon/minioncertmanager/certificate/SerialNumberRepository.java
> +    public SerialNumberRepository(@Value("${grpc.server.db:/app/db}") String rootDir) throws RocksDBException{
done

2023-06-21 20:02 UTC, freddy61025 commented on rest-server/src/main/java/org/opennms/horizon/server/service/GrpcLocationService.java
> +        if (status) {
done

2023-06-21 20:05 UTC, freddy61025 commented on minion-certificate-manager/main/src/main/java/org/opennms/horizon/minioncertmanager/certificate/SerialNumberRepository.java
> +        LOG.info("Begin to init rocksDB of {}", rootDir);
done

2023-06-22 21:34 UTC, artnaseef requested changes

2023-06-22 21:34 UTC, artnaseef commented on minion-certificate-manager/docker-it/src/test/java/org/opennms/horizon/minioncertmanager/stepdefs/MinionCertificateManagerTestSteps.java
> +    @Then("send isValid with last serial number and timeout {int}ms")
The wording on this step is a little unclear to me.  How about the following instead?

    send "isValid" request with last serial number and timeout {int}ms

2023-06-22 21:34 UTC, artnaseef commented on minion-certificate-manager/docker-it/src/test/java/org/opennms/horizon/minioncertmanager/stepdefs/MinionCertificateManagerTestSteps.java
> +            null);
Is there some timing here where it might come back as invalid but then later come back as valid?  If not, then the retries can be removed.

2023-06-22 21:34 UTC, artnaseef commented on minion-certificate-manager/main/src/test/java/org/opennms/horizon/minioncertmanager/certificate/PKCS12GeneratorTest.java
> +            outputDirPath.toFile().getAbsolutePath() + FileSystems.getDefault().getSeparator() + "client.signed.cert");
I like the use of the `mockCertificateReader`.

One thing I recommend here - instead of directly verifying the `getX509Certificate` method was called, use a `Mockito.when(...)` on that call and have it return a value.  Then, capture the return value fro the call to `generate` above, and compare them.

The advantage of that approach is not only does it make sure the right method call is made, it also ensures the result of that method call is returned by the `generate` method itself.  Then the `Mockito.verify(...)` of that method call is no longer needed, because the test already proves it is called.

2023-06-22 21:34 UTC, artnaseef commented on minion-certificate-manager/main/src/main/java/org/opennms/horizon/minioncertmanager/certificate/CertificateReader.java
> +public class CertificateReader {
This looks good.

2023-06-22 22:02 UTC, freddy61025 commented on minion-certificate-manager/docker-it/src/test/java/org/opennms/horizon/minioncertmanager/stepdefs/MinionCertificateManagerTestSteps.java
> +            null);
i just think using the retry util is a common practices.

2023-06-22 22:03 UTC, freddy61025 commented on minion-certificate-manager/main/src/test/java/org/opennms/horizon/minioncertmanager/certificate/PKCS12GeneratorTest.java
> +            outputDirPath.toFile().getAbsolutePath() + FileSystems.getDefault().getSeparator() + "client.signed.cert");
done

2023-06-22 22:40 UTC, artnaseef approved these changes

2023-06-23 02:20 UTC, merged