HS-1737: make certificate verifier rely on serial number
OpenNMS-Cloud/lokahi pull request #1251
Opened 2023-06-27 05:43 UTC by freddy61025

## Description

## Jira link(s)
- https://opennms.atlassian.net/browse/HS-1737

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2023-06-29 16:23 UTC, splatch approved these changes
No blockers from my side - there is one comment about `location-id` attribute for spans which you need to check with devops.

2023-06-29 16:40 UTC, freddy61025 commented on minion-certificate-verifier/main/src/main/java/org/opennms/horizon/minioncertverifier/controller/CertificateController.java
> +        String cert = request.getHeader("ssl-client-cert");
good point let me check will nginx forward expired cert to us.

2023-06-29 18:29 UTC, deejgregor commented on minion-certificate-verifier/main/src/main/java/org/opennms/horizon/minioncertverifier/controller/CertificateController.java
> +            span.setAttribute("message", "Invalid certificate");
What you want to do here is record the exception using [`recordException`](https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/exceptions/#recording-an-exception). Note: we don't need to mark this as an "escaped exception" because we don't re-throw the exception.
--


<br class="Apple-interchange-newline">

```suggestion
            span.recordException(ex);
            span.setStatus(StatusCode.ERROR, "invalid certificate: " + ex);
```

2023-06-29 18:41 UTC, deejgregor requested changes
See suggestions for the controller (one or two more coming)

2023-06-29 18:41 UTC, deejgregor commented on minion-certificate-verifier/main/src/main/java/org/opennms/horizon/minioncertverifier/controller/CertificateController.java
> +            span.setAttribute("message", "Invalid certificate. serial number: " + parser.getSerialNumber());
```suggestion
            span.setStatus(StatusCode.ERROR, "certificate manager reported that certificate is invalid");
```

2023-06-29 18:41 UTC, deejgregor commented on minion-certificate-verifier/main/src/main/java/org/opennms/horizon/minioncertverifier/controller/CertificateController.java
> +            parser = new CertificateParser(certificatePem);
If we can successfully parse the serial number, always add it as a span attribute. Then you can always search traces based on serial number and it will be available for debugging.

```suggestion
            parser = new CertificateParser(certificatePem);
            span.setAttribute("serial-number", parser.getSerialNumber());
```

2023-06-29 18:41 UTC, deejgregor commented on minion-certificate-verifier/main/src/main/java/org/opennms/horizon/minioncertverifier/controller/CertificateController.java
> +                .header(TENANTID_KEY, tenant)
When the request is unauthorized, I don't think you want to return these headers.

2023-06-29 18:44 UTC, deejgregor commented on minion-certificate-verifier/main/src/main/java/org/opennms/horizon/minioncertverifier/controller/CertificateController.java
> +            span.setAttribute("message", "Invalid certificate");
If it might be useful, you could also add the problematic certificate itself as an attribute. Actually, the more I think about it, I think it would be a good idea. Then, if you need to debug a parsing issue, you have *everything* you need here to do so.

2023-06-29 18:46 UTC, freddy61025 commented on minion-certificate-verifier/main/src/main/java/org/opennms/horizon/minioncertverifier/controller/CertificateController.java
> +                .header(TENANTID_KEY, tenant)
my reason to return it just hoping it can assist troubleshooting. Will that able to trace?

2023-06-29 18:49 UTC, deejgregor commented on minion-certificate-verifier/main/src/main/java/org/opennms/horizon/minioncertverifier/controller/CertificateController.java
> +            span.setAttribute(LOCATIONID_KEY, location);
I'd suggest leaving the tenant attribute name as "user". Here's some background on why: https://github.com/OpenNMS-Cloud/lokahi/pull/1167#discussion_r1212585233

If we change either of these names, we should change it in the other places: `git grep -E 'setAttribute\("(user|location)'`

2023-06-29 20:34 UTC, freddy61025 commented on minion-certificate-verifier/main/src/main/java/org/opennms/horizon/minioncertverifier/controller/CertificateController.java
> +        String cert = request.getHeader("ssl-client-cert");
I have tested. Nginx will not trigger verifier if certificate is invalid or expired.

![image](https://github.com/OpenNMS-Cloud/lokahi/assets/7125494/27096ec8-51e1-44df-9ab1-05fe6edcf20a)

2023-06-29 20:46 UTC, freddy61025 commented on minion-certificate-verifier/main/src/main/java/org/opennms/horizon/minioncertverifier/controller/CertificateController.java
> +            parser = new CertificateParser(certificatePem);
done

2023-06-29 20:47 UTC, freddy61025 commented on minion-certificate-verifier/main/src/main/java/org/opennms/horizon/minioncertverifier/controller/CertificateController.java
> +            span.setAttribute("message", "Invalid certificate. serial number: " + parser.getSerialNumber());
done

2023-06-29 20:48 UTC, freddy61025 commented on minion-certificate-verifier/main/src/main/java/org/opennms/horizon/minioncertverifier/controller/CertificateController.java
> +            span.setAttribute("message", "Invalid certificate");
done

2023-06-29 20:48 UTC, freddy61025 commented on minion-certificate-verifier/main/src/main/java/org/opennms/horizon/minioncertverifier/controller/CertificateController.java
> +            span.setAttribute(LOCATIONID_KEY, location);
done

2023-06-30 17:55 UTC, deejgregor approved these changes

2023-06-30 18:19 UTC, merged