HS-1783, HS-1772: Store alertable events in alert service database
OpenNMS-Cloud/lokahi pull request #1285
Opened 2023-07-07 15:30 UTC by geraldhumphries

## Description

- Refactors alert service to store its list of alertable events as an entity called EventDefinition (final name TBD)
- Adds API for EventDefinition
- Queries for EventDefinitions on the frontend and uses them in the alert condition form
- EventType enum has been repurposed to specify "SNMP trap", "internal event", etc.

Todo:
- Rename EventDefinition to something better like AlertableEvent
- Fix `watch` not working properly in AlertCondition form
- Sort out the EventType input on the PolicyRule form

## Jira link(s)
- https://opennms.atlassian.net/browse/HS-1783
- https://opennms.atlassian.net/browse/HS-1772

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2023-07-11 11:49 UTC, scthompsonopen requested changes
I was going to approve because 95% of my comments are nits, but there's some commented out code at the end of this PR that disables the welcome guide so I can't approve until that is restored. :)

2023-07-11 11:49 UTC, scthompsonopen commented on ui/src/components/MonitoringPolicies/MonitoringPoliciesCard.vue
> +<!--    TODO: Bring this back when thresholding is implemented
I would recommend creating a JIRA for this TODO so we can track it properly.

2023-07-11 11:49 UTC, scthompsonopen commented on ui/src/components/MonitoringPolicies/MonitoringPoliciesRuleForm.vue
> +                :index="index as number"
Same comment as above, both are nits and possible to ignore in a time crunch though.

2023-07-11 14:32 UTC, geraldhumphries commented on ui/src/components/MonitoringPolicies/MonitoringPoliciesRuleForm.vue
> +                :index="index as number"
Index from `v-for` is type `string | number` according to IntelliJ but the component prop is `number`, so it's showing an error. I don't think it had any real impact, implicit type casting was taking care of it. I've changed it to `Number(index)`.

2023-07-11 17:01 UTC, mikewrosey commented
As all rules need at least 1 condition with a trigger event, we had this pre-populated with the first option. Should we keep that? If the user attempts to save the policy with the condition as is, it will throw an error.
![screenshot-localhost_3009-2023 07 11-12_58_02](https://github.com/OpenNMS-Cloud/lokahi/assets/8680122/18fbe724-74ec-444b-93c6-1facc15004d5)

2023-07-11 17:04 UTC, mikewrosey commented on ui/src/components/MonitoringPolicies/MonitoringPoliciesEventCondition.vue
> -  { id: SNMPEventType.SNMP_EGP_DOWN, name: 'SNMP EGP Down'}
Looks like this enum `SNMPEventType` is no longer used anywhere. We could remove it entirely from monitoringPolicies.constants.ts

2023-07-12 15:21 UTC, geraldhumphries commented on ui/src/store/Views/welcomeStore.ts
> +      onboardingState = false
Oops!

2023-07-12 15:57 UTC, geraldhumphries commented
> As all rules need at least 1 condition with a trigger event, we had this pre-populated with the first option. Should we keep that? If the user attempts to save the policy with the condition as is, it will throw an error. ![screenshot-localhost_3009-2023 07 11-12_58_02](https://user-images.githubusercontent.com/8680122/252736650-18fbe724-74ec-444b-93c6-1facc15004d5.png)



> As all rules need at least 1 condition with a trigger event, we had this pre-populated with the first option. Should we keep that? If the user attempts to save the policy with the condition as is, it will throw an error. ![screenshot-localhost_3009-2023 07 11-12_58_02](https://user-images.githubusercontent.com/8680122/252736650-18fbe724-74ec-444b-93c6-1facc15004d5.png)

For now I've disabled the save button when there's no triggerEvent on a condition. I think it needs another look, but I suspect the UX will change.

2023-07-12 16:04 UTC, scthompsonopen approved these changes
LGTM, at least the FE portions from a code review standpoint. I can't speak for the BE portions, nor did I manually test this (I'll leave that to those who understand the feature better, I wouldn't know where to start).

2023-07-12 17:15 UTC, cgorantla approved these changes
LGTM!

2023-07-12 18:01 UTC, merged