HS-1666: Tidy up Tag Manager on Inventory Page
OpenNMS-Cloud/lokahi pull request #1287
Opened 2023-07-10 13:34 UTC by scthompsonopen

## Description
Bonnie made a request to clarify/simplify the Tag Manager on the Network Inventory page. Knowing that the UI/UX team would most likely be completely overhauling this page post-EAR, I decided to take a quick pass without their involvement to see if I could clean up a few interactions.

I did show the updates off to the UX team in a meeting last week, and they had some minor feedback which I've addressed in this ticket (including the instructions in a point-form list, and re-including the select-all/clear functionality)

One of the biggest changes we made was to include the EmptyList component when we did not have any node results.

We have an opportunity now to direct the user to a more appropriate location for all three node types. This text can be specific on each tab.

## All Three Tabs Empty
![image](https://github.com/OpenNMS-Cloud/lokahi/assets/86311553/de1e6708-8889-418b-84e2-dbb5534c52b5)
![image](https://github.com/OpenNMS-Cloud/lokahi/assets/86311553/1357a7f8-4fa9-4d39-bcde-12d451e44c70)
![image](https://github.com/OpenNMS-Cloud/lokahi/assets/86311553/096f4231-bcf1-428f-a97d-808a292c13b8)

## We've also included a Feather Numerical Badge next to the name of the tab if it has results
![image](https://github.com/OpenNMS-Cloud/lokahi/assets/86311553/a2a1c194-ec18-4b5d-bdc3-6a52c6f8b726)

## When expanded the Tag Manager is now a bit more streamlined
![image](https://github.com/OpenNMS-Cloud/lokahi/assets/86311553/56208122-69af-480f-96b2-1d83e3068993)

## Clicking on the input field will show a list of existing Tags
![image](https://github.com/OpenNMS-Cloud/lokahi/assets/86311553/f965be14-7e45-4164-bc96-c02518c6daa9)

## Select a Tag will add it to the Active Tag List
![image](https://github.com/OpenNMS-Cloud/lokahi/assets/86311553/e5656fe2-7579-4423-a48e-17b0a9422b7e)

## Select a Checkbox on a Node to add the active tags to the pending tags
![image](https://github.com/OpenNMS-Cloud/lokahi/assets/86311553/20d2a829-639f-4f4f-8efc-b5c600a16639)

## You can also use the Select All and Clear Selection buttons.
![image](https://github.com/OpenNMS-Cloud/lokahi/assets/86311553/820549e1-b4db-432a-bcaa-fa0054ef5f55)

Clicking on 'Save Tags To Nodes' will then save those new Tags to your list of existing tags.

## Deleting Tags from a node remains unchanged
![image](https://github.com/OpenNMS-Cloud/lokahi/assets/86311553/9c812fa2-bea5-4641-9587-c83459e47a3d)

## Complete Video of new Process
https://github.com/OpenNMS-Cloud/lokahi/assets/86311553/8dd53dc7-1230-4015-ac59-024535ca78bc

## Jira link(s)
- https://opennms.atlassian.net/browse/HS-1666

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2023-07-10 14:40 UTC, Bonrob2 requested changes
Some minor changes.

2023-07-10 14:40 UTC, Bonrob2 commented on ui/src/containers/Inventory.vue
> +        :content="{ msg: 'No Unmonitored Nodes. Add some on the Minions page.', btn: { label: 'Visit Minions Page', action: () => { $router.push('/minions') } } }" />
```suggestion
        :content="{ msg: 'No unmonitored nodes. Add some on the Minions page.', btn: { label: 'Visit Minions Page', action: () => { $router.push('/minions') } } }" />
```

2023-07-10 14:40 UTC, Bonrob2 commented on ui/src/containers/Inventory.vue
> +        :content="{ msg: 'No Detected Nodes. Add some on the Minions page.', btn: { label: 'Visit Minions Page', action: () => { $router.push('/minions') } } }" />
```suggestion
        :content="{ msg: 'No detected nodes. Add some on the Minions page.', btn: { label: 'Visit Minions Page', action: () => { $router.push('/minions') } } }" />
```

2023-07-10 16:54 UTC, scthompsonopen commented on ui/src/components/Inventory/InventoryTagManager.vue
> +          <li>Using the search, find an existing tag or create a new one.</li>
I've adjusted for this manually.

![image](https://github.com/OpenNMS-Cloud/lokahi/assets/86311553/0ba9ba46-426d-49bc-bf67-7093c66cde16)

2023-07-10 16:55 UTC, scthompsonopen commented on ui/src/components/Inventory/InventoryTagManager.vue
> +          <li>Click Save Tags to Node</li>
I've adjusted for this manually, by making the text bold (which I think is what happens with double asterixes in markdown). I had to translate to HTML.

2023-07-10 17:18 UTC, Bonrob2 commented on ui/src/components/Inventory/InventoryTagManager.vue
> +          <li>Using the search, find an existing tag or create a new one.</li>
Looks good except step 3 needs a period. Sorry I missed that the first time around!

2023-07-10 17:19 UTC, Bonrob2 commented on ui/src/components/Inventory/InventoryTagManager.vue
> +          <li>Click <strong>Save Tags to Node</strong></li>
```suggestion
          <li>Click <strong>Save Tags to Node</strong>.</li>
```

2023-07-10 17:19 UTC, Bonrob2 reviewed
looks good. Just a period I missed. Thanks!

2023-07-10 17:24 UTC, Bonrob2 approved these changes
Text LGTM!

2023-07-10 17:36 UTC, mikewrosey commented on ui/src/store/Queries/inventoryQueries.ts
> +    detectedNodes.value = []
Deleting a detected node works, but no longer refreshes the page after, so the deleted node stays in the UI. User has to refresh to see it gone. Clicking delete again causes an unknown error.

Similar for other monitored states.

![screenshot-localhost_3009-2023 07 10-13_27_01](https://github.com/OpenNMS-Cloud/lokahi/assets/8680122/fcfbb580-565f-477a-bafb-6116b8f62803)

2023-07-10 17:41 UTC, mikewrosey commented on ui/src/containers/Inventory.vue
> +        :content="{ msg: 'No monitored nodes. Add some on the Minions page.', btn: { label: 'Visit Minions Page', action: () => { $router.push('/minions') } } }" />
Probably OK for now, but it might make more sense to send the user to /discovery, because /minions will be going away.

2023-07-10 17:46 UTC, scthompsonopen commented on ui/src/store/Queries/inventoryQueries.ts
> +    detectedNodes.value = []
I'll fix that! I didn't think to test deleting nodes. Good catch.

2023-07-10 17:46 UTC, scthompsonopen commented on ui/src/containers/Inventory.vue
> +        :content="{ msg: 'No monitored nodes. Add some on the Minions page.', btn: { label: 'Visit Minions Page', action: () => { $router.push('/minions') } } }" />
Definitely makes sense. I wasn't sure where to send them, and Jose had the same comment (that Minions was going away). I'll update it to go to the discovery page (and update the button copy as well).

2023-07-11 13:37 UTC, mikewrosey approved these changes
Looks good!

2023-07-12 11:15 UTC, merged