Implemented automation test for monitoring policy.
OpenNMS-Cloud/lokahi pull request #1293
Opened 2023-07-10 22:30 UTC by JohnWang-NMS

## Description
Created Cucumber/Gherkin automation tests for monitoring policy. Test scenario - https://confluence.internal.opennms.com/pages/viewpage.action?pageId=143827267

## Jira link(s)
- https://opennms.atlassian.net/browse/HS-1679

## Checklist
* [x] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [x] Appropriate reviewer(s) have been selected.
* [x] Jira issue(s) have been updated to "In Review".
* [x] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2023-07-10 22:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1293) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1293) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenNMS-Cloud/lokahi?pullRequest=1293) it.</sub>

2023-07-11 16:30 UTC, bouff commented on test-automation/integration-tests/src/main/resources/org/opennms/horizon/it/monitoring-policy.feature
> +    Given Tenant id "test-mp-tenant"
As per discussion yesterday, should be removed. 

If possible to set this, then will need a ticket to ensure this isn't possible for on-prem.

2023-07-11 16:30 UTC, bouff commented on test-automation/integration-tests/src/main/java/org/opennms/horizon/it/MonitoringPolicyTestSteps.java
> +    public MonitoringPolicyTestSteps(TestsExecutionHelper helper) { this.helper = helper; }
Please format the Java code throughout.  If you're using IntelliJ, please use the built-in formatter.

We need to have consistent code style throughout.

2023-07-11 16:30 UTC, bouff commented on test-automation/integration-tests/src/main/java/org/opennms/horizon/it/MonitoringPolicyTestSteps.java
> +    private int policyId;
Code style: Should be placed with the other class members.

2023-07-11 16:30 UTC, bouff commented on test-automation/integration-tests/src/main/java/org/opennms/horizon/it/gqlmodels/MonitorPolicyInputData.java
> +    private List<PolicyRuleData> rules; //replace with List ?
Seems like comment can be removed: `//replace with List ?`

2023-07-11 16:30 UTC, bouff commented on test-automation/integration-tests/src/main/java/org/opennms/horizon/it/gqlmodels/MonitorPolicyInputData.java
> +    private String[] tags;
Is there a reason to prefer `String[]` over `List<String>`?

2023-07-11 16:30 UTC, bouff commented on test-automation/integration-tests/src/main/java/org/opennms/horizon/it/MonitoringPolicyTestSteps.java
> +    @Given("Location {string} is created MP")
There's a lot of duplication: several of these steps are defined in class `InventoryTestSteps`.

Can we re-use the existing steps instead?

2023-07-11 16:30 UTC, bouff commented on test-automation/integration-tests/src/main/java/org/opennms/horizon/it/MonitoringPolicyTestSteps.java
> +        for(JsonElement element : alerts) {
Defining a model class for the response would make this code much simpler - instead of working with `JsonObject` and `JsonArray`.

2023-07-11 16:30 UTC, bouff commented on test-automation/integration-tests/src/main/java/org/opennms/horizon/it/MonitoringPolicyTestSteps.java
> +    private String snmpNodeIp;
Should be moved with the other class members

2023-08-04 15:33 UTC, JohnWang-NMS commented on test-automation/integration-tests/src/main/java/org/opennms/horizon/it/gqlmodels/MonitorPolicyInputData.java
> +    private String[] tags;
> Is there a reason to prefer `String[]` over `List<String>`?

Replaced with List in the check-in.

2023-08-04 15:34 UTC, JohnWang-NMS commented on test-automation/integration-tests/src/main/java/org/opennms/horizon/it/gqlmodels/MonitorPolicyInputData.java
> +    private List<PolicyRuleData> rules; //replace with List ?
Removed.

2023-08-04 15:34 UTC, JohnWang-NMS commented on test-automation/integration-tests/src/main/java/org/opennms/horizon/it/gqlmodels/PolicyRuleData.java
> +    private List<TriggerEventData> triggerEvents; //replace with List ?
Removed.

2023-08-04 16:11 UTC, JohnWang-NMS commented on test-automation/integration-tests/src/main/java/org/opennms/horizon/it/MonitoringPolicyTestSteps.java
> +    public MonitoringPolicyTestSteps(TestsExecutionHelper helper) { this.helper = helper; }
Did the reformat on the file but it does not seem to have effect. I've also have "Enable EditorConfig support" checked in Code Style.

2023-08-04 16:21 UTC, JohnWang-NMS commented on test-automation/integration-tests/src/main/java/org/opennms/horizon/it/MonitoringPolicyTestSteps.java
> +        for(JsonElement element : alerts) {
The flip side of doing so is the codebase might be cluttered with many small model classes.

2023-08-04 16:22 UTC, JohnWang-NMS commented on test-automation/integration-tests/src/main/java/org/opennms/horizon/it/MonitoringPolicyTestSteps.java
> +    private String snmpNodeIp;
Done

2023-08-04 16:32 UTC, bouff commented on test-automation/integration-tests/src/main/java/org/opennms/horizon/it/MonitoringPolicyTestSteps.java
> +        for(JsonElement element : alerts) {
It won't be clutter.  In fact, this promotes re-usability.

2023-08-04 16:41 UTC, JohnWang-NMS commented on test-automation/integration-tests/src/main/java/org/opennms/horizon/it/MonitoringPolicyTestSteps.java
> +    private GenericContainer<?> snmpContainer;
Done

2023-08-04 16:41 UTC, JohnWang-NMS commented on test-automation/integration-tests/src/main/java/org/opennms/horizon/it/MonitoringPolicyTestSteps.java
> +import java.util.*;
Done

2023-08-08 14:58 UTC, JohnWang-NMS commented on test-automation/integration-tests/src/main/resources/org/opennms/horizon/it/monitoring-policy.feature
> +#      | trigger_event id | trigger_event name  | count | overtime | overtime_unit | severity | clear_event |
All the other comment lines have been removed except for this one which will be kept for annotating the data table underneath.

2023-08-09 17:41 UTC, geraldhumphries requested changes
There are some things to be addressed, but I also left a couple of comments to start discussions. Nothing in those comments need to be addressed for this PR.

2023-08-09 17:41 UTC, geraldhumphries commented on test-automation/integration-tests/src/main/resources/org/opennms/horizon/it/monitoring-policy.feature
> +  Scenario Outline: Apply a custom monitoring policy to a node
NOT A REVIEW COMMENT, this is for discussion.

There is one large scenario outline here that does several different things. It is difficult to tell what it is actually trying to test, especially if you are just reading the Gherkin.

We can split it up into separate scenarios:
```
Scenario: Users can create monitoring policies with alert conditions for SNMP traps
Scenario: Alerts are triggered when an SNMP trap alert condition is met
```

This is also doing several other things that could be scenarios, but belong in other feature files:
```
Scenario: Users can create locations
Scenario: Users can download valid Minion certificates
Scenario: Users can create ICMP active discoveries
Scenario: Minions can discover nodes with ICMP
Scenario: Minions can forward SNMP traps from nodes
```

All the steps that set up a location, Minion, node, discovery, etc. should be abstracted into coarse-grained Given steps:
```
Scenario: Users can create monitoring policies with alert conditions for SNMP traps
  Given there are no monitoring policies. <-- This should delete all existing policies
  When the user starts creating a monitoring policy with location "test-location" and tag "test-tag"
  And the user adds an SNMP trap policy rule
  And the user adds the following alert conditions
      | trigger_event_id | trigger_event_name  | count | overtime | overtime_unit | severity | clear_event |
      | 1 | "coldStart" | 1     | 3        | MINUTE        | <severity>    |             |
  When the user saves the monitoring policy
  Then there is a monitoring policy with location "test-location", tag "test-tag", and a "coldStart" SNMP trap condition

Scenario: Alerts are triggered when an SNMP trap alert condition is met
  Given I have a monitoring policy with location "test-location", tag "test-tag", and a "coldStart" SNMP trap condition <-- This should perform the same actions as the `Given` steps in first scenario
  And there is a Minion monitoring a node at location "test-location" with tag "test-tag" <-- This should start the Minion, node, create the location, download the cert, etc.
  When the Minion sends a "coldStart" SNMP trap for the node
  Then an alert should be triggered for the node
```

2023-08-09 17:41 UTC, geraldhumphries commented on test-automation/integration-tests/src/main/resources/org/opennms/horizon/it/monitoring-policy.feature
> +    Then Create a monitoring policy with name "test-monitoring-policy" and tag "<tag>"
This should be split into two steps, a `When` to perform the action and a `Then` to verify the output:

```
When the user saves the monitoring policy with name "test-monitoring-policy" and tag "<tag>"
Then there is a monitoring policy with name "test-monitoring-policy" and tag "<tag>"
```

2023-08-10 03:00 UTC, JohnWang-NMS commented on test-automation/integration-tests/src/main/resources/org/opennms/horizon/it/monitoring-policy.feature
> +    Then Location "test-monitoring-policy-location" does not exist
Agreed but before/after hooks in Cucumber does not take any parameters unless they are defined as constants.

2023-08-10 03:00 UTC, JohnWang-NMS commented on test-automation/integration-tests/src/main/resources/org/opennms/horizon/it/monitoring-policy.feature
> +    Then Wait for at least one minion for the given location reported by inventory with timeout 180000ms
Removed

2023-08-10 03:00 UTC, JohnWang-NMS commented on test-automation/integration-tests/src/main/resources/org/opennms/horizon/it/monitoring-policy.feature
> +    Then The alert has the severity set to "<severity>"
Updated

2023-08-10 03:01 UTC, JohnWang-NMS commented on test-automation/integration-tests/src/main/resources/org/opennms/horizon/it/monitoring-policy.feature
> +    Then Send a trap to Minion with oid "1.3.6.1.6.3.1.1.5.2"
Changed accordingly

2023-08-10 03:01 UTC, JohnWang-NMS commented on test-automation/integration-tests/src/main/resources/org/opennms/horizon/it/monitoring-policy.feature
> +    When SNMP node "mp_snmp_node" is started in the network of minion "test-monitoring-policy-system01".
And is now used.

2023-08-10 03:08 UTC, JohnWang-NMS commented on test-automation/integration-tests/src/main/resources/org/opennms/horizon/it/monitoring-policy.feature
> +    Then Location "test-monitoring-policy-location" do exist.
Updated accordingly

2023-08-10 03:08 UTC, JohnWang-NMS commented on test-automation/integration-tests/src/main/resources/org/opennms/horizon/it/monitoring-policy.feature
> +    Given No Minion running with location "test-monitoring-policy-location".
Periods have been removed.

2023-08-10 03:08 UTC, JohnWang-NMS commented on test-automation/integration-tests/src/main/resources/org/opennms/horizon/it/monitoring-policy.feature
> +    Then Create a monitoring policy with name "test-monitoring-policy" and tag "<tag>"
Done

2023-08-10 03:09 UTC, JohnWang-NMS commented on test-automation/integration-tests/src/main/resources/org/opennms/horizon/it/monitoring-policy.feature
> +#      | trigger_event id | trigger_event name  | count | overtime | overtime_unit | severity | clear_event |
Done

2023-08-11 13:59 UTC, geraldhumphries commented on test-automation/integration-tests/src/main/resources/org/opennms/horizon/it/monitoring-policy.feature
> +    Then Location "test-monitoring-policy-location" does not exist
I guess it needs the parameters because all of the config is defined in `Background`? We can circle back on this later when that gets refactored.

2023-08-11 14:52 UTC, geraldhumphries approved these changes
Great work on this, I've opened https://opennms.atlassian.net/browse/LOK-1943 and https://opennms.atlassian.net/browse/LOK-1944 for the issues I mentioned.

2023-08-11 15:03 UTC, geraldhumphries commented on test-automation/integration-tests/src/main/resources/org/opennms/horizon/it/monitoring-policy.feature
> +  Scenario Outline: Apply a custom monitoring policy to a node
Created this issue: https://opennms.atlassian.net/browse/LOK-1944

2023-08-11 15:21 UTC, merged