HS-1642: Add support for cidr notation
OpenNMS-Cloud/lokahi pull request #1333
Opened 2023-07-19 20:59 UTC by cgorantla

## Description
Support Ip range cidr notation

## Jira link(s)
- https://opennms.atlassian.net/browse/HS-1642

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2023-07-19 23:05 UTC, freddy61025 approved these changes
LGTM, It will be better to have test cover it.

2023-07-20 15:53 UTC, vserrago requested changes

2023-07-20 15:53 UTC, vserrago commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/taskset/ScannerTaskSetService.java
> +                    ipRangeBuilder.setEnd(highAddress);
Nit: This could be more succinctly specified:

```suggestion
                    var ipRangeBuilder = IpRange.newBuilder()
                        .setBegin(info.getLowAddress())
                        .setEnd(info.getHighAddress());
```

2023-07-20 15:53 UTC, vserrago commented on inventory/main/src/test/java/org/opennms/horizon/inventory/service/taskset/ScannerTaskSetServiceTest.java
> +    }
This test would benefit from being parameterized

2023-07-20 18:28 UTC, cgorantla commented on inventory/main/src/test/java/org/opennms/horizon/inventory/service/taskset/ScannerTaskSetServiceTest.java
> +    }
Even with parameterized, I need to use some logic to get expected results.
Is there a way to specify expected results with Parameterized test otherwise I need logic to derive results which defeats the purpose of test

2023-07-20 18:48 UTC, vserrago commented on inventory/main/src/test/java/org/opennms/horizon/inventory/service/taskset/ScannerTaskSetServiceTest.java
> +    }
There is, and there are a few ways you could do it using different value sources. I think this test can be written with a [@CsvSource](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-sources-CsvSource), which would allow you to specify something similar to the following:

```suggestion
    @CsvSource({
      "'192.168.4.0/24, 192.168.2.2, 192.168.3.1-192.168.3.254', 192.168.4.0, 192.168.4.255",
      "'192.168.4.0/24, 192.168.2.2, 192.168.3.1-192.168.3.254', 192.168.3.1, 192.168.3.254",
      // ..etc
    })
    @ParameterizedTest
    void testIpAddressParsing(List<String> cidrs, String expectedBegin, String expectedEnd) throws InvalidProtocolBufferException {
        var optional = service.createDiscoveryTask(cidrs,locationId, 1);
        // ...
    }
```

Of if you want to test 1 cidr at a time,

```suggestion
    @CsvSource({
      "192.168.4.0/24, 192.168.4.0, 192.168.4.255",
      "192.168.3.1-192.168.3.254, 192.168.3.1, 192.168.3.254",
      // ..etc
    })
    @ParameterizedTest
    void testIpAddressParsing(String cidr, String expectedBegin, String expectedEnd) throws InvalidProtocolBufferException {
        var optional = service.createDiscoveryTask(List.of(cidr),locationId, 1);
        // ...
    }
```

If you have more questions about it feel free to reach out

2023-07-20 19:46 UTC, cgorantla commented on inventory/main/src/test/java/org/opennms/horizon/inventory/service/taskset/ScannerTaskSetServiceTest.java
> +    }
Awesome. Done!

2023-07-20 19:47 UTC, vserrago approved these changes

2023-07-21 14:02 UTC, merged