HS-1586: Start metrics collection per network interface
OpenNMS-Cloud/lokahi pull request #1334
Opened 2023-07-20 13:56 UTC by freddy61025

## Description
Changes:

- Add Azure vm OS & location info handling 
- Add azure_interface table
- Link private IP & public IP with related resourceId
- Add timespan to reduce query cost
- Add Public IP metrics
- Add Network Interface metrics
- Improve Azure Error Message handling. 

## Jira link(s)
- https://opennms.atlassian.net/browse/HS-1586

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2023-07-25 16:25 UTC, mikewrosey commented on ui/src/components/NodeStatus/IPInterfacesTable.vue
> +            {{ console.log( nodeStatusStore.node.azureInterfaces.get(ipInterface.azureInterfaceId)?.publicIpAddress ) }}
console.log left from testing

2023-07-26 11:50 UTC, scthompsonopen approved these changes
Approving because all my comments are nits or refactor suggestions for the future. 

Just a note that I have only reviewed the FE sections, I am not qualified to review/approve the BE portions (which is the majority of this PR).

I have an overall piece of minor feedback in that this PR is pretty big, and future large PRs might benefit from being broken down into smaller chunks. Not suggesting merging half-complete code into develop, but more working with in an integration branch so we can see the large feature come together in smaller chunks.

Overall looks good to me!

2023-07-26 11:50 UTC, scthompsonopen commented on ui/src/components/NodeStatus/IPInterfacesTable.vue
> +            <th scope="col" v-if="nodeStatusStore.isAzure">Private IP ID</th>
Now that we've added so many columns depending on this `isAzure` variable, I wonder if there's a way to revisit this design instead of having so many repeated v-if statements. Maybe an Azure and non-azure table.

This is a general though for the future of this table, versus direct feedback on this ticket. I don't want to hold up this big PR on refactors.

2023-07-26 11:50 UTC, scthompsonopen commented on ui/src/components/NodeStatus/IPInterfacesTable.vue
> +            <td v-if="nodeStatusStore.isAzure">{{ nodeStatusStore.node.azureInterfaces.get(ipInterface.azureInterfaceId)?.privateIpId }}</td>
Similar comment here to above. Now that we've grown this table so much, I wonder if it's worth revisiting the design for a refactor to either split the table in two, rebuild it to work off generic props so it's not quite so specific and more re-usable, or maybe something else entirely. Just thoughts for the future on how we can refactor this to be a bit neater, nothing to be done now.

2023-07-26 17:22 UTC, mikewrosey commented on ui/src/containers/Graphs.vue
> +    <LineGraph :graph="azureNodeBytesInOut" type="bytes" v-if="isAzure"/>
Agree with all the refactor comments. And the Graphs and Node Status pages were built entirely without designs and as far as I know will basically be redone from scratch after EAR. That will be a good time to ensure these separations.

2023-07-26 17:23 UTC, mikewrosey approved these changes

2023-07-26 17:29 UTC, freddy61025 commented on ui/src/containers/Graphs.vue
> +    <LineGraph :graph="azureNodeBytesInOut" type="bytes" v-if="isAzure"/>
https://opennms.atlassian.net/browse/HS-1871 task created as reminder.

2023-07-26 17:29 UTC, freddy61025 commented on ui/src/components/NodeStatus/IPInterfacesTable.vue
> +            <th scope="col" v-if="nodeStatusStore.isAzure">Private IP ID</th>
https://opennms.atlassian.net/browse/HS-1871 task created as reminder.

2023-07-26 17:30 UTC, freddy61025 commented on ui/src/components/NodeStatus/IPInterfacesTable.vue
> +            <td v-if="nodeStatusStore.isAzure">{{ nodeStatusStore.node.azureInterfaces.get(ipInterface.azureInterfaceId)?.privateIpId }}</td>
https://opennms.atlassian.net/browse/HS-1871 task created as reminder.

2023-07-27 14:19 UTC, geraldhumphries approved these changes

2023-07-27 19:42 UTC, vserrago requested changes

2023-07-27 19:42 UTC, vserrago commented on shared-lib/azure/azure-http/src/main/java/org/opennms/horizon/shared/azure/http/AzureHttpClient.java
> +            throw new IllegalArgumentException();
Unlikely to happen but we should have a message in the exception with the parameter to enhance traceability

```suggestion
            throw new IllegalArgumentException("Invalid value: " + metricName);
```

2023-07-27 19:42 UTC, vserrago commented on shared-lib/azure/azure-http/src/main/java/org/opennms/horizon/shared/azure/http/AzureHttpClient.java
> +            log.info("============================");
I don't think we want to log all of this. Logging the request might expose the client secret/token.

```suggestion
            log.info("Response statusCode: {}, body: {}", httpResponse.statusCode(), httpBody);
```

2023-07-27 19:42 UTC, vserrago commented on shared-lib/azure/azure-http/src/main/java/org/opennms/horizon/shared/azure/http/AzureHttpClient.java
> +        log.debug("========");
I think even at the debug level we don't want to log sensitive data from the request.

```suggestion
```

2023-07-27 19:42 UTC, vserrago commented on shared-lib/azure/azure-http/src/main/java/org/opennms/horizon/shared/azure/http/AzureHttpClient.java
> +                    log.error("Request: {}, HTTP_UNAUTHORIZED: {}", request, ex.getMessage(), ex);
Probably should not log the whole request here

2023-07-27 19:52 UTC, freddy61025 commented on minion/plugins/azure-plugin/src/main/java/org/opennms/horizon/minion/azure/AzureCollector.java
> +    // Supported intervals: PT1M,PT5M,PT15M,PT30M,PT1H,PT6H,PT12H,P1D
that list usually only return when you input something wrong during call.

2023-07-27 20:26 UTC, vserrago approved these changes

2023-07-27 20:45 UTC, merged