LOK-1989: Discovery Updates
OpenNMS-Cloud/lokahi pull request #1444
Opened 2023-09-06 19:50 UTC by scthompsonopen

## Description
Our latest update to the discovery page. A bit of a visual and code overhaul. A big PR.

Better PR copy to follow.

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-1989

## Flagged for review
This one really needs to be tested manually. There's bound to be something I've missed.

## Checklist
* [X] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [X] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2023-09-07 19:53 UTC, Bonrob2 commented on ui/src/components/Discovery/discovery.text.ts
> +    empty: 'No discoveries performed'
```suggestion
    empty: 'No discoveries performed.'
```

2023-09-07 20:00 UTC, Bonrob2 requested changes
Very minor changes noted in the files.
Question about the connect information for Azure. Is it possible to have different text there, or since it's a template do we need to keep the text? It's the only one that doesn't have IP address ranges, port, or community string. 
I had suggested the following in Figma: "Set connection information like Azure client and subscription IDs."

2023-09-08 11:02 UTC, scthompsonopen commented
> Set connection information like Azure client and subscription IDs.

I was able to make this change, I hadn't noticed the copy changed on that one form. I just check to see what type the user selected and modify the copy based on that state now:

## Azure Form
![image](https://github.com/OpenNMS-Cloud/lokahi/assets/86311553/0c24b7ed-2fe0-48fc-aabd-d441acfb2be7)

## ICMP Form
![image](https://github.com/OpenNMS-Cloud/lokahi/assets/86311553/85b67289-46fb-41fa-a08e-7a3089f11dee)

## Passive Form
![image](https://github.com/OpenNMS-Cloud/lokahi/assets/86311553/00143a87-a109-4c74-86f5-ebc78962ae96)

2023-09-12 13:56 UTC, mikewrosey approved these changes

2023-09-12 14:10 UTC, Bonrob2 approved these changes
LGTM! Thanks!

2023-09-12 14:15 UTC, merged