LOK-1880: convert flow query bytes to bit per second
OpenNMS-Cloud/lokahi pull request #1453
Opened 2023-09-12 12:34 UTC by freddy61025

## Description

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-1880

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2023-09-12 14:04 UTC, vserrago requested changes

2023-09-12 14:04 UTC, vserrago commented on rest-server/src/main/java/org/opennms/horizon/server/service/flows/UnitConverter.java
> +     * convert a grouped points value from byte > bps, beware it will directly modify value of flowingPoint
As mentioned above, this method should convert without side-effect.

2023-09-12 14:04 UTC, vserrago commented on rest-server/src/test/java/org/opennms/horizon/server/service/flows/UnitConverterTest.java
> +        Collections.shuffle(pointList);
I think it would be better to have a pre-defined, asorted order instead of randomly shuffling during test execution.

```suggestion
        pointList.add(getFlowingPoint(startTime + 100, 200, LABEL, EGRESS));
        pointList.add(getFlowingPoint(startTime, 100, LABEL, INGRESS));
        pointList.add(getFlowingPoint(startTime + 300, 400, LABEL, INGRESS));
        pointList.add(getFlowingPoint(startTime + 100, 200, LABEL, INGRESS));

        pointList.add(getFlowingPoint(startTime, 100, LABEL + "1", 
        pointList.add(getFlowingPoint(startTime + 200, 300, LABEL, INGRESS));
        pointList.add(getFlowingPoint(startTime, 100, LABEL, EGRESS));
```

2023-09-13 14:02 UTC, freddy61025 commented on rest-server/src/main/java/org/opennms/horizon/server/service/flows/UnitConverter.java
> +     * It will split data by label & direction and convert byte > bps, beware it will directly modify value of flowingPoint
replace with return void to avoid misunderstanding.

2023-09-13 14:02 UTC, freddy61025 commented on rest-server/src/main/java/org/opennms/horizon/server/service/flows/UnitConverter.java
> +     * convert a grouped points value from byte > bps, beware it will directly modify value of flowingPoint
replace with return void to avoid misunderstanding.

2023-09-13 14:03 UTC, freddy61025 commented on rest-server/src/test/java/org/opennms/horizon/server/service/flows/UnitConverterTest.java
> +        Collections.shuffle(pointList);
The main idea is to maintain the test data order for easier maintenance. replace with add with index.

2023-09-13 20:10 UTC, vserrago approved these changes

2023-09-13 20:20 UTC, merged