LOK-1834: Update default monitoring policy
OpenNMS-Cloud/lokahi pull request #1458
Opened 2023-09-13 14:08 UTC by cgorantla

## Description

Move default monitoring policy from code to liquibase.
Add `Device Unreachable` alert condition/definition.

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-1834 

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2023-09-14 13:33 UTC, vserrago requested changes

2023-09-14 13:33 UTC, vserrago commented on alert/src/main/resources/db/changelog/hs-0.1.0/tables/rename_trigger_event_to_alert_condition.xml
> +
Why remove the default value & non-nullability?, Also, this change should go into a different file. This one is named `rename_trigger_event_to_alert_condition.xml`, which doesn't describe these changes accurately.

2023-09-15 14:40 UTC, cgorantla commented on alert/src/main/resources/db/changelog/hs-0.1.0/tables/rename_trigger_event_to_alert_condition.xml
> +
I don't understand the concept of overtime clearly but looking at the code, it seems completely optional, that's the reason I moved it to non-nullable. Also default value of `minute` for `over_time_unit` is throwing error when it is converting to `OverTimeUnit` enum.

2023-09-15 14:43 UTC, cgorantla commented on alert/src/main/resources/db/changelog/hs-0.1.0/tables/rename_trigger_event_to_alert_condition.xml
> +
The file was chosen because it is one related to alert condition.  Don't want to create separate file for a minor update.

2023-09-18 13:14 UTC, vserrago requested changes

2023-09-19 19:50 UTC, merged