LOK-1930: Minion cleanup
OpenNMS-Cloud/lokahi pull request #1465
Opened 2023-09-18 13:49 UTC by cgorantla

## Description
1. Reconnect after Sink Stream errors out
2. Add a workaround to send trap config  to avoid timeout errors
3. Shutdown Minion properly when non-recoverable error happens
4. Update logs on Minion grpc client ( don't show exceptions unless debug is set)
5. Update logs in plugins ( don't show exceptions unless debug is set)

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-XXXX

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2023-09-18 19:54 UTC, freddy61025 approved these changes
LGTM

2023-09-18 20:40 UTC, bouff commented on minion/plugins/snmp-plugin/src/main/java/org/opennms/horizon/minion/snmp/SnmpMonitor.java
> +            if (LOG.isDebugEnabled()) {
Nit: is the conditional needed in this case (if debug then write a debug message)?

There isn't any intense computation for the log message itself, so I'd recommend against having these..

2023-09-18 20:40 UTC, bouff commented on minion/minion-grpc/grpc-client/src/test/java/org/opennms/horizon/minion/grpc/channel/SSLChannelFactoryTest.java
> +
Since we are swallowing the exception here... and this seems to be unexpected - why don't we have the test fail if an exception is thrown on create?

2023-09-18 20:40 UTC, bouff commented on minion/minion-grpc/grpc-client/src/main/java/org/opennms/horizon/minion/grpc/MinionGrpcClient.java
> +                    LOG.error("Error on cleanup of existing rpc stream", exc);
Nit: I find it confusing that the lower level `DEBUG` will result in showing/hiding a (higher level) `ERROR` log.

Why isn't the level kept the same?  (E.g. `DEBUG` is on, one will see `DEBUG` logs)

2023-09-18 20:43 UTC, bouff commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/TrapConfigService.java
> +        // Keep sending Trap config every 15 mins.
Please raise a tech-debt task (and include the Jira ID here, in the comment) with the context for this approach.

2023-09-19 19:51 UTC, cgorantla commented on minion/minion-grpc/grpc-client/src/test/java/org/opennms/horizon/minion/grpc/channel/SSLChannelFactoryTest.java
> +
Updated test.

2023-09-19 19:53 UTC, cgorantla commented on minion/minion-grpc/grpc-client/src/main/java/org/opennms/horizon/minion/grpc/MinionGrpcClient.java
> +                    LOG.error("Error on cleanup of existing rpc stream", exc);
I kept this to ERROR to make it easier to search and visibility purpose on the console. We can go either way.

2023-09-19 20:09 UTC, vserrago requested changes

2023-09-19 20:09 UTC, vserrago commented on minion/minion-grpc/grpc-client/src/main/java/org/opennms/horizon/minion/grpc/MinionGrpcClient.java
> +                    LOG.error("Error on cleanup of existing rpc stream", exc);
I also don't think it's a good idea to gate higher severity log statements behind lower severity logs being enabled. As mentioned, the `logger#is<level>Enabled()` methods are for preventing computationally-heavy log statements from getting invoked. To have it gate higher-severity messages would not be intuitive to someone like an operator unless they were looking directly at this source file.

I think it would be better to log them at the debug level, or alternatively, at the warn level since they are an error we can otherwise suppress/recover from.

2023-09-19 21:03 UTC, bouff approved these changes

2023-09-20 13:29 UTC, vserrago approved these changes

2023-09-20 13:58 UTC, merged