Fix GRPC API Validation Flaws
OpenNMS-Cloud/lokahi pull request #1501
Opened 2023-10-10 22:12 UTC by freddy61025

## Description

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-1925

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2023-10-19 18:57 UTC, bouff reviewed
Overall LGTM.  Only a couple minor nits.

2023-10-19 18:57 UTC, bouff commented on inventory/main/src/test/java/org/opennms/horizon/inventory/grpc/MonitoringSystemGrpcServiceTest.java
> +    void testGgtMonitoringSystemByQuery(){
Nit: typo in method name here and line 126

2023-10-19 18:57 UTC, bouff commented on events/grpc/src/test/java/org/opennms/horizon/events/grpc/service/AbstractGrpcUnitTest.java
> +    protected final String tenantId = "test-tenant";
Nit: could be constants (here and line below)

2023-10-19 18:57 UTC, bouff commented on minion-certificate-manager/main/src/main/java/org/opennms/horizon/minioncertmanager/grpc/MinionCertificateManagerImpl.java
> +    boolean isLocationExist(long locationId, String tenantId) {
Nit: can be private?

2023-10-19 18:57 UTC, bouff commented on inventory/main/src/test/java/org/opennms/horizon/inventory/service/TagServiceTest.java
> +
Nit: can remove newline here

2023-10-20 18:15 UTC, vserrago requested changes
Looks good overall, but there are a few items to address. Any nits are optional.

2023-10-20 18:15 UTC, vserrago commented on inventory/main/src/test/java/org/opennms/horizon/inventory/component/AlertClientTest.java
> +    public final static GrpcCleanupRule grpcCleanUp = new GrpcCleanupRule();
As mentioned previously in a previous location, this rule is mis-specified due to using Junit5 annotations and a static field.

2023-10-20 18:15 UTC, vserrago commented on minion-certificate-manager/main/src/main/java/org/opennms/horizon/minioncertmanager/grpc/MinionCertificateManagerImpl.java
> +    MinionCertificateManagerImpl(File certificate, File key, PKCS12Generator pkcs8Generator, SerialNumberRepository serialNumberRepository, InventoryClient inventoryClient) throws IOException, Interr
Nit: Line is excessively long and would benefit from being broken into multiple lines.

```suggestion
    MinionCertificateManagerImpl(
        File certificate,
        File key,
        PKCS12Generator pkcs8Generator,
        SerialNumberRepository serialNumberRepository,
        InventoryClient inventoryClient
    ) throws IOException, InterruptedException {
```

2023-10-20 18:15 UTC, vserrago commented on minion-certificate-manager/main/src/main/java/org/opennms/horizon/minioncertmanager/grpc/MinionCertificateManagerImpl.java
> +        @Value("${manager.mtls.privateKey}") File privateKey, @Autowired SerialNumberRepository serialNumberRepository, @Autowired InventoryClient inventoryClient) throws IOException, InterruptedExce
Nit: Line is excessively long and would benefit from being broken into multiple lines.

```suggestion
        @Value("${manager.mtls.privateKey}") File privateKey,
        @Autowired SerialNumberRepository serialNumberRepository,
        @Autowired InventoryClient inventoryClient
    ) throws IOException, InterruptedException {
```

2023-10-23 13:58 UTC, freddy61025 commented on minion-certificate-manager/main/src/main/java/org/opennms/horizon/minioncertmanager/grpc/MinionCertificateManagerImpl.java
> +        @Value("${manager.mtls.privateKey}") File privateKey, @Autowired SerialNumberRepository serialNumberRepository, @Autowired InventoryClient inventoryClient) throws IOException, InterruptedExce
done

2023-10-23 13:58 UTC, freddy61025 commented on minion-certificate-manager/main/src/main/java/org/opennms/horizon/minioncertmanager/grpc/MinionCertificateManagerImpl.java
> +    MinionCertificateManagerImpl(File certificate, File key, PKCS12Generator pkcs8Generator, SerialNumberRepository serialNumberRepository, InventoryClient inventoryClient) throws IOException, Interr
done

2023-10-23 13:58 UTC, freddy61025 commented on inventory/main/src/test/java/org/opennms/horizon/inventory/component/AlertClientTest.java
> +    public final static GrpcCleanupRule grpcCleanUp = new GrpcCleanupRule();
done

2023-10-23 13:59 UTC, freddy61025 commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/discovery/active/AzureActiveDiscoveryService.java
> +        }
done

2023-10-23 13:59 UTC, freddy61025 commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/TagService.java
> +    private boolean isPolicyExist(long policyId, String tenantId) {
done

2023-10-23 13:59 UTC, freddy61025 commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/MonitoringSystemGrpcService.java
>          responseObserver.onCompleted();
nice catch

2023-10-23 14:00 UTC, freddy61025 commented on events/grpc/src/test/java/org/opennms/horizon/events/grpc/service/AbstractGrpcUnitTest.java
> +    protected TenantLookup tenantLookup = new GrpcTenantLookupImpl();
done

2023-10-23 14:00 UTC, freddy61025 commented on events/grpc/src/test/java/org/opennms/horizon/events/grpc/client/InventoryClientTest.java
> +    public static final GrpcCleanupRule grpcCleanUp = new GrpcCleanupRule();
done

2023-10-23 14:00 UTC, freddy61025 commented on inventory/main/src/test/java/org/opennms/horizon/inventory/service/TagServiceTest.java
> +
done

2023-10-23 14:00 UTC, freddy61025 commented on minion-certificate-manager/main/src/main/java/org/opennms/horizon/minioncertmanager/grpc/MinionCertificateManagerImpl.java
> +    boolean isLocationExist(long locationId, String tenantId) {
done

2023-10-23 14:00 UTC, freddy61025 commented on events/grpc/src/test/java/org/opennms/horizon/events/grpc/service/AbstractGrpcUnitTest.java
> +    protected final String tenantId = "test-tenant";
done

2023-10-23 14:00 UTC, freddy61025 commented on inventory/main/src/test/java/org/opennms/horizon/inventory/grpc/MonitoringSystemGrpcServiceTest.java
> +    void testGgtMonitoringSystemByQuery(){
done

2023-10-23 14:45 UTC, vserrago approved these changes

2023-10-23 14:55 UTC, vserrago approved these changes

2023-10-23 15:41 UTC, merged