LOK-2055: ignore enrichment if ip lookup fail
OpenNMS-Cloud/lokahi pull request #1536
Opened 2023-10-31 04:18 UTC by freddy61025

## Description

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2055
- 
## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2023-10-31 14:24 UTC, cgorantla requested changes

2023-10-31 14:24 UTC, cgorantla commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/IpInterfaceService.java
> +                modelRepo.findByIpAddressAndLocationIdAndTenantId(ipInterface.getIpAddress(), node.getMonitoringLocationId(), tenantId)
Note that this is also used in update ( scan can run multiple times).  Also throwing exception will prevent adding other interfaces.

2023-11-01 13:54 UTC, freddy61025 commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/IpInterfaceService.java
> +                modelRepo.findByIpAddressAndLocationIdAndTenantId(ipInterface.getIpAddress(), node.getMonitoringLocationId(), tenantId)
as per discussion, replace duplication checking by make sure findByIpAddressAndLocationIdAndTenantId only return single record. Priority return snmpPrimary first then first record.

2023-11-02 19:25 UTC, vserrago approved these changes

2023-11-02 21:18 UTC, cgorantla approved these changes
LGTM!

2023-11-02 23:01 UTC, merged