LOK-2207: Add support for pagination and sorting
OpenNMS-Cloud/lokahi pull request #1567
Opened 2023-11-20 17:55 UTC by cgorantla

## Description
Add support for pagination and sorting

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2207

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2023-11-20 19:59 UTC, cgorantla commented
Moved to draft since this can't be merged until we update graphql query in UI

2023-11-22 16:51 UTC, mikewrosey approved these changes

2023-11-22 18:14 UTC, vserrago requested changes

2023-11-22 18:14 UTC, vserrago commented on rest-server/src/main/java/org/opennms/horizon/server/service/GrpcNodeService.java
> +            return new TopNResponse(csvData.toString().getBytes(StandardCharsets.UTF_8), downloadFormat);
I feel like it may be worthwhile to use a CSV library here instead of a `StringBuilder`, to handle the rare edge cases that come with escaping special characters etc. It looks like we already use `org.apache.commons:commons-csv` elsewhere in Lokahi, so maybe we can use that library here too?

2023-11-22 22:07 UTC, vserrago approved these changes

2023-11-27 21:05 UTC, merged