LOK-1975: BE: Node Alias
OpenNMS-Cloud/lokahi pull request #1582
Opened 2023-11-27 21:36 UTC by bouff

## Description
Adds an operation to set the "node alias".  This new field is optional and stores a user-provided "human friendly" name for a node.  For instance, "192.168.1.1" can be given the name "router".

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-1975
- https://opennms.atlassian.net/browse/LOK-1976

## Flagged for review
- I'm not very familiar with the FE side of things.  I made some changes - such that the node alias can be seen in the response for listing nodes. 

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

## Manual Testing

This shows a manual test of the GraphQL mutation for the node alias:
![Screenshot 2023-11-27 at 4 27 45 PM](https://github.com/OpenNMS-Cloud/lokahi/assets/39974723/6c086db4-2dea-40de-9fb9-6ff6bfd7ce6d)

Observe the updated node alias in the response:
![Screenshot 2023-11-27 at 4 28 21 PM](https://github.com/OpenNMS-Cloud/lokahi/assets/39974723/c1447bef-d58d-4eae-928b-bd70a353bc25)

2023-11-27 21:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1582) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1582) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenNMS-Cloud/lokahi?pullRequest=1582) it.</sub>

2023-11-28 14:54 UTC, vserrago requested changes

2023-11-28 14:54 UTC, vserrago commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/NodeGrpcService.java
> +            var nodeId = nodeService.updateNode(request, tenantId);
Nit: I tend to prefer the explicit type if the assigned type isn't obvious from the statement. In this case I was not sure if it's a `Long` or a `String`

```suggestion
            Long nodeId = nodeService.updateNode(request, tenantId);
```

2023-11-28 14:54 UTC, vserrago commented on inventory/main/src/test/java/org/opennms/horizon/inventory/service/NodeServiceTest.java
> +        assertEquals("Node with ID " + otherNodeUpdateRequest.getId() + " not found", exception.getMessage());
This should be a separate unit test

2023-11-28 14:54 UTC, vserrago commented on rest-server/src/test/resources/test/data/mutation-update-node.json
> +}
It doesn't look like this file is referenced in any tests. If the intent was to have it tested in `org.opennms.horizon.server.GraphQLQueryValidationTest`, then it needs to be added to `org.opennms.horizon.server.GraphQLQueryValidationTest#allowedRequests`. Otherwise it can be deleted. Since it's not a complex query it's not a big deal if we don't test it.

2023-11-28 16:50 UTC, bouff commented on rest-server/src/test/resources/test/data/mutation-update-node.json
> +}
Sounds good - might as well keep it as a reference.

2023-11-28 17:16 UTC, cgorantla reviewed
LGTM!

I think we can update UI to show Node with alias if alias is available.

2023-11-28 17:20 UTC, vserrago approved these changes

2023-11-28 17:26 UTC, bouff commented
> LGTM!
> 
> I think we can update UI to show Node with alias if alias is available.

Yup, this will be done in LOK-1977

2023-11-28 17:27 UTC, merged