Added fix for lok-2221
OpenNMS-Cloud/lokahi pull request #1615
Opened 2024-02-02 09:45 UTC by MusaidAli

## Description

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-XXXX

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-02-02 10:16 UTC, smunir-onms commented on inventory/main/src/main/java/org/opennms/horizon/inventory/repository/NodeRepository.java
> +    long countDistinctNodes();
I think, it should filter by tenantID.

@cgorantla , please correct me if I am wrong.

2024-02-02 14:28 UTC, cgorantla requested changes

2024-02-02 14:28 UTC, cgorantla commented on rest-server/src/main/java/org/opennms/horizon/server/service/GrpcNodeService.java
> +    public Mono<Long> countNodeRows(@GraphQLEnvironment ResolutionEnvironment env) {
There is an existing GraphQL API for this.
Please use that https://github.com/OpenNMS-Cloud/lokahi/pull/1615/files#diff-c3aa9df5bed1ef1085d4017c23e43a65ff52de5be3e873ee8f1794e821eee498L154

2024-02-02 14:28 UTC, cgorantla commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/NodeGrpcService.java
> +        try {
Need to add tenant lookup for every service.

String tenantId = tenantLookup.lookupTenantId(Context.current()).orElseThrow();

`nodeCount` would be better name for the service.

2024-02-02 14:28 UTC, cgorantla commented on inventory/main/src/main/java/org/opennms/horizon/inventory/repository/NodeRepository.java
> +    long countDistinctNodes();
Yes, we need to get num of nodes for the given tenant

2024-02-05 03:42 UTC, cgorantla reviewed
Looks good. few more suggestions

2024-02-05 03:42 UTC, cgorantla commented on shared-lib/inventory/src/main/proto/nodeService.proto
> +  rpc getNodesCount(google.protobuf.Empty) returns (google.protobuf.Int64Value) {};
nit: 
```suggestion
  rpc getNodeCount(google.protobuf.Empty) returns (google.protobuf.Int64Value) {};
```

2024-02-05 03:42 UTC, cgorantla commented on inventory/main/src/main/java/org/opennms/horizon/inventory/repository/NodeRepository.java
> +    @Query("SELECT COUNT(DISTINCT n.id) FROM Node n WHERE n.tenantId = :tenantId ")
you can omit DISTINCT as  id is primary key here.

2024-02-05 03:42 UTC, cgorantla commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/NodeGrpcService.java
> +    @Override
Please add a step to validate this in CucumberIT, probably [here](https://github.com/OpenNMS-Cloud/lokahi/blob/460d08408d815314ea212f775df0bcffb27c23c1/inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/NodeStepDefinitions.java#L114) you can replace with  this new grpc method.

2024-02-05 10:27 UTC, smunir-onms commented
Thank you so much @cgorantla for the kind suggestions, it's very helpful for future commits.

2024-02-05 15:03 UTC, cgorantla approved these changes
LGTM!

2024-02-07 18:36 UTC, cgorantla reviewed
Please merge develop and handle conflicts

2024-02-07 18:36 UTC, cgorantla commented on inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/NodeStepDefinitions.java
> +        Assert.assertEquals(nodeCount, nodeCount);
check against actual node count

2024-02-14 16:08 UTC, closed without merging