https://opennms.atlassian.net/browse/LOK-2229
OpenNMS-Cloud/lokahi pull request #1622
Opened 2024-02-08 12:00 UTC by MusaidAli

## Description

## Jira link(s)
https://opennms.atlassian.net/browse/LOK-2229

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-02-08 14:51 UTC, cgorantla requested changes
Please add a test case in Alerts component.

2024-02-08 14:51 UTC, cgorantla commented on alert/src/main/java/org/opennms/horizon/alertservice/db/entity/Alert.java
> +import jakarta.persistence.JoinColumn;
remove unused import

2024-02-08 14:51 UTC, cgorantla commented on alert/src/main/java/org/opennms/horizon/alertservice/db/entity/Alert.java
> +    @Column(name = "node_id")
we should add this to alarm table with liquibase, see resources

2024-02-08 14:51 UTC, cgorantla commented on alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
> +           List<Alert> protoList = getEnrichAlertProto2nd(alerts);
you can simplify this with Streams: 
alerts.stream()
                      .map(alert -> Alert.newBuilder(alertMapper.toProto(alert)).build())
                      .collect(Collectors.toList());

or update method name `maptoAlertProtoList`

2024-02-08 14:51 UTC, cgorantla commented on alert/src/main/java/org/opennms/horizon/alertservice/service/AlertEventProcessor.java
> +        if (event.getNodeId() > 0) {
duplicate code, just need to add `alert.setNodeId(event.getNodeId());`

2024-02-08 14:51 UTC, cgorantla commented on rest-server/src/main/java/org/opennms/horizon/server/service/GrpcAlertService.java
> +    public Mono<ListAlertResponse> getRecentAlertsByNode(@GraphQLArgument(name = "nodeId") long nodeId,
let's take care of pagination in another PR

2024-02-08 14:51 UTC, cgorantla commented on shared-lib/alert/src/main/proto/alerts.proto
> +  rpc getRecentAlertsByNode(AlertRequestByNode)  returns (ListAlertsResponse) {};
we can probably omit `Recent` in the name

2024-02-12 14:48 UTC, cgorantla reviewed
Please add a test case in alert.feature

2024-02-12 14:48 UTC, cgorantla commented on rest-server/src/main/java/org/opennms/horizon/server/service/GrpcAlertService.java
> +    @SuppressWarnings("squid:S107")
do we need this `@SuppressWarnings("squid:S107")`

2024-02-12 14:48 UTC, cgorantla commented on alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
> +        getFilterOptions(request, timeRange, severities, filterNodeIds);
i think there is no requirement for filters here.  we can remove that

2024-02-12 14:59 UTC, MusaidAli commented on rest-server/src/main/java/org/opennms/horizon/server/service/GrpcAlertService.java
> +    @SuppressWarnings("squid:S107")
ok ,i will remove it.

2024-02-12 15:00 UTC, MusaidAli commented on alert/src/main/java/org/opennms/horizon/alertservice/service/AlertEventProcessor.java
> +        if (event.getNodeId() > 0) {
hi , this code was already there if(even.getNodeId()>0)

2024-02-13 13:35 UTC, cgorantla commented on alert/src/main/resources/db/changelog/hs-0.1.0/tables/alert.xml
> +            <column name="node_id" type="bigint"/>
we can't directly add  node_id in the table, please add new changeSet

2024-02-13 18:40 UTC, cgorantla commented on alert/src/test/java/org/opennms/horizon/alertservice/stepdefs/AlertTestSteps.java
> +            .getAlertsByNode(requestBuilder.build());
what are you validating here ?

2024-02-23 12:20 UTC, closed without merging