LOK-2235:Added feature.
OpenNMS-Cloud/lokahi pull request #1655
Opened 2024-02-21 18:27 UTC by MusaidAli

## Description
BE: BFF: Node: SearchSnmpInterfaces

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2235

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-02-21 20:06 UTC, cgorantla requested changes
Search code looks fine, needs some updates on tests.

2024-02-21 20:06 UTC, cgorantla commented on inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/SnmpInterfaceStepDefinitions.java
> +    @Given("a new snmp_interface with name {string}, desc {string} ,alias {string} , physical address {string} and node label {string} with tenant {string}")
One way to add SnmpInterfaces is through NodeScanResult by sending message to Kafka, Please check code [here](https://github.com/OpenNMS-Cloud/lokahi/blob/develop/inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/InventoryProcessingStepDefinitions.java#L405) for reference.

2024-02-26 14:58 UTC, cgorantla commented
you should resolve conflicts properly, we shouldn't see any changes that are not yours

2024-02-26 17:32 UTC, cgorantla reviewed
Tests are not complete, please go through other review comments and resolve

2024-02-26 17:32 UTC, cgorantla commented on rest-server/src/main/java/org/opennms/horizon/server/service/grpc/InventoryClient.java
> +                SearchBy.newBuilder().setSearch((search != null) ? search : "").build();
no need for this null check

2024-02-27 11:43 UTC, smunir-onms commented on inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/InventoryProcessingStepDefinitions.java
> +            // backgroundHelper.getLocation().getBytes(StandardCharsets.UTF_8));
please remove commented code

2024-02-27 16:27 UTC, cgorantla reviewed
I missed this previous review, we are only searching snmp interfaces under a node so `nodeId` should be included in the proto.

2024-02-28 13:51 UTC, MusaidAli commented on shared-lib/inventory/src/main/proto/snmpInterface.proto
> +message SnmpInterfaceCreateDTO {
resolved.

2024-02-28 13:52 UTC, MusaidAli commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/SnmpInterfaceService.java
> +    public SnmpInterface saveSnmpInterface(SnmpInterfaceCreateDTO request) {
resolved

2024-02-28 13:52 UTC, MusaidAli commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/NodeGrpcService.java
> +    public void createSnmpInterface(SnmpInterfaceCreateDTO snmpInterfaceDTO, StreamObserver<SnmpInterfaceDTO> responseObserver) {
resolved.

2024-02-28 13:52 UTC, MusaidAli commented on inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/SnmpInterfaceStepDefinitions.java
> +    @Given("a new snmp_interface with name {string}, desc {string} ,alias {string} , physical address {string} and node label {string} with tenant {string}")
added ,resolved.

2024-02-28 13:52 UTC, MusaidAli commented on rest-server/src/main/java/org/opennms/horizon/server/service/grpc/InventoryClient.java
> +                SearchBy.newBuilder().setSearch((search != null) ? search : "").build();
resolved.

2024-02-28 13:52 UTC, MusaidAli commented on inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/InventoryProcessingStepDefinitions.java
> +            // backgroundHelper.getLocation().getBytes(StandardCharsets.UTF_8));
removed,

2024-02-28 15:58 UTC, smunir-onms commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/NodeGrpcService.java
> +            ;
remove extra semicolon

2024-02-28 16:41 UTC, MusaidAli commented on shared-lib/inventory/src/main/proto/nodeService.proto
> +  string search = 1;
resolved. added updated to search_term.

2024-02-28 16:41 UTC, cgorantla commented on inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/InventoryProcessingStepDefinitions.java
> +    public void verifyMessageInConsumer(String systemPropertyName, String topic) {
we shouldn't test Kafka consumer, we have to test `gRPC` API that you added in `NodeGrpcService`. 
Kafka Consumer propagates data internally to update node.

And since this is async in nature, validate using `await().atMost`

2024-02-29 17:53 UTC, MusaidAli commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/NodeGrpcService.java
> +            ;
resolved.

2024-02-29 22:09 UTC, cgorantla commented on shared-lib/protobuf/src/main/java/org/opennms/horizon/shared/protobuf/util/ProtobufUtil.java
> +    public static Object convertAnyToModel(ScannerResponse message) {
Is this needed ?

2024-03-01 08:47 UTC, MusaidAli commented on inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/InventoryProcessingStepDefinitions.java
> +import org.opennms.horizon.inventory.dto.*;
resolved.

2024-03-01 08:48 UTC, MusaidAli commented on inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/InventoryProcessingStepDefinitions.java
> +                .anyMatch(snmpInterfaceDTO -> snmpInterfaceDTO.getIfName().equals(ifName)));
resolved,removed assert.

2024-03-01 08:48 UTC, MusaidAli commented on inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/InventoryProcessingStepDefinitions.java
> +                                .anyMatch(snmpInterfaceDTO ->
added size>0 ,resolved.

2024-03-01 08:48 UTC, MusaidAli commented on shared-lib/protobuf/src/main/java/org/opennms/horizon/shared/protobuf/util/ProtobufUtil.java
> +    public static Object convertAnyToModel(ScannerResponse message) {
removed,not needed now.

2024-03-01 12:27 UTC, smunir-onms commented on inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/inventory-processing.feature
> +# TBD888 - Test Flows and Traps Configs published
please remove unused code

2024-03-01 13:01 UTC, MusaidAli commented on inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/inventory-processing.feature
> +# TBD888 - Test Flows and Traps Configs published
resolved.

2024-03-01 13:04 UTC, smunir-onms reviewed
LGTM

2024-03-01 13:45 UTC, smunir-onms reviewed
LGTM

2024-03-04 20:20 UTC, cgorantla requested changes

2024-03-04 20:20 UTC, cgorantla commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/NodeGrpcService.java
> +    private final SnmpInterfaceMapper snmpInterfaceMapper;
was mapper getting used here ?

2024-03-04 20:20 UTC, cgorantla commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/SnmpInterfaceService.java
> +    private final NodeRepository nodeRepository;
unused, can remove

2024-03-04 20:20 UTC, cgorantla commented on parent-pom/pom.xml
> +<?xml version="1.0" encoding="utf-8" ?>
revert these changes

2024-03-04 20:20 UTC, cgorantla commented on rest-server/src/main/java/org/opennms/horizon/server/service/GrpcNodeService.java
> +                            "Type")
```suggestion
                    .setHeader(
                            "ALIAS",
                            "IP ADDR",
                            "PHYSICAL ADDR",
                            "INDEX",
                            "DESC",
                            "TYPE", 
                            "NAME",
                            "SPEED",
                            "ADMIN STATUS",
                            "OPERATOR STATUS")
```
Align it with UI, sent you screenshot with real dadta

2024-03-04 20:29 UTC, cgorantla requested changes

2024-03-04 20:29 UTC, cgorantla commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/NodeGrpcService.java
> +        try {
this is different from Alert Service, you have to explicitly check for tenant, follow the patten in other grpc services in this file

2024-03-05 07:23 UTC, MusaidAli commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/NodeGrpcService.java
> +    private final SnmpInterfaceMapper snmpInterfaceMapper;
private final SnmpInterfaceMapper snmpInterfaceMapper; Removed not used.

2024-03-05 07:23 UTC, MusaidAli commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/SnmpInterfaceService.java
> +    private final NodeRepository nodeRepository;
private final NodeRepository nodeRepository; Removed.

2024-03-05 07:29 UTC, MusaidAli commented on parent-pom/pom.xml
> +<?xml version="1.0" encoding="utf-8" ?>
changes reverted from develop branch.

2024-03-05 07:37 UTC, MusaidAli commented on rest-server/src/main/java/org/opennms/horizon/server/service/GrpcNodeService.java
> +                            "Type")
resolved.added like UI screen shot.

2024-03-05 08:55 UTC, MusaidAli commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/NodeGrpcService.java
> +        try {
resolved,added tenantId with or and conditions,tested.

2024-03-05 09:04 UTC, MusaidAli commented on parent-pom/pom.xml
> +<?xml version="1.0" encoding="utf-8" ?>
this was due to running spotless on parent-pom

2024-03-05 11:36 UTC, smunir-onms reviewed
requested changes verified.

2024-03-05 21:51 UTC, cgorantla requested changes

2024-03-05 21:51 UTC, cgorantla commented on inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/inventory-processing.feature
> +    Then verify node has SnmpInterface with ifName "eth0"
what if I only search with `et`, we should use like instead of direct matching on all properties. Please validate this, currently it doesn't work

2024-03-07 16:33 UTC, cgorantla approved these changes
LGTM!

2024-03-07 17:05 UTC, MusaidAli commented on inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/inventory-processing.feature
> +    Then verify node has SnmpInterface with ifName "eth0"
resolved. added et and works

2024-03-07 17:07 UTC, merged