LOK-2229:Added feature getAlertsByNode.
OpenNMS-Cloud/lokahi pull request #1658
Opened 2024-02-22 08:26 UTC by MusaidAli

## Description
BE: BFF: Alerts: GetRecentAlertsByNode 

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2229

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-02-22 17:56 UTC, cgorantla reviewed
Looks good, tests pending.

2024-02-22 17:56 UTC, cgorantla commented on alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
> +            LOG.error("Noinstance available! " + e.getMessage());
```suggestion
            LOG.error("Error while getting alerts by nodeId {}", nodeId, e);
```

2024-02-22 17:56 UTC, cgorantla commented on alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
> +            LOG.error("Noinstance available! " + e.getMessage());
Also we need to send appropriate error message on `responseObserver`

2024-02-22 17:56 UTC, cgorantla commented on alert/src/test/java/org/opennms/horizon/alertservice/stepdefs/AlertTestSteps.java
> +        assertNotNull(ListAlertsResponse.getAlertsList());
when we don't return any exception, `getAlertsList()` will always be non-null.

This is probably incomplete, please add appropriate test

2024-02-23 02:19 UTC, cgorantla requested changes

2024-02-23 02:19 UTC, cgorantla commented on alert/src/main/java/org/opennms/horizon/alertservice/service/AlertEventProcessor.java
> +        alert.setNodeId(event.getNodeId());
we also need to add nodeId in https://github.com/OpenNMS-Cloud/lokahi/pull/1658/files#diff-c0591950bd23ffc13b94b3c007b89cd531f64822d975530923b1b7aa4edab871R133  in  message Alert {...}

2024-02-23 02:19 UTC, cgorantla commented on alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
> +    @Transactional
This doesn't load any child objects, so we may not need `@Transactional` here

2024-02-23 15:43 UTC, cgorantla reviewed
LGTM, resolve conflicts

2024-02-26 14:56 UTC, cgorantla commented
Merge conflicts properly, you shouldn't have any changes that are not yours.

2024-02-26 17:27 UTC, cgorantla reviewed
LGTM, few more comments

2024-02-26 17:27 UTC, cgorantla commented on alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
> +    @Transactional
@MusaidAli we don't need this @Transactional here

2024-02-26 17:27 UTC, cgorantla commented on alert/src/main/resources/db/changelog/hs-0.1.0/tables/alert_add_node_id.xml
> +    <changeSet id="hs-0.1.0-alert-add-node-id" author="musaid">
preferably, your github id  as author `musaidali`

2024-02-26 17:27 UTC, cgorantla commented on alert/src/test/java/org/opennms/horizon/alertservice/stepdefs/AlertTestSteps.java
> +        var ListAlertsResponse = clientUtils.getAlertServiceStub().getAlertsByNode(requestBuilder.build());
```suggestion
        var listAlertsResponse = clientUtils.getAlertServiceStub().getAlertsByNode(requestBuilder.build());
```

2024-02-29 17:18 UTC, MusaidAli commented on alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
> +            LOG.error("Noinstance available! " + e.getMessage());
resolved.

2024-02-29 17:19 UTC, MusaidAli commented on alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
> +    @Transactional
resolved.

2024-02-29 17:23 UTC, MusaidAli commented on alert/src/main/java/org/opennms/horizon/alertservice/service/AlertEventProcessor.java
> +        alert.setNodeId(event.getNodeId());
resolved.

2024-02-29 17:26 UTC, MusaidAli commented on alert/src/test/java/org/opennms/horizon/alertservice/stepdefs/AlertTestSteps.java
> +        assertNotNull(ListAlertsResponse.getAlertsList());
resolved.

2024-02-29 17:31 UTC, MusaidAli commented on alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
> +    @Transactional
resolved.

2024-02-29 17:31 UTC, MusaidAli commented on alert/src/main/resources/db/changelog/hs-0.1.0/tables/alert_add_node_id.xml
> +    <changeSet id="hs-0.1.0-alert-add-node-id" author="musaid">
resolved.

2024-02-29 17:31 UTC, MusaidAli commented on alert/src/test/java/org/opennms/horizon/alertservice/stepdefs/AlertTestSteps.java
> +        var ListAlertsResponse = clientUtils.getAlertServiceStub().getAlertsByNode(requestBuilder.build());
resolved.

2024-02-29 22:10 UTC, cgorantla commented on alert/src/test/java/org/opennms/horizon/alertservice/stepdefs/AlertTestSteps.java
> +        var ListAlertsResponse = clientUtils.getAlertServiceStub().getAlertsByNode(requestBuilder.build());
not resolved yet

2024-02-29 22:10 UTC, cgorantla commented on alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
> +    @Transactional
not resolved yet

2024-03-01 08:52 UTC, MusaidAli commented on alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
> +    @Transactional
resolved.

2024-03-01 08:53 UTC, MusaidAli commented on alert/src/test/java/org/opennms/horizon/alertservice/stepdefs/AlertTestSteps.java
> +        assertNotNull(ListAlertsResponse.getAlertsList());
resolved.

2024-03-01 08:53 UTC, MusaidAli commented on alert/src/test/java/org/opennms/horizon/alertservice/stepdefs/AlertTestSteps.java
> +        var ListAlertsResponse = clientUtils.getAlertServiceStub().getAlertsByNode(requestBuilder.build());
resolved.now Thanks.

2024-03-01 11:38 UTC, MusaidAli commented on alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
> +    @Transactional
resolved ,was throwing User
could not initialize proxy - no session hibernate ,used JPQL instead of native sql.

2024-03-01 14:09 UTC, smunir-onms reviewed
LGTM

2024-03-04 19:43 UTC, cgorantla reviewed
LGTM, few more comments

2024-03-04 19:43 UTC, cgorantla commented on alert/src/main/java/org/opennms/horizon/alertservice/db/repository/AlertRepository.java
> +            value = "SELECT a FROM Alert a LEFT JOIN FETCH a.alertCondition " + "WHERE a.tenantId = :tenantId "
Do we need `LEFT JOIN FETCH a.alertCondition` here ?

2024-03-04 19:43 UTC, cgorantla commented on alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
> +        String sortBy = !request.getSortBy().isEmpty() ? request.getSortBy() : SORT_BY_DEFAULT;
what if `request.getSortBy()` is null ?

2024-03-04 19:43 UTC, cgorantla commented on alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
> +            alertPage = alertRepository.findAlertsByNodeId(tenantId, nodeId, pageRequest);
```suggestion
            var alertPage = alertRepository.findAlertsByNodeId(tenantId, nodeId, pageRequest);
```

2024-03-04 19:43 UTC, cgorantla commented on alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
> +            responseObserver.onNext(response);
```suggestion
            responseObserver.onNext(responseBuilder.build());
```

2024-03-04 19:43 UTC, cgorantla commented on alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
> +                    .setMessage("Error while getting alerts with nodeId {} " + nodeId + e.getMessage())
don't need to send exception message to BFF

2024-03-05 06:35 UTC, MusaidAli commented on alert/src/main/java/org/opennms/horizon/alertservice/db/repository/AlertRepository.java
> +            value = "SELECT a FROM Alert a LEFT JOIN FETCH a.alertCondition " + "WHERE a.tenantId = :tenantId "
removed working fine after removing this.previously this was giving error may -- could not initialize proxy - no session hibernate --- but i think this was because of native sql .tested working fine now ,removed left join fetch a.alertcondition.

2024-03-05 06:38 UTC, MusaidAli commented on alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
> +            alertPage = alertRepository.findAlertsByNodeId(tenantId, nodeId, pageRequest);
resolved added  var alertPage.

2024-03-05 06:39 UTC, MusaidAli commented on alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
> +            responseObserver.onNext(response);
resolved.

2024-03-05 06:43 UTC, MusaidAli commented on alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
> +                    .setMessage("Error while getting alerts with nodeId {} " + nodeId + e.getMessage())
added the following code.is this correct.           

 Status status = Status.newBuilder()
                .setCode(Code.NOT_FOUND_VALUE)
                .setMessage("Error while getting alerts")
                .build();
            responseObserver.onError(StatusProto.toStatusRuntimeException(status));

2024-03-05 06:49 UTC, MusaidAli commented on alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
> +        String sortBy = !request.getSortBy().isEmpty() ? request.getSortBy() : SORT_BY_DEFAULT;
added null check.  

if(request.getSortBy()!=null) {
}

2024-03-05 07:08 UTC, MusaidAli commented on alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
> +        String sortBy = !request.getSortBy().isEmpty() ? request.getSortBy() : SORT_BY_DEFAULT;
Caused by: java.lang.NullPointerException: null
	at org.opennms.horizon.alerts.proto.AlertRequestByNode$Builder.setSortBy(AlertRequestByNode.java:669)
	at org.opennms.horizon.server.service.grpc.AlertsClient.getAlertsByNode(AlertsClient.java:351)

2024-03-05 07:14 UTC, MusaidAli commented on alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
> +        String sortBy = !request.getSortBy().isEmpty() ? request.getSortBy() : SORT_BY_DEFAULT;
so i have handle null check ,the following 
  request.setPageSize(pageSize)
                .setPage(page)
                .setSortBy((sortBy==null)?"id":sortBy)
                .setSortAscending(sortAscending)
                .setNodeId(nodeId)
                .build();

2024-03-05 21:00 UTC, cgorantla approved these changes
LGTM!

2024-03-05 21:35 UTC, merged