LOK-2233 : BFF: Node: SearchIpInterfaces
OpenNMS-Cloud/lokahi pull request #1660
Opened 2024-02-22 18:35 UTC by Junaid-Khan-Nant

## Description

1. Add gRPC service in nodeService.proto to search IpInterfaces either by IpAddress or by hostName and return list of IpInterface ( IpInterfaceDTO in ipInterface.proto.
2. Implement this in Inventory service along with a test case.
3. Use this new service in BFF ( rest-server) to implement new GraphQL service that will take a string and return List of IpInterfaces.

## Jira link(s)
https://opennms.atlassian.net/browse/LOK-2233

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-02-22 20:54 UTC, cgorantla requested changes

2024-02-22 20:54 UTC, cgorantla commented on shared-lib/inventory/src/main/proto/nodeService.proto
> +  string ip_address =3;
there will be multiple ip interfaces under one node and we are searching those ip interfaces so we shouldn't carry ip address.

2024-02-22 20:54 UTC, cgorantla commented on rest-server/src/main/java/org/opennms/horizon/server/service/grpc/InventoryClient.java
> +    public List<IpInterfaceDTO> listIpInterfacesByNodeSearch(Long nodeId,String ipInterfaceSearchTerm,String ipAddress, String accessToken) {
```suggestion
    public List<IpInterfaceDTO> listIpInterfacesBySearchTerm(Long nodeId,String searchTerm, String accessToken) {
```

2024-02-22 20:54 UTC, cgorantla commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
> +    public List<IpInterfaceDTO> listSearchIpInterfacesByQuery(String tenantId, Long nodeId, String searchIpInterfaceTerm, String ipAddress) {
remove `ipAddress` from this call

2024-02-22 20:54 UTC, cgorantla commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/NodeGrpcService.java
> +import org.opennms.horizon.inventory.dto.*;
avoid using wildcard imports

2024-02-22 20:54 UTC, cgorantla commented on inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/node.feature
> +  Scenario: Search IpInterfaces by Node
It would be good to not depend on previous scenario for data.

2024-02-26 12:52 UTC, smunir-onms commented
please resolve conflicts before new changes

2024-02-26 17:33 UTC, cgorantla requested changes
resolve conflicts

2024-02-29 22:04 UTC, closed without merging

2024-02-29 22:11 UTC, cgorantla commented
Closing as https://github.com/OpenNMS-Cloud/lokahi/pull/1665 will take care of this.