LOK-2233 : BFF: Node: SearchIpInterfaces
OpenNMS-Cloud/lokahi pull request #1665
Opened 2024-02-26 18:50 UTC by Junaid-Khan-Nant

## Description
1. Add gRPC service in nodeService.proto to search IpInterfaces either by IpAddress or by hostName and return list of IpInterface ( IpInterfaceDTO in ipInterface.proto.
2. Implement this in Inventory service along with a test case.
3. Use this new service in BFF ( rest-server) to implement new GraphQL service that will take a string and return List of IpInterfaces.

## Jira link(s)
https://opennms.atlassian.net/browse/LOK-2233

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-02-27 11:22 UTC, smunir-onms reviewed
looks good to me

2024-02-28 14:26 UTC, smunir-onms commented on shared-lib/lokahi-common-utils/src/main/java/org/opennms/horizon/shared/utils/InetAddressUtils.java
> +    public static boolean isValidIpAddress(String ipAddress) {
minor: name should be more descriptive: isValidIpv4OrIpv6Address

2024-02-28 14:44 UTC, smunir-onms reviewed
LGTM

2024-02-28 15:05 UTC, Junaid-Khan-Nant commented on shared-lib/lokahi-common-utils/src/main/java/org/opennms/horizon/shared/utils/InetAddressUtils.java
> +    public static boolean isValidIpAddress(String ipAddress) {
Done

2024-02-28 16:04 UTC, cgorantla requested changes

2024-02-28 16:04 UTC, cgorantla commented on inventory/main/src/main/java/org/opennms/horizon/inventory/repository/IpInterfaceRepository.java
> +            @Param("ipAddress") InetAddress ipAddress,
A node has multiple IpInterfaces and each IpInterfaces is an IpAddress ( InetAddress), you have to search in all of those IpAdresses not one IpAddress

2024-02-29 15:26 UTC, Junaid-Khan-Nant commented on shared-lib/inventory/src/main/proto/nodeService.proto
> +  rpc listSearchIpInterfaceByQuery(SearchIpInterfaceQuery) returns (IpInterfaceList) {};
Done

2024-02-29 15:26 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
> +        if (InetAddressUtils.isValidIpv4OrIpv6Address(searchIpInterfaceTerm)) {
Done

2024-03-01 12:56 UTC, smunir-onms reviewed
SGTM

2024-03-04 18:22 UTC, smunir-onms reviewed
updated changes seems OK

2024-03-04 20:27 UTC, cgorantla requested changes

2024-03-04 20:27 UTC, cgorantla commented on shared-lib/lokahi-common-utils/src/main/java/org/opennms/horizon/shared/utils/InetAddressUtils.java
> +    public static boolean isValidIpv4OrIpv6Address(String ipAddress) {
unused, remove

2024-03-04 20:27 UTC, cgorantla commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/NodeGrpcService.java
> +
log the exception

2024-03-04 20:27 UTC, cgorantla commented on inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/NodeStepDefinitions.java
> +    @Then("verify the list of IpInterfaces has size greater than {int}")
you can combine these two steps

2024-03-05 11:26 UTC, smunir-onms reviewed
requested changes verified

2024-03-05 22:31 UTC, cgorantla reviewed
few comments otherwise looks good to me.

2024-03-05 22:31 UTC, cgorantla commented on inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/node.feature
> +    Then fetch a list of IpInterfaces by node using search term "128.0.0.1" that has size greater than 0
update this  `Then fetch a list of IpInterfaces by node using search term "my" that has size greater than 0`. and see if it passes

2024-03-05 22:31 UTC, cgorantla commented on inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/inventory-processing.feature
> +    Then verify node has IpInterface with hostName "Local"
```suggestion
    Then verify node has IpInterface with hostName "Loc"
```
update this to partial search and see if it works

2024-03-05 22:31 UTC, cgorantla commented on inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/NodeStepDefinitions.java
> +                .orElseThrow(() -> new IllegalArgumentException("Node " + ipAddress + " not found"));
don't think we need this check

2024-03-06 11:11 UTC, Junaid-Khan-Nant commented on inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/NodeStepDefinitions.java
> +                .orElseThrow(() -> new IllegalArgumentException("Node " + ipAddress + " not found"));
Removed.

2024-03-06 11:11 UTC, Junaid-Khan-Nant commented on inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/inventory-processing.feature
> +    Then verify node has IpInterface with hostName "Local"
Its working with partial search.

2024-03-06 15:47 UTC, Junaid-Khan-Nant commented on inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/node.feature
> +    Then fetch a list of IpInterfaces by node using search term "128.0.0.1" that has size greater than 0
As discuss its is done.

2024-03-06 18:10 UTC, smunir-onms reviewed
latest changes verified.

2024-03-06 21:56 UTC, cgorantla approved these changes
LGTM!

2024-03-07 09:46 UTC, Junaid-Khan-Nant commented
Merge LOK-2233 into develop.

2024-03-07 10:11 UTC, merged