FE: Node Status: Add initial unit tests
OpenNMS-Cloud/lokahi pull request #1700
Opened 2024-03-11 12:00 UTC by faizanjanjua

## Description
Add some initial unit tests for the Node Status page.

Add tests/NodeStatus/nodeStatus.test.ts and use inventory.test.ts as an example.

Ensure the main title and System Information title are present.

We will add more tests in the future, this is just to add the first one.

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2347

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-03-11 12:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1700) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1700) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenNMS-Cloud/lokahi?pullRequest=1700) it.</sub>

2024-03-11 19:07 UTC, synqotik requested changes
Please see comments.

Also, make sure to run `yarn lint` and fix any code formatting issues. Thanks

2024-03-11 19:07 UTC, synqotik commented on ui/tests/NodeStatus/nodeStatus.test.ts
> +const mockRouter = createRouter({ history: createWebHistory(), routes: [
For now, I don't think we need this `mockRouter`. You can use:

```
import router from '@/router'
```

and then pass it to the `mountWithPiniaVillus` call

2024-03-11 19:07 UTC, synqotik commented on ui/tests/NodeStatus/nodeStatus.test.ts
> +await mockRouter.isReady()
Remove `mockRouter`

2024-03-11 19:07 UTC, synqotik commented on ui/tests/NodeStatus/nodeStatus.test.ts
> +describe('Inventory page', () => {
Should be `'Node Status page'`

2024-03-11 19:07 UTC, synqotik commented on ui/tests/NodeStatus/nodeStatus.test.ts
> +    wrapper = mountWithPiniaVillus({
Creating the `wrapper` should go into a `beforeAll` block

2024-03-11 19:07 UTC, synqotik commented on ui/tests/NodeStatus/nodeStatus.test.ts
> +        stubs: {
Not sure if we need this `RouterLinkStub` or not, try it without (`stubs: false`)

2024-03-11 19:07 UTC, synqotik commented on ui/tests/NodeStatus/nodeStatus.test.ts
> +    // const featherTabContainer = wrapper.getComponent('[data-test="tab-container"]')
Delete these commented-out lines

2024-03-12 17:35 UTC, synqotik approved these changes

2024-03-13 08:53 UTC, faizanjanjua commented on ui/tests/NodeStatus/nodeStatus.test.ts
> +        stubs: {
Done

2024-03-13 08:53 UTC, faizanjanjua commented on ui/tests/NodeStatus/nodeStatus.test.ts
> +describe('Inventory page', () => {
Done

2024-03-13 08:53 UTC, faizanjanjua commented on ui/tests/NodeStatus/nodeStatus.test.ts
> +await mockRouter.isReady()
Done

2024-03-13 08:53 UTC, faizanjanjua commented on ui/tests/NodeStatus/nodeStatus.test.ts
> +const mockRouter = createRouter({ history: createWebHistory(), routes: [
Done

2024-03-13 09:27 UTC, merged