Akhan/jira/lok 2238
OpenNMS-Cloud/lokahi pull request #1701
Opened 2024-03-11 17:59 UTC by aurang-zeb313

## Description
DownloadEventsToCsv
Columns included will be Time ( format should be same as UI) , UEI, description fields are sufficient.

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2238

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-03-13 17:50 UTC, cgorantla requested changes

2024-03-13 17:50 UTC, cgorantla commented on rest-server/src/main/java/org/opennms/horizon/server/service/GrpcEventService.java
> +            CSVPrinter csvPrinter = new CSVPrinter(csvData, csvformat);
Use this with `try with resources`, while you are there also fix this in `generateDownloadableIpInterfacesResponse`

2024-03-14 11:19 UTC, aurang-zeb313 commented on rest-server/src/main/java/org/opennms/horizon/server/service/GrpcEventService.java
> +            CSVPrinter csvPrinter = new CSVPrinter(csvData, csvformat);
Done

2024-03-14 16:21 UTC, cgorantla approved these changes
LGTM!

2024-03-15 09:11 UTC, merged