LOK : 2272 : Prevent duplicate nodes for the same IPAddress for a given location
OpenNMS-Cloud/lokahi pull request #1706
Opened 2024-03-12 16:35 UTC by Junaid-Khan-Nant

## Description
- When we have multiple Minions,  sometimes I see that duplicate nodes being created. This should be prevented.
- Node  is always associated with a location so it should have foreign key with monitoring location and a node can have multiple Ip Interfaces.
- We should prevent  duplicate IpAddress ( IpInterface) for a given location.
- This can be achieved with unique constraint between IpAddress and location.
- Add a test case to prove that this will work.

## Jira link(s)
https://opennms.atlassian.net/browse/LOK-2272

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-03-12 17:26 UTC, smunir-onms commented on inventory/main/src/main/resources/db/changelog/hs-0.1.0/tables/ip-interface-add-new-column.xml
> +    <changeSet id="add_fk_to_ipinterface" author="tbigg">
add proper id as per conventions, set your github ID in the author

2024-03-12 17:26 UTC, smunir-onms commented on inventory/main/src/main/resources/db/changelog/hs-0.1.0/tables/ip-interface-add-new-column.xml
> +    <changeSet id="add_unique_constraint_to_ipinterface" author="tbigg">
same here

2024-03-12 17:27 UTC, smunir-onms requested changes
overall looks good, added some comments

2024-03-13 11:12 UTC, smunir-onms reviewed
LGTM, discussed changes verified

2024-03-14 11:50 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
> +            ipInterface.setLocation(node.getMonitoringLocation());
Done

2024-03-14 12:58 UTC, smunir-onms reviewed
LGTM, make sure reference unit tests shouldn't fail

2024-03-14 16:19 UTC, cgorantla commented on inventory/main/src/main/java/org/opennms/horizon/inventory/component/NodeKafkaProducer.java
> +    //    @PostUpdate
please remove this, this is not to be checked in

2024-03-14 16:22 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/component/NodeKafkaProducer.java
> +    //    @PostUpdate
Done.

2024-03-14 16:48 UTC, cgorantla commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
> +            throw new DataIntegrityViolationException("Ip address already exists for a given location", e);
don't need to throw same exception unless you are converting it into custom exception, always log exceptions

2024-03-14 16:48 UTC, cgorantla commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
> +            throws EntityExistException, LocationNotFoundException, DataIntegrityViolationException {
How does this new exception handled at grpc layer ?

2024-03-14 16:48 UTC, cgorantla commented on inventory/main/src/main/resources/db/changelog/hs-0.1.0/tables/ip-interface-add-new-column.xml
> +            <column name="location_id" type="bigint"/>
this should be non-null and existing ip interfaces should be updated with node_id

2024-03-14 17:37 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
> +            throws EntityExistException, LocationNotFoundException, DataIntegrityViolationException {
Handle in NodeGrpcService in createNode method.

2024-03-14 17:39 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/resources/db/changelog/hs-0.1.0/tables/ip-interface-add-new-column.xml
> +            <column name="location_id" type="bigint"/>
Add constraint for not null and i think node_id is already updated. Please correct if i am not wrong.

2024-03-14 17:45 UTC, cgorantla commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/NodeGrpcService.java
> +                Status status = Status.newBuilder()
we are not sure if `DataIntegrityViolationException` could always be associated with  duplicate ip address, it could be very generic

2024-03-14 17:45 UTC, cgorantla commented on inventory/main/src/main/resources/db/changelog/hs-0.1.0/tables/ip-interface-add-new-column.xml
> +                <constraints nullable="false"/>
This will fail for existing tables, you need to handle this with another sql query to update existing tables

2024-03-15 16:43 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/NodeGrpcService.java
> +                Status status = Status.newBuilder()
Change to generic runtime exception.

2024-03-15 16:45 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/resources/db/changelog/hs-0.1.0/tables/ip-interface-add-new-column.xml
> +                <constraints nullable="false"/>
Added Please review the SQL query.

2024-03-15 16:49 UTC, smunir-onms commented on inventory/main/src/main/resources/db/changelog/hs-0.1.0/tables/ip-interface-add-new-column.xml
> +                <constraints nullable="false"/>
sql query seems OK, make sure it works with existing data

2024-03-15 19:13 UTC, cgorantla requested changes
Suggest to catch `DataIntegrityVoilationException` just after the  `.save(entity)` and expose a custom exception to handle database errors.  For now, you can use `ABORTED_VALUE` as grpc error when handling those database errors.
If you can parse and extract duplicate element exception, expose it with custom exception like `DuplicateDataException`  and use `ALREADY_EXISTS_VALUE` grpc error.

2024-03-15 19:13 UTC, cgorantla commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/NodeGrpcService.java
> +                Status status = Status.newBuilder()
I don't mean to change this to RuntimeException. Unless you parse DataIntegrityViolationException and make sure it is violating unique constraint for  ip_address, location combination, you are not sure if this is related to duplicate data.

2024-03-19 18:19 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/resources/db/changelog/hs-0.1.0/tables/ip-interface-add-new-column.xml
> +                <constraints nullable="false"/>
query update.

2024-03-28 13:09 UTC, smunir-onms commented
duplicate of https://github.com/OpenNMS-Cloud/lokahi/pull/1737

2024-03-28 13:09 UTC, closed without merging