Ma/jira/lok sys log
OpenNMS-Cloud/lokahi pull request #1717
Opened 2024-03-14 17:46 UTC by MusaidAli

## Description
SysLog implementation module

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-XXXX

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-03-14 19:34 UTC, cgorantla reviewed
Not sure what you are trying to do here.

Minion is an OSGi application, it runs on karaf, there is no need to for any spring boot dependencies.

Ignore the test cases,  Integrate SyslogReceiver , it's implementation along with blueprint and feature files. Make sure that this feature resolves properly on karaf when we run Minion.

2024-03-18 12:18 UTC, cgorantla requested changes
First get the Receiver loaded properly along with bundle and feature. Then we can add more layers

2024-03-18 12:18 UTC, cgorantla commented on minion/minion-syslog/features/src/main/feature/feature.xml
> +      <!--  <bundle>mvn:org.opennms.lokahi.minion/syslog-listener/${project.version}</bundle>-->
you need to have required bundles for this feature.

2024-03-18 12:18 UTC, cgorantla commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyncDispatcher.java
not required

2024-03-18 12:18 UTC, cgorantla commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SinkModule.java
> +/*
not required

2024-03-18 12:18 UTC, cgorantla commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SimpleNamespaceFilter.java
> +/*
not required

2024-03-18 12:18 UTC, cgorantla commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/MessageDispatcherFactory.java
> +/*
not required

2024-03-18 12:18 UTC, cgorantla commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/Message.java
> + * Licensed to The OpenNMS Group, Inc (TOG) under one or more
not required

2024-03-18 12:18 UTC, cgorantla commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/AsyncPolicy.java
> +/*
not required

2024-03-18 12:18 UTC, cgorantla commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/AsyncDispatcher.java
> +/*
not required

2024-03-18 12:18 UTC, cgorantla commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/AggregationPolicy.java
> +/*
not required

2024-03-18 12:18 UTC, cgorantla commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/AbstractXmlSinkModule.java
> +/*
not required

2024-03-18 12:18 UTC, cgorantla commented on minion/minion-syslog/listener/pom.xml
> +        <dependency>
clean up these libraries that are not required

2024-03-18 12:43 UTC, MusaidAli commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/MessageDispatcherFactory.java
> +/*
m_dispatcher.send(new SyslogConnection(source, buffer)).get();
this is required.

2024-03-18 12:52 UTC, MusaidAli commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SimpleNamespaceFilter.java
> +/*
public static XMLFilter getXMLFilterForNamespace(final String namespace) throws SAXException {
        XMLFilter filter = namespace == null ? new SimpleNamespaceFilter("", false) : new SimpleNamespaceFilter(namespace, true);

        LOG.trace("namespace filter for namespace {}: {}", namespace, filter);
        final XMLReader xmlReader = XMLReaderFactory.createXMLReader();
        xmlReader.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
        xmlReader.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
        xmlReader.setFeature("http://xml.org/sax/features/external-general-entities", false);
        xmlReader.setFeature("http://xml.org/sax/features/external-parameter-entities", false);

        filter.setParent(xmlReader);
        return filter;
    }

this is required

2024-03-19 10:13 UTC, closed without merging