LOK-2367 Events: User Interceptor for handing tenant validation
OpenNMS-Cloud/lokahi pull request #1722
Opened 2024-03-15 11:36 UTC by smunir-onms

## Description

On Events Service, we should use  io.grpc.ServerInterceptor to handle tenant validation.

Please check AlertServerInterceptor  for reference

Remove existing checks for tenantId validation in grpc service calls.

Add a integration test to validate that Interceptor is indeed getting used

## Jira link(s)
https://opennms.atlassian.net/browse/LOK-2367

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-03-21 17:43 UTC, smunir-onms commented
@cgorantla I found this test class EventGrpcServiceTest where intercepter is getting used, do I need to add more stuff?

2024-03-22 18:47 UTC, cgorantla reviewed
This looks fine. Would like to test case that validates that a invalid tenant would result in appropriate response when calling grpc services

2024-03-26 10:06 UTC, fooker requested changes
Just minor nit

2024-03-26 10:06 UTC, fooker commented on events/grpc/src/main/java/org/opennms/horizon/events/grpc/service/EventGrpcService.java
> +                Optional.ofNullable(GrpcConstants.TENANT_ID_CONTEXT_KEY.get()).orElseThrow();
Use `Objects::requireNonNull` instead of `Optional`.

2024-03-26 10:06 UTC, fooker commented on events/grpc/src/main/java/org/opennms/horizon/events/grpc/service/EventGrpcService.java
> +                Optional.ofNullable(GrpcConstants.TENANT_ID_CONTEXT_KEY.get()).orElseThrow();
Use `Objects::requireNonNull` instead of `Optional`.

2024-03-26 11:44 UTC, fooker approved these changes

2024-03-27 15:59 UTC, cgorantla reviewed
Is it possible to validate this integration test instead of a unit test where we know the interceptor is actually filtering the requests

2024-03-27 17:54 UTC, smunir-onms commented
> Is it possible to validate this integration test instead of a unit test where we know the interceptor is actually filtering the requests

Should add feature test? have to wait for feature integration in events.

2024-03-28 21:22 UTC, cgorantla approved these changes

2024-03-29 10:14 UTC, merged