akhan/jira/LOK-2369
OpenNMS-Cloud/lokahi pull request #1728
Opened 2024-03-18 17:03 UTC by aurang-zeb313

## Description
Service Monitor results contains a field named properties which is used to transport metrics gathered from the monitoring poll execution. Rename accordingly.
Starting point is ServiceMonitorResponseImpl. Rename the field properties to metrics. Find all usages of this field in the whole code-base and rename other usages, too. Be aware that this is named metrics in some places already. Check in modules minion, minion-gateway and metric-processor.

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2369

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-03-18 17:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1728) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1728) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenNMS-Cloud/lokahi?pullRequest=1728) it.</sub>

2024-03-18 19:06 UTC, cgorantla approved these changes
LGTM!

2024-03-18 19:07 UTC, cgorantla requested changes

2024-03-18 19:07 UTC, cgorantla commented on minion/plugins/plugins-api/src/main/java/org/opennms/horizon/minion/plugin/api/ServiceMonitorResponseImpl.java
> +    private Map<String, Number> metrics;
May be update this to optionalMetrics

2024-03-18 19:11 UTC, cgorantla commented on minion/plugins/plugins-api/src/main/java/org/opennms/horizon/minion/plugin/api/ServiceMonitorResponseImpl.java
> +    private Map<String, Number> metrics;
Or may be additionalMetrics

2024-03-19 10:13 UTC, aurang-zeb313 commented on minion/plugins/plugins-api/src/main/java/org/opennms/horizon/minion/plugin/api/ServiceMonitorResponseImpl.java
> +    private Map<String, Number> metrics;
OK

2024-03-19 10:34 UTC, smunir-onms commented on minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutionResultProcessorImpl.java
> +                        Optional.of(smr).map(ServiceMonitorResponse::getMetrics).orElse(Collections.EMPTY_MAP))
This reference seems unchanged

2024-03-19 10:47 UTC, fooker approved these changes

2024-03-22 14:18 UTC, cgorantla approved these changes
LGTM!

2024-03-22 14:19 UTC, merged