LOK : 2372 : BE: Add pagination to Events by NodeId
OpenNMS-Cloud/lokahi pull request #1729
Opened 2024-03-18 17:53 UTC by Junaid-Khan-Nant

## Description
- Add pagination to Events by NodeId  grpc and graphql services.
- Add sorting.
- Add appropriate tests to validate this.

## Jira link(s)
https://opennms.atlassian.net/browse/LOK-2372

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-03-22 14:29 UTC, cgorantla commented on events/grpc/src/main/java/org/opennms/horizon/events/grpc/service/EventGrpcService.java
> +        var events = eventService.searchEvents(tenantId, request, pageRequest);
It would be better to catch any exceptions from `eventService.searchEvents(tenantId, request, pageRequest);` and  send an error on responseObserver

2024-03-22 14:29 UTC, cgorantla commented on events/persistence/src/main/java/org/opennms/horizon/events/persistence/service/EventService.java
> +        List<Event> collect = eventPage.getContent().stream()
```suggestion
        List<Event> events = eventPage.getContent().stream()
```

2024-03-22 14:29 UTC, cgorantla commented on rest-server/src/main/java/org/opennms/horizon/server/service/GrpcEventService.java
>      @GraphQLQuery(name = "downloadEvents")
`downloadEventsByNodeId` would be better term here

2024-03-22 14:29 UTC, cgorantla commented on rest-server/src/main/java/org/opennms/horizon/server/service/GrpcEventService.java
>              @GraphQLArgument(name = "searchTerm") String searchTerm,
we can remove `searchTerm`, we can keep sorting.

2024-03-22 16:30 UTC, Junaid-Khan-Nant commented on events/grpc/src/main/java/org/opennms/horizon/events/grpc/service/EventGrpcService.java
> +        var events = eventService.searchEvents(tenantId, request, pageRequest);
Done

2024-03-22 16:30 UTC, Junaid-Khan-Nant commented on events/persistence/src/main/java/org/opennms/horizon/events/persistence/service/EventService.java
> +        List<Event> collect = eventPage.getContent().stream()
Done

2024-03-22 16:31 UTC, Junaid-Khan-Nant commented on rest-server/src/main/java/org/opennms/horizon/server/service/GrpcEventService.java
>              @GraphQLArgument(name = "searchTerm") String searchTerm,
Done

2024-03-22 16:51 UTC, Junaid-Khan-Nant commented on rest-server/src/main/java/org/opennms/horizon/server/service/GrpcEventService.java
>      @GraphQLQuery(name = "downloadEvents")
Done

2024-03-26 10:17 UTC, fooker requested changes

2024-03-26 10:17 UTC, fooker commented on events/grpc/src/main/java/org/opennms/horizon/events/grpc/service/EventGrpcService.java
> +            String tenantId = tenantLookup.lookupTenantId(Context.current()).orElseThrow();
tenant lookup should always be first in function

2024-03-26 10:17 UTC, fooker commented on events/grpc/src/main/java/org/opennms/horizon/events/grpc/service/EventGrpcService.java
> +        } catch (Exception e) {
Catching pain `Exception` is almost never a good idea.

Is there even anything in the try block that throws?

2024-03-26 10:17 UTC, fooker commented on events/main/src/test/java/org/opennms/horizon/events/grpc/service/EventGrpcSearchEventsTest.java
> +        EventLogListResponse eventLog1 = serviceStub.searchEvents(searchEventByNodeIdAndLogMessage);
While you are here anyways, make these `var`s.

2024-03-26 10:17 UTC, fooker commented on events/persistence/src/main/java/org/opennms/horizon/events/persistence/repository/EventRepository.java
> +                    "SELECT count(e) " + "FROM Event e " + "WHERE e.tenantId = :tenantId " + "AND e.nodeId = :nodeId ")
Can be a single string. Same for above.

2024-03-26 10:17 UTC, fooker commented on rest-server/src/main/java/org/opennms/horizon/server/service/GrpcEventService.java
> -            @GraphQLArgument(name = "searchTerm") String searchTerm,
Why remove this param?

2024-03-26 10:17 UTC, fooker commented on rest-server/src/main/java/org/opennms/horizon/server/service/GrpcEventService.java
> +                        .searchEvents(nodeId, "", pageSize, page, sortBy, sortAscending, headerUtil.getAuthHeader(env))
I doubt passing `""` is the right thing to do.

2024-03-26 10:36 UTC, Junaid-Khan-Nant commented on rest-server/src/main/java/org/opennms/horizon/server/service/GrpcEventService.java
> -            @GraphQLArgument(name = "searchTerm") String searchTerm,
This is done as instructed by @cgorantla.
https://github.com/OpenNMS-Cloud/lokahi/pull/1729/files/de4b3a2d6c6b3221b602ab0857e46bcd5abaaf7a#r1535681053

2024-03-26 11:20 UTC, Junaid-Khan-Nant commented on events/grpc/src/main/java/org/opennms/horizon/events/grpc/service/EventGrpcService.java
> +            String tenantId = tenantLookup.lookupTenantId(Context.current()).orElseThrow();
Done.

2024-03-26 11:24 UTC, Junaid-Khan-Nant commented on events/grpc/src/main/java/org/opennms/horizon/events/grpc/service/EventGrpcService.java
> +        } catch (Exception e) {
There is possibility of exception for tenant or may be runtime.

2024-03-26 11:24 UTC, Junaid-Khan-Nant commented on events/main/src/test/java/org/opennms/horizon/events/grpc/service/EventGrpcSearchEventsTest.java
> +        EventLogListResponse eventLog1 = serviceStub.searchEvents(searchEventByNodeIdAndLogMessage);
Done

2024-03-26 11:24 UTC, Junaid-Khan-Nant commented on events/persistence/src/main/java/org/opennms/horizon/events/persistence/repository/EventRepository.java
> +                    "SELECT count(e) " + "FROM Event e " + "WHERE e.tenantId = :tenantId " + "AND e.nodeId = :nodeId ")
Done

2024-03-26 11:30 UTC, Junaid-Khan-Nant commented on rest-server/src/main/java/org/opennms/horizon/server/service/GrpcEventService.java
> +                        .searchEvents(nodeId, "", pageSize, page, sortBy, sortAscending, headerUtil.getAuthHeader(env))
As search term is mandatory parameter for method as per comment of @cgorantla remove it from download method . But it has to pass something at service layer null will throw exception.

2024-03-26 11:47 UTC, fooker commented on rest-server/src/main/java/org/opennms/horizon/server/service/GrpcEventService.java
> +                        .searchEvents(nodeId, "", pageSize, page, sortBy, sortAscending, headerUtil.getAuthHeader(env))
quick search in code shows  that this is used in a `LIKE` statement, therefore the empty string will always lead to an empty result.

2024-03-26 11:50 UTC, fooker commented on events/grpc/src/main/java/org/opennms/horizon/events/grpc/service/EventGrpcService.java
> +        } catch (Exception e) {
There is always something that can throw a runtime exception. Is there anything in the try block that requires you to catch? If yes, make the catch block more specific. If not, remove it.

It is always a bad idea to randomly catch `Exception` as it would catch things that rarely occur but should be passed on

2024-03-26 12:20 UTC, Junaid-Khan-Nant commented on rest-server/src/main/java/org/opennms/horizon/server/service/GrpcEventService.java
> +                        .searchEvents(nodeId, "", pageSize, page, sortBy, sortAscending, headerUtil.getAuthHeader(env))
What u suggest should I add searchTerm in paramters for method downloadEventsByNodeId.

2024-03-26 13:08 UTC, fooker commented on rest-server/src/main/java/org/opennms/horizon/server/service/GrpcEventService.java
> +                        .searchEvents(nodeId, "", pageSize, page, sortBy, sortAscending, headerUtil.getAuthHeader(env))
I don't know. Do we use this function in UI already? If yes, do we pass a default value there?

2024-03-26 15:53 UTC, smunir-onms reviewed
LGTM

2024-03-26 19:57 UTC, cgorantla reviewed
Looks good to me. Were you able to validate this in GraphQL ?

2024-03-27 10:12 UTC, Junaid-Khan-Nant commented
> Looks good to me. Were you able to validate this in GraphQL ?

Y

2024-03-27 10:15 UTC, Junaid-Khan-Nant commented
> Looks good to me. Were you able to validate this in GraphQL ?

Yes.. Screenshot
![Screenshot from 2024-03-27 15-12-06](https://github.com/OpenNMS-Cloud/lokahi/assets/157728179/fcd8abaf-55f8-4608-8282-f2dbdda6efda)
![Screenshot from 2024-03-27 15-11-35](https://github.com/OpenNMS-Cloud/lokahi/assets/157728179/0c262263-49d1-4a8e-8ea6-45b5c7031095)
 is attached.

2024-03-27 15:56 UTC, cgorantla approved these changes
LGTM!

2024-03-28 10:41 UTC, Junaid-Khan-Nant commented
Merge into develop branch.

2024-03-28 11:24 UTC, smunir-onms approved these changes
LGTM

2024-03-28 11:31 UTC, smunir-onms commented on rest-server/src/main/java/org/opennms/horizon/server/service/GrpcEventService.java
> +                        .searchEvents(nodeId, "", pageSize, page, sortBy, sortAscending, headerUtil.getAuthHeader(env))
As per last discussion, double quote replaced with search term by @Junaid-Khan-Nant

2024-03-28 11:42 UTC, merged