LOK: 2337 Syslog Module Opennms Lokahi
OpenNMS-Cloud/lokahi pull request #1734
Opened 2024-03-19 10:09 UTC by MusaidAli

## Description
Add Syslog receiver on Minion

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2337

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-03-26 14:38 UTC, fooker requested changes

2024-03-26 16:42 UTC, MusaidAli commented on minion/minion-syslog/listener/src/test/java/org/test/AppTest.java
> +    public static void main(String[] args) throws Exception {
resolved,removed AppTest not needed.

2024-03-26 16:42 UTC, MusaidAli commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/MyCamelRoute.java
> +public class MyCamelRoute extends RouteBuilder {
removed.

2024-03-26 16:43 UTC, MusaidAli commented on minion/minion-syslog/listener/src/test/java/org/test/TestRoute.java
> +public class TestRoute extends RouteBuilder {
removed.

2024-03-26 19:56 UTC, cgorantla reviewed
Were you able to validate that this listener can receive syslogs ?

2024-03-26 19:56 UTC, cgorantla commented on minion/minion-syslog/listener/pom.xml
> +      <artifactId>camel-core</artifactId>
use specific version for camel here

2024-03-26 19:56 UTC, cgorantla commented on minion/minion-syslog/listener/pom.xml
> +      <artifactId>camel-netty</artifactId>
use specific version for camel-netty here

2024-03-26 19:56 UTC, cgorantla commented on minion/minion-syslog/listener/pom.xml
> +      <version>0.1.0-SNAPSHOT</version>
use ${project.version}

2024-03-26 19:56 UTC, cgorantla commented on minion/minion-syslog/listener/pom.xml
> +      <version>2.3.1</version>
user version from parent pom

2024-03-26 19:56 UTC, cgorantla commented on minion/minion-syslog/listener/pom.xml
> +            <Import-Package>!io.netty.buffer,
do we need this import package ?

2024-03-26 19:56 UTC, cgorantla commented on shared-lib/protobuf/src/main/proto/traps-config.proto
> +message SyslogConfig {
remove this

2024-03-27 09:11 UTC, MusaidAli commented on minion/minion-syslog/listener/pom.xml
> +      <version>0.1.0-SNAPSHOT</version>
giving error : Property in parent definition are prohibited.

2024-03-27 09:18 UTC, MusaidAli commented on minion/minion-syslog/listener/pom.xml
> +            <Import-Package>!io.netty.buffer,
removed ,not needed.

2024-03-27 09:18 UTC, MusaidAli commented on minion/minion-syslog/listener/pom.xml
> +      <artifactId>camel-core</artifactId>
resolved added ${camel.version}

2024-03-27 09:19 UTC, MusaidAli commented on minion/minion-syslog/listener/pom.xml
> +      <artifactId>camel-netty</artifactId>
resolved .added ${camel.version}

2024-03-27 09:28 UTC, MusaidAli commented on minion/minion-syslog/listener/pom.xml
> +            <Import-Package>!io.netty.buffer,
YES ,we need it without this while adding   <bundle>mvn:org.opennms.lokahi.minion/syslog-listener/${project.version}</bundle> in feature giving error.

2024-03-27 09:33 UTC, MusaidAli commented on minion/minion-syslog/listener/pom.xml
> +            <Import-Package>!io.netty.buffer,
will try to resolve without this import package.

2024-03-27 10:22 UTC, MusaidAli commented
> Were you able to validate that this listener can receive syslogs ?

yes ,when we start receiver with Thread.sleep(Long.MAX_VALUE); and send udp packets .it is receiving

2024-03-27 15:43 UTC, MusaidAli commented on minion/minion-syslog/listener/pom.xml
> +            <Import-Package>!io.netty.buffer,
resolved,please check lattest comment.

2024-03-27 16:06 UTC, cgorantla commented
> > Were you able to validate that this listener can receive syslogs ?
> 
> yes ,when we start receiver with Thread.sleep(Long.MAX_VALUE); and send udp packets .it is receiving

we should get it running without Thread.sleep

2024-03-27 16:09 UTC, cgorantla reviewed
Make sure the feature is installed and listener running and it can capture syslogs and log them.

2024-03-27 16:09 UTC, cgorantla commented on minion/minion-syslog/listener/pom.xml
> +      <groupId>javax.xml.bind</groupId>
Should be moved to jakarta xml ?

2024-03-27 16:09 UTC, cgorantla commented on minion/minion-syslog/listener/pom.xml
> +      <version>0.1.0-SNAPSHOT</version>
you should be able to use project version

2024-03-27 16:09 UTC, cgorantla commented on minion/minion-features/src/main/feature/feature.xml
>      <feature name="minion-ng">
you need to add `minion-syslog` feature to get it running on Minion

2024-03-27 16:09 UTC, cgorantla commented on minion/minion-syslog/listener/pom.xml
> +    </dependency>
You still need `maven-bundle-plugin` without the  Import package

2024-03-27 16:15 UTC, MusaidAli commented on minion/minion-features/src/main/feature/feature.xml
>      <feature name="minion-ng">
minion-syslog                                │ 0.1.0.SNAPSHOT   │ x        │ Started     │ minion-syslog-0.1.0-SNAPSHOT           │
running in karaf ./runInplace, will update minion feature.

2024-03-27 16:59 UTC, MusaidAli commented
> > > Were you able to validate that this listener can receive syslogs ?
> > 
> > 
> > yes ,when we start receiver with Thread.sleep(Long.MAX_VALUE); and send udp packets .it is receiving
> 
> we should get it running without Thread.sleep

yes that for testing only.

2024-03-27 17:00 UTC, MusaidAli commented on minion/minion-syslog/listener/pom.xml
> +    </dependency>
please explain,didn't get the point.

2024-03-27 17:01 UTC, MusaidAli commented on minion/minion-syslog/listener/pom.xml
> +      <groupId>javax.xml.bind</groupId>
I think i will remove this ,this is not being used.

2024-03-27 17:02 UTC, MusaidAli commented on minion/minion-syslog/listener/pom.xml
> +      <groupId>javax.xml.bind</groupId>
should i removed this javax.xml.bind ?

2024-03-27 17:14 UTC, cgorantla commented on minion/minion-syslog/listener/pom.xml
> +    </dependency>
Ignore, it's not needed

2024-03-27 17:14 UTC, cgorantla commented on minion/minion-syslog/listener/pom.xml
> +      <groupId>javax.xml.bind</groupId>
if it's not used, remove

2024-03-27 17:15 UTC, MusaidAli commented on minion/minion-syslog/listener/pom.xml
> +    </dependency>
ok,Thanks

2024-04-12 15:53 UTC, cgorantla reviewed
Please fix Minion build failures

2024-04-15 11:28 UTC, MusaidAli commented
> Please fix Minion build failures

it is fixed.

2024-04-16 10:41 UTC, naeem-afzal reviewed
By providing clear and concise comments, we can streamline collaboration, promote code readability, and facilitate knowledge transfer among team members. Let's ensure that our comments are informative, up-to-date, and in line with best practices to maximize their effectiveness.

2024-04-16 10:41 UTC, naeem-afzal commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +        from("netty:udp://0.0.0.0:20514?sync=false&allowDefaultCodec=false&disconnectOnNoReply=false&receiveBufferSize="
Consider loading configuration values dynamically from configurations rather than hard coding them directly into the code. This approach enhances maintainability and flexibility, allowing for easier adjustments and updates without modifying the code base.

2024-04-16 10:41 UTC, naeem-afzal commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                        LOG.info("method1");
Kindly use log.debug instead of log.info for debug messages at all places

2024-04-17 08:31 UTC, MusaidAli commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +        from("netty:udp://0.0.0.0:20514?sync=false&allowDefaultCodec=false&disconnectOnNoReply=false&receiveBufferSize="
resolved.

2024-04-22 21:02 UTC, cgorantla commented
Also merge develop to your branch

2024-04-22 21:17 UTC, cgorantla reviewed
I validated this and don't see that route started by default.

2024-04-23 09:12 UTC, MusaidAli commented on minion/minion-syslog/listener/pom.xml
> +      <version>0.1.0-SNAPSHOT</version>
This is not updating now ,giving parent.relative path error .

2024-04-23 09:12 UTC, MusaidAli commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                    LOG.info("method3");
removed.

2024-04-23 09:12 UTC, MusaidAli commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                    LOG.info("02");
removed .

2024-04-23 09:13 UTC, MusaidAli commented on minion/minion-syslog/listener/src/main/resources/syslogMessage.txt
> +<34>1 2023-04-12T15:42:21.123Z mymachine.example.com evntslog - ID47 - An application event log entry...
removed ,parser will be added in next .

2024-04-23 09:13 UTC, MusaidAli commented
> Also merge develop to your branch

merged develop.

2024-04-23 09:14 UTC, MusaidAli commented
> I validated this and don't see that route started by default.

please check now .route will be starting .

2024-04-23 09:14 UTC, MusaidAli commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/parser/SyslogSeverity.java
> +
parser will be used next .

2024-04-23 09:15 UTC, MusaidAli commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/java/org/opennms/horizon/shared/grpc/syslog/contract/mapper/impl/TenantLocationSpecificSyslogDTOMapperImpl.java
> +package org.opennms.horizon.shared.grpc.syslog.contract.mapper.impl;
removed.

2024-04-23 11:58 UTC, MusaidAli commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/java/org/opennms/horizon/shared/grpc/syslog/contract/mapper/TenantLocationSpecificSyslogTOMapper.java
> +package org.opennms.horizon.shared.grpc.syslog.contract.mapper;
removed.

2024-04-24 14:41 UTC, smunir-onms approved these changes
LGTM, last comments from @cgorantla incorporated

2024-04-24 14:46 UTC, MusaidAli commented on minion/minion-syslog/listener/pom.xml
> +      <version>0.1.0-SNAPSHOT</version>
This is not updating now ,giving parent.relative path error .

2024-04-24 14:49 UTC, MusaidAli commented on minion/minion-syslog/features/src/main/feature/feature.xml
> +        <bundle>mvn:org.opennms.lokahi.minion/syslog-listener/${project.version}</bundle>
resolved.

2024-04-26 11:15 UTC, fooker approved these changes

2024-04-26 11:54 UTC, merged