LOK-2360: Thread model for monitor execution
OpenNMS-Cloud/lokahi pull request #1740
Opened 2024-03-21 16:06 UTC by Mohammad-Junid

## Description
Current monitor execution is undefined and current implementation is unclear. Current API uses futures to delegate problem to implementation.

Implement a thread pool to be shared by all monitors and use this threadpool to execute the monitoring. Therefore alter the monitor interface to not return a future.

Implement a separate thread pool used to process and hand-off monitor results from minion to gateway.

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2360

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-03-21 16:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1740) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1740) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenNMS-Cloud/lokahi?pullRequest=1740) it.</sub>

2024-03-22 11:19 UTC, smunir-onms commented on minion/plugins/icmp-plugin/src/test/java/org/opennms/horizon/minion/icmp/IcmpMonitorTest.java
> +        ;
remove extra ;

2024-03-22 11:32 UTC, smunir-onms commented on minion/plugins/azure-plugin/src/main/java/org/opennms/horizon/minion/azure/AzureMonitor.java
> +    public ServiceMonitorResponse poll(MonitoredService svc, Any config) {
proper naming: replace svc with monitoredService
ServiceMonitorResponse poll(MonitoredService monitoredService, Any config)

2024-03-22 11:35 UTC, smunir-onms commented on minion/plugins/icmp-plugin/src/main/java/org/opennms/horizon/minion/icmp/IcmpMonitor.java
> +    public ServiceMonitorResponse poll(MonitoredService svc, Any config) {
rename svc to monitoredService

2024-03-22 11:37 UTC, smunir-onms commented on minion/plugins/icmp-plugin/src/test/java/org/opennms/horizon/minion/icmp/IcmpMonitorTest.java
> +        ;
remove extra semicolon

2024-03-22 11:38 UTC, smunir-onms commented on minion/plugins/plugins-api/src/main/java/org/opennms/horizon/minion/plugin/api/ServiceMonitor.java
> +    public ServiceMonitorResponse poll(MonitoredService svc, Any config);
rename svc to monitoredService

2024-03-22 11:38 UTC, smunir-onms commented on minion/plugins/snmp-plugin/src/main/java/org/opennms/horizon/minion/snmp/SnmpMonitor.java
> +    public ServiceMonitorResponse poll(MonitoredService svc, Any config) {
rename svc to monitoredService

2024-03-22 14:06 UTC, Mohammad-Junid commented on minion/plugins/icmp-plugin/src/test/java/org/opennms/horizon/minion/icmp/IcmpMonitorTest.java
> +        ;
Done

2024-03-22 14:06 UTC, Mohammad-Junid commented on minion/plugins/azure-plugin/src/main/java/org/opennms/horizon/minion/azure/AzureMonitor.java
> +    public ServiceMonitorResponse poll(MonitoredService svc, Any config) {
Done

2024-03-22 14:07 UTC, Mohammad-Junid commented on minion/plugins/icmp-plugin/src/main/java/org/opennms/horizon/minion/icmp/IcmpMonitor.java
> +    public ServiceMonitorResponse poll(MonitoredService svc, Any config) {
Done

2024-03-22 14:07 UTC, Mohammad-Junid commented on minion/plugins/icmp-plugin/src/test/java/org/opennms/horizon/minion/icmp/IcmpMonitorTest.java
> +        ;
Done

2024-03-22 14:07 UTC, Mohammad-Junid commented on minion/plugins/plugins-api/src/main/java/org/opennms/horizon/minion/plugin/api/ServiceMonitor.java
> +    public ServiceMonitorResponse poll(MonitoredService svc, Any config);
Done

2024-03-22 14:07 UTC, Mohammad-Junid commented on minion/plugins/snmp-plugin/src/main/java/org/opennms/horizon/minion/snmp/SnmpMonitor.java
> +    public ServiceMonitorResponse poll(MonitoredService svc, Any config) {
Done

2024-03-22 16:47 UTC, smunir-onms commented on minion/plugins/icmp-plugin/src/main/java/org/opennms/horizon/minion/icmp/IcmpMonitor.java
> +import org.opennms.horizon.minion.plugin.api.*;
please use single imports instead of wildcards

2024-03-22 19:00 UTC, cgorantla reviewed
Keep the CompletableFuture  for now, Just add a thread pool for handling the results

2024-03-22 19:00 UTC, cgorantla commented on minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutorLocalMonitorServiceImpl.java
> +        this.executor = Executors.newFixedThreadPool(POOL_SIZE);
This can be cached threadpool

2024-03-22 19:00 UTC, cgorantla commented on minion/plugins/icmp-plugin/src/main/java/org/opennms/horizon/minion/icmp/IcmpMonitor.java
> +        return responseHolder.get();
when you send this result back, `handleExecutionComplete` will immediately get a null value.

2024-03-26 09:42 UTC, fooker commented
@Mohammad-Junid please respect PR title schema of `LOK-xxxx: A short description`

2024-03-26 09:59 UTC, fooker requested changes
This issue is about changing the signature of the `ServiceMonitor::poll` method, not radically remove `CompletableFuture`. Please make sure to understand which threads execute what part of the code and which parts are maybe blocking other threads.

2024-03-26 09:59 UTC, fooker commented on minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutorLocalMonitorServiceImpl.java
> +                submitExecutor(monitoredService, taskDefinition);
You should use `CompletableFuture::supplyAsync` to just execute `ServiceMonitor::poll` using the executor. This will give you an `CompletionStage` that you can use for further processing and most of the code could stay the same.

2024-03-26 09:59 UTC, fooker commented on minion/plugins/icmp-plugin/src/main/java/org/opennms/horizon/minion/icmp/IcmpMonitor.java
> -    public CompletableFuture<ServiceMonitorResponse> poll(MonitoredService svc, Any config) {
Not sure why the `Pinger` has such a strange interface, but using a `CompletableFuture` seems to be a good fit here.

2024-03-26 09:59 UTC, fooker commented on minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutorLocalMonitorServiceImpl.java
> +        resultProcessor.queueSendResult(taskDefinition.getId(), serviceMonitorResponse);
Please verify that this will not block, or if it does, is executed in the thread pool.

2024-03-26 16:24 UTC, Mohammad-Junid commented on minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutorLocalMonitorServiceImpl.java
> +        this.executor = Executors.newFixedThreadPool(POOL_SIZE);
Done

2024-03-26 16:25 UTC, Mohammad-Junid commented on minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutorLocalMonitorServiceImpl.java
> +                submitExecutor(monitoredService, taskDefinition);
Done

2024-03-26 16:26 UTC, Mohammad-Junid commented on minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutorLocalMonitorServiceImpl.java
> +        resultProcessor.queueSendResult(taskDefinition.getId(), serviceMonitorResponse);
add the previously existing code and working fine

2024-03-26 16:29 UTC, Mohammad-Junid commented on minion/plugins/icmp-plugin/src/main/java/org/opennms/horizon/minion/icmp/IcmpMonitor.java
> +        return responseHolder.get();
Did the needed changes

2024-03-27 16:18 UTC, cgorantla reviewed
As discussed today, please keep CompletableFuture and only handle results in separate thread pool.

2024-03-27 18:10 UTC, closed without merging

2024-03-27 18:10 UTC, Mohammad-Junid commented
creating another PR with clear and minimum changes