LOK-1863 Event Service: Add Service level test cases
OpenNMS-Cloud/lokahi pull request #1741
Opened 2024-03-21 19:53 UTC by jahanzebdataq

## Description
vent Service is missing service level test CucumberIT

we should cover

Trap being sent → Event being persisted

Trap being sent for known node → Event having node info

Trap being sent for unknown node → New suspect event being sent

Receiving external events, internal events → Events being persisted

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-1863

2024-04-01 19:59 UTC, cgorantla commented on events/docker-it/src/test/java/org/opennms/horizon/events/CucumberRunnerIT.java
> +                .withEnv("EVENT_ENCRYPTION_KEY", RandomStringUtils.randomAlphanumeric(32))
don't need this env `"EVENT_ENCRYPTION_KEY`

2024-04-01 19:59 UTC, cgorantla commented on events/docker-it/pom.xml
> +    <dependency>
where are you using this ?

2024-04-01 19:59 UTC, cgorantla commented on events/docker-it/src/test/java/org/opennms/horizon/events/stepdefs/EventStepDefinitions.java
> +                                        .anyMatch(event -> event.getTenantId().equals(this.tenantId)),
It's better to check if it produces specific event with uei, not just tenantId

2024-04-01 19:59 UTC, cgorantla commented on events/docker-it/src/test/resources/org/opennms/horizon/events/event.feature
> +    When Send Trap Data to Kafka Listener via Producer with TenantId "event-tenant-stream" and Location "1"
Location with some name will be meaningful

2024-04-02 11:06 UTC, jahanzebdataq commented on events/docker-it/src/test/resources/org/opennms/horizon/events/event.feature
> +    When Send Trap Data to Kafka Listener via Producer with TenantId "event-tenant-stream" and Location "1"
If we give name here, then we have to find out location id through location name, for which we have to use MonitoringLocationServiceGrpc from inventory service

2024-04-02 11:11 UTC, jahanzebdataq commented on events/docker-it/src/test/java/org/opennms/horizon/events/stepdefs/EventStepDefinitions.java
> +                                        .anyMatch(event -> event.getTenantId().equals(this.tenantId)),
What is uei? and how do we get and store it in our class to be checked against it?

2024-04-02 11:11 UTC, jahanzebdataq commented on events/docker-it/src/test/java/org/opennms/horizon/events/CucumberRunnerIT.java
> +                .withEnv("EVENT_ENCRYPTION_KEY", RandomStringUtils.randomAlphanumeric(32))
Resolved

2024-04-02 11:12 UTC, jahanzebdataq commented on events/docker-it/pom.xml
> +    <dependency>
Removed this dependency

2024-04-02 12:07 UTC, jahanzebdataq commented on events/docker-it/src/test/java/org/opennms/horizon/events/stepdefs/EventStepDefinitions.java
> +                                        .anyMatch(event -> event.getTenantId().equals(this.tenantId)),
Added a uei check

2024-04-08 18:54 UTC, cgorantla commented on events/docker-it/src/test/java/org/opennms/horizon/events/stepdefs/EventStepDefinitions.java
> +                                .setAgentAddress("127.0.0.1")
Not sure how does it produce an event with uei `uei.opennms.org/generic/traps/SNMP_Cold_Start` when you don't have any relevant Trap in TrapDTO, Can you re-check this ?

2024-04-18 02:57 UTC, cgorantla commented
This is consistently failing at my end.

2024-04-18 11:45 UTC, jahanzebdataq commented
> This is consistently failing at my end.

Can you show me the error so we can see why it is failing at your end, even though it ran perfectly here

2024-05-03 06:01 UTC, cgorantla reviewed
This doesn't seems to work.
None of the trap are received on Event Service.

Please debug using remote debug by enabling debug port

2024-05-06 12:41 UTC, jahanzebdataq commented
> This doesn't seems to work. None of the trap are received on Event Service.
> 
> Please debug using remote debug by enabling debug port

I have tested it on my local machine, also changed the parameters of trap being sent to trap listener, after getting back event list, we get the event with same parameters. Please view the video. Also I committed these changes and all check in the PR were passed and it executed related cucumber tests.
[Screencast Event Service Trap to event test.webm](https://github.com/OpenNMS-Cloud/lokahi/assets/159922670/de6fe5e9-339b-4606-9550-a53748568edf)

2024-05-07 18:10 UTC, jahanzebdataq commented
> This doesn't seems to work. None of the trap are received on Event Service.
> 
> Please debug using remote debug by enabling debug port

I was not able to debug and find out whether trap was being sent and persisted or not, I added the logs in event consumer as you can see in the images below, upon executing the code you can see the logs of events being sent by trap consumer and persisted by event consumer.
![Screenshot from 2024-05-07 22-58-14](https://github.com/OpenNMS-Cloud/lokahi/assets/159922670/bc81b049-4fdd-4186-9f75-7314173df75f)
![Screenshot from 2024-05-07 23-02-57](https://github.com/OpenNMS-Cloud/lokahi/assets/159922670/9c03d78f-42af-4e9b-a6c5-0ac555c56e05)
![Screenshot from 2024-05-07 23-08-07](https://github.com/OpenNMS-Cloud/lokahi/assets/159922670/3059a70e-484d-49b1-8975-4225031ef690)

2024-05-08 12:47 UTC, fooker requested changes

2024-05-08 12:47 UTC, fooker commented on events/consumer/src/main/java/org/opennms/horizon/events/consumer/EventsConsumer.java
> +            LOG.info("Received events from kafka {}", eventLog);
Why both?

2024-05-08 12:47 UTC, fooker commented on events/docker-it/src/test/java/org/opennms/horizon/events/CucumberRunnerIT.java
> +                true); // DEBUGGING - set to true to expose the application debugging on host port 5005
Please revert

2024-05-08 18:11 UTC, jahanzebdataq commented on events/consumer/src/main/java/org/opennms/horizon/events/consumer/EventsConsumer.java
> +            LOG.info("Received events from kafka {}", eventLog);
Removed

2024-05-15 12:21 UTC, fooker approved these changes

2024-05-16 12:56 UTC, merged