LOK-2361 : Add a http-plugin in minion/plugins module. Also add http.…
OpenNMS-Cloud/lokahi pull request #1755
Opened 2024-03-27 17:14 UTC by aurang-zeb313

…proto file for http plugin.

## Description
Build a HTTP service monitor and register it in minion.
Proto file for http plugin.

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2361

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-03-27 17:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1755) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1755) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenNMS-Cloud/lokahi?pullRequest=1755) it.</sub>

2024-03-28 12:09 UTC, fooker requested changes
The proto is okay, now. `verbose` can be removed

2024-03-28 12:09 UTC, fooker commented on minion/plugins/pom.xml
> +      <module>http-plugin</module>
Formating

2024-03-28 12:09 UTC, fooker commented on shared-lib/protobuf/src/main/proto/http.proto
> +  bool verbose = 12;
I think we can skip these - a old debugging artifact.

2024-03-29 10:59 UTC, smunir-onms commented on minion/plugins/http-plugin/pom.xml
> +                                <feature>icmp*</feature>
I think it should be <feature>http*</feature>

2024-04-05 13:08 UTC, aurang-zeb313 commented
> The proto is okay, now. `verbose` can be removed
Done

2024-04-08 10:42 UTC, kashifsardar181 approved these changes

2024-04-09 14:56 UTC, aurang-zeb313 commented
![Screenshot from 2024-04-08 21-32-09](https://github.com/OpenNMS-Cloud/lokahi/assets/159940154/77607c0e-2f26-428e-9170-bde193d16c79)
![Screenshot from 2024-04-08 21-31-10](https://github.com/OpenNMS-Cloud/lokahi/assets/159940154/a3c686ed-c093-41e3-8bf6-8a61d65bac44)

2024-04-12 15:51 UTC, cgorantla reviewed
Please fix minion build failure

2024-04-15 12:33 UTC, aurang-zeb313 commented
> Please fix minion build failure

Build issue resolved.

2024-04-15 15:48 UTC, aurang-zeb313 commented on shared-lib/lokahi-common-utils/src/main/java/org/opennms/horizon/shared/utils/Base64.java
> +public final class Base64 {
Base64 is used to encode userName and password in httpMonitor

2024-04-15 17:57 UTC, aurang-zeb313 commented on minion/plugins/http-plugin/pom.xml
> +    <dependency>
Yes, it is needed for test cases.

2024-04-15 17:58 UTC, aurang-zeb313 commented on minion/plugins/http-plugin/src/main/feature/feature.xml
> +        <bundle dependency="true">mvn:org.opennms.lib/org.opennms.lib.tracker/0.7</bundle>
I need only grpc-contract

2024-04-15 17:58 UTC, aurang-zeb313 commented on minion/plugins/http-plugin/src/main/java/org/opennms/horizon/minion/http/HttpMonitor.java
> +                e.fillInStackTrace();
Removed.

2024-04-15 17:59 UTC, aurang-zeb313 commented on minion/plugins/http-plugin/src/main/java/org/opennms/horizon/minion/http/HttpMonitor.java
> +                HttpMonitor.LOG.warn("Error closing socket connection", e);
Done

2024-04-15 17:59 UTC, aurang-zeb313 commented on minion/plugins/http-plugin/src/main/java/org/opennms/horizon/minion/http/HttpMonitor.java
> +                    HttpMonitor.LOG.info(
Done

2024-04-23 02:58 UTC, cgorantla reviewed
I think we should be able to resolve just with url for any http service. We may not need ipaddress/hostname here. Since this was derived from OpenNMS Classic, we still have this code. we can improve upon this in next PR.

2024-04-29 16:23 UTC, merged