Implement Thread Model for Monitor Execution
OpenNMS-Cloud/lokahi pull request #1756
Opened 2024-03-27 18:30 UTC by Mohammad-Junid

## Description
Current monitor execution is undefined and current implementation is unclear. Current API uses futures to delegate problem to implementation.

Implement a thread pool to be shared by all monitors and use this threadpool to execute the monitoring. Therefore alter the monitor interface to not return a future.

Implement a separate thread pool used to process and hand-off monitor results from minion to gateway.

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2360

2024-03-27 18:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1756) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1756) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenNMS-Cloud/lokahi?pullRequest=1756) it.</sub>

2024-03-28 12:22 UTC, fooker requested changes

2024-03-28 12:22 UTC, fooker commented on minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutorLocalMonitorServiceImpl.java
> +                        executor);
I don't think this is sufficient for thread management here.

2024-03-28 12:23 UTC, fooker commented on minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutorLocalMonitorServiceImpl.java
> +                        executor);
I would expect a method returning a `Future` not to block for a long time as part of the contract (similar how methods returning `Optional` should never return `null`). This rises the question on how we do this in blocking impls. We can not have a thread pool per monitor.

I see how this looks counter-intuitive for async monitor impls like the ICMP monitor. But this impl can just block on the future filled in the callback which will just park the task thread.

Outside of the API, almost everything can stay the same but just the call to `poll` has to be wrapped by the thread pool which will transform the blocking method into a `CompletionStage` and we can do the hand-off in the already existing async way.

2024-04-01 18:11 UTC, Mohammad-Junid commented on minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutorLocalMonitorServiceImpl.java
> +                        executor);
Done

2024-04-01 19:53 UTC, cgorantla requested changes

2024-04-01 19:53 UTC, cgorantla commented on minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutorLocalMonitorServiceImpl.java
> +                                return monitor.poll(monitoredService, taskDefinition.getConfiguration())
you can simply use `future.whenCompleteAsync` instead of wrapping in another `CompletableFuture.supplyAsync`

2024-04-02 17:30 UTC, Mohammad-Junid commented on minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutorLocalMonitorServiceImpl.java
> +                                return monitor.poll(monitoredService, taskDefinition.getConfiguration())
Done

2024-04-02 17:33 UTC, kashifsardar181 commented on minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutorLocalMonitorServiceImpl.java
Its look good based on previous review suggestion

2024-04-02 19:42 UTC, cgorantla commented on minion/plugins/icmp-plugin/src/test/java/org/opennms/horizon/minion/icmp/IcmpMonitorTest.java
> +        future.whenCompleteAsync(
Not sure why we have the tests in async mode. Tests will always pass since the execution will be sequential here.

2024-04-03 11:01 UTC, Mohammad-Junid commented on minion/plugins/icmp-plugin/src/test/java/org/opennms/horizon/minion/icmp/IcmpMonitorTest.java
> +        future.whenCompleteAsync(
we  have discussed in team by removing async then there is no need of this test case as its already exists "**testError**".

2024-04-04 14:25 UTC, cgorantla commented on minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutorLocalMonitorServiceImpl.java
> +        this.executor = Executors.newCachedThreadPool(new ThreadFactoryBuilder()
Since `TaskExecutorLocalMonitorServiceImpl` is only invoked when a new task is created, this executor should be moved to `TaskExecutorLocalServiceFactoryImpl` and also handle executor shutdown

2024-04-04 17:23 UTC, Mohammad-Junid commented on minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutorLocalMonitorServiceImpl.java
> +        this.executor = Executors.newCachedThreadPool(new ThreadFactoryBuilder()
The executor moved to  TaskExecutorLocalServiceFactoryImpl

2024-04-08 12:49 UTC, cgorantla commented on minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutorLocalServiceFactoryImpl.java
> +                        // Create the service instance
Just pass the executor to `TaskExecutorLocalMonitorServiceImpl` , and keep whatever you had previously in [/TaskExecutorLocalMonitorServiceImpl.java](https://github.com/OpenNMS-Cloud/lokahi/pull/1756/files#diff-94787fcc9391d92e961a5070e1d378b7f3ec5cff44dc7d947f8dbd47efb491ef)

2024-04-08 16:28 UTC, Mohammad-Junid commented on minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutorLocalServiceFactoryImpl.java
> +                        // Create the service instance
The changes are done

2024-04-08 18:45 UTC, cgorantla approved these changes
LGTM!

2024-04-09 14:19 UTC, fooker approved these changes

2024-04-15 09:29 UTC, merged