LOK-2359:Refine Interface for service monitors.
OpenNMS-Cloud/lokahi pull request #1758
Opened 2024-03-28 16:25 UTC by kashifsardar181

## Description
LOK-2359
Refine interface classes all service monitors should implement on minion.
Check what is currently used and remove everything that is not used right now.
Things that we know of:
Device Config
Actual Location
LOK-2370
MonitoredService class is used in API but not filled correctly mostly. Remove the class and use the provided monitor specific config where needed. If required, extend the config with needed values.

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2359
- https://opennms.atlassian.net/browse/LOK-2370

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-03-28 16:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1758) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1758) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenNMS-Cloud/lokahi?pullRequest=1758) it.</sub>

2024-03-29 09:26 UTC, smunir-onms reviewed
LGTM

2024-04-01 19:50 UTC, cgorantla requested changes

2024-04-01 19:50 UTC, cgorantla commented on minion/plugins/snmp-plugin/src/main/java/org/opennms/horizon/minion/snmp/SnmpMonitor.java
> -                    .nodeId(svc.getNodeId())
why are we removing these ?

2024-04-01 19:50 UTC, cgorantla commented on minion/plugins/snmp-plugin/src/main/java/org/opennms/horizon/minion/snmp/SnmpMonitor.java
> -    private SnmpAgentConfig mapAgentConfig(SnmpMonitorRequest snmpMonitorRequest) {
Is this not used anywhere ?

2024-04-01 19:50 UTC, cgorantla commented on shared-lib/protobuf/src/main/proto/snmp.proto
> +  int64 nodeId = 7;
where are we assigning these values ?

2024-04-02 10:24 UTC, kashifsardar181 commented on minion/plugins/snmp-plugin/src/main/java/org/opennms/horizon/minion/snmp/SnmpMonitor.java
> -    private SnmpAgentConfig mapAgentConfig(SnmpMonitorRequest snmpMonitorRequest) {
Yes its not used any where

2024-04-02 12:29 UTC, kashifsardar181 commented on minion/plugins/snmp-plugin/src/main/java/org/opennms/horizon/minion/snmp/SnmpMonitor.java
> -                    .nodeId(svc.getNodeId())
In case of exception nodeId and monitorServiceId are added

2024-04-02 12:32 UTC, kashifsardar181 reviewed
Fixes are done based on the previous review comments

2024-04-03 10:14 UTC, kashifsardar181 reviewed
Review changes are done

2024-04-04 13:56 UTC, cgorantla commented on minion/plugins/snmp-plugin/src/main/java/org/opennms/horizon/minion/snmp/SnmpMonitor.java
> +            snmpMonitorRequest = config.unpack(SnmpMonitorRequest.class);
```suggestion
final SnmpMonitorRequest snmpMonitorRequest = config.unpack(SnmpMonitorRequest.class);
```
then you don't need another final SnmpMonitorRequest finalSnmpMonitorRequest

2024-04-04 13:56 UTC, cgorantla commented on shared-lib/protobuf/src/main/proto/icmp.proto
> +  int64 nodeId = 7;
Instead of adding these two here directly, It would be better to add another message with

message ServiceInventory {
int64 nodeId = 1;
int64 monitorServiceId = 2;
}

and add this new message to the request.

2024-04-04 13:56 UTC, cgorantla commented on minion/plugins/azure-plugin/src/main/java/org/opennms/horizon/minion/azure/AzureMonitor.java
> +                        .nodeId(request.getNodeId())
I don't see relevant changes for AzureMonitor in Inventory

2024-04-04 13:57 UTC, cgorantla reviewed
Also please validate ICMP/SNMP in UI with graphs properly populated with metrics.

2024-04-04 14:10 UTC, kashifsardar181 commented on minion/plugins/snmp-plugin/src/main/java/org/opennms/horizon/minion/snmp/SnmpMonitor.java
> +            snmpMonitorRequest = config.unpack(SnmpMonitorRequest.class);
then snmpMonitorRequest is out of scope in exception block

2024-04-08 18:11 UTC, kashifsardar181 commented
> Also please validate ICMP/SNMP in UI with graphs properly populated with metrics.
Validated and shared the video with you on [Mattermost](https://chat.opennms.com/files/43671tzghirptx7k1yo7cdkrqo/public?h=WAk4taxL9vA_dpRC_3W6uEbhosZLGkkrbn14anJIMsw)

2024-04-08 18:12 UTC, kashifsardar181 commented on shared-lib/protobuf/src/main/proto/icmp.proto
> +  int64 nodeId = 7;
Added as suggested

2024-04-08 19:03 UTC, cgorantla reviewed
Please check comments on SnmpMonitor and related to AzureMonitor and resolve them

2024-04-22 18:37 UTC, cgorantla reviewed
It is still missing changes for Azure monitor

2024-04-22 18:37 UTC, cgorantla commented on shared-lib/protobuf/src/main/proto/common.proto
> +option java_package = "org.opennms.common";
why are we changing this java package ?

2024-04-22 18:37 UTC, cgorantla commented on minion/plugins/snmp-plugin/src/main/java/org/opennms/horizon/minion/snmp/SnmpMonitor.java
> +            snmpMonitorRequest = config.unpack(SnmpMonitorRequest.class);
you don't need to initialize with null at the start

2024-04-22 18:37 UTC, cgorantla commented on minion/plugins/snmp-plugin/src/main/java/org/opennms/horizon/minion/snmp/SnmpMonitor.java
> +            final SnmpMonitorRequest finalSnmpMonitorRequest = snmpMonitorRequest; // Final reference for inside lambda
can be removed if we can avoid null assignment for snmpMonitorRequest

2024-04-24 16:31 UTC, smunir-onms commented on minion/plugins/azure-plugin/src/main/java/org/opennms/horizon/minion/azure/AzureMonitor.java
> +                        .nodeId(request.getNodeId())
I found just this reference, was updated accordingly, can you please help me locate another. Thank you.
![image](https://github.com/OpenNMS-Cloud/lokahi/assets/157733753/230b9806-48d0-485d-874e-29420bc66f3f)

2024-04-24 16:32 UTC, smunir-onms commented on minion/plugins/snmp-plugin/src/main/java/org/opennms/horizon/minion/snmp/SnmpMonitor.java
> +            snmpMonitorRequest = config.unpack(SnmpMonitorRequest.class);
Discussed

2024-04-24 16:33 UTC, smunir-onms commented on shared-lib/protobuf/src/main/proto/common.proto
> +option java_package = "org.opennms.common";
package renamed as discussed.

2024-04-24 17:06 UTC, smunir-onms commented on shared-lib/protobuf/src/main/proto/inventoryCommon.proto
> +  int64 node_id = 1;
Agreed!

2024-04-25 13:29 UTC, smunir-onms commented on shared-lib/protobuf/src/main/proto/inventoryCommon.proto
> +  int64 node_id = 1;
Updated

2024-04-25 13:30 UTC, smunir-onms commented on minion/plugins/snmp-plugin/src/main/java/org/opennms/horizon/minion/snmp/SnmpMonitor.java
> +            final SnmpMonitorRequest finalSnmpMonitorRequest = snmpMonitorRequest; // Final reference for inside lambda
Discussed

2024-04-26 13:31 UTC, smunir-onms commented on shared-lib/protobuf/src/main/proto/common.proto
> +option java_package = "org.opennms.common";
types.proto reverted

2024-04-29 18:18 UTC, cgorantla approved these changes
Looks good. Please validate SNMP graphs and check that nothing is broken

2024-04-30 15:19 UTC, fooker approved these changes
Looks good to me

2024-05-03 03:23 UTC, cgorantla approved these changes
Validated, seems to work fine

2024-05-03 14:24 UTC, merged