FE: Monitoring Policies Edit Panel - initial
OpenNMS-Cloud/lokahi pull request #1766
Opened 2024-04-03 17:34 UTC by faizanjanjua

## Description
Create a components/MonitoringPoliciesEditPanel component, route will be /monitoring-policies-new/:id where id is a number, the database id of the policy. Note that this route must be after /monitoring-policies-new/create.

When a user is on the MonitoringPoliciesDetailPanel and clicks the Edit icon, they will route to this component.

For this ticket:

update route to use this component

ensure component is navigated-to from main table, but only after LOK-2380: FE: Monitoring Policies - Details panel, initial version - Bilal
DONE
is done. monitoringPolicies.selectedPolicy should be set

display status (cannot actually change it)

add Basic Information for name and description (memo field)

add section names (placeholders) for Tags, Notifications, Alert Rules, but don’t implement them

other sections will be added in separate tickets

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2420

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-04-03 21:02 UTC, synqotik requested changes
Overall looks good, mostly formatting changes and a few small code changes.

2024-04-03 21:02 UTC, synqotik commented on ui/src/components/MonitoringPolicies/MonitoringPolicyBasicInformationEditAddForm.vue
> +
Remove 2 blank lines, so just one blank line between `@use` and first class

2024-04-03 21:02 UTC, synqotik commented on ui/components.d.ts
> +
Remove blank line

2024-04-04 13:54 UTC, faizanjanjua commented on ui/src/components/MonitoringPolicies/MonitoringPoliciesDetailPanel.vue
> +  if (id != undefined) {
`
const onEdit = (id: number) => {  
  if (id) {
    router.push(`/monitoring-policies-new/${id}`)
  }
}`

changed as per your instructions

2024-04-04 13:55 UTC, faizanjanjua commented on ui/src/components/MonitoringPolicies/MonitoringPoliciesEditPanel.vue
> +const store = useMonitoringPoliciesStore()
chagned order to   imports, then functions, then watchEffect

2024-04-04 13:55 UTC, faizanjanjua commented on ui/src/components/MonitoringPolicies/MonitoringPoliciesEditPanel.vue
> +    populateForm(filteredPolicy as Policy)
watchEffect(() => {
  if (store.monitoringPolicies.length > 0 && route?.params?.id) {
    const filteredPolicy = store.monitoringPolicies.find((item: Policy) => item.id === Number(route.params.id))
    store.displayPolicyForm(filteredPolicy as Policy)
    }
})

2024-04-04 13:55 UTC, faizanjanjua commented on ui/src/components/MonitoringPolicies/MonitoringPoliciesEditPanel.vue
> +      <FeatherTabPanel>TWOTOOW</FeatherTabPanel>
Done

2024-04-04 14:20 UTC, synqotik approved these changes
LGTM

2024-04-04 15:16 UTC, merged