Encode interface specifics in SNMP Result Metrics as labels
OpenNMS-Cloud/lokahi pull request #1820
Opened 2024-04-24 13:04 UTC by aurang-zeb313

## Description
Search code for LOK-2404 and remove all marked named values from proto including all use-cases. 
Use labels as a replacement.

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2404

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-04-24 13:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1820) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1820) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenNMS-Cloud/lokahi?pullRequest=1820) it.</sub>

2024-04-24 14:54 UTC, smunir-onms commented on minion/plugins/snmp-plugin/src/main/java/org/opennms/horizon/minion/snmp/SnmpCollectionSet.java
> +                // .setIpAddress(ipAddress)
please remove commented code

2024-04-26 11:24 UTC, fooker requested changes
This seems to be quite similar to #1812.

2024-05-01 17:43 UTC, smunir-onms commented
> LGTM, needs to validate, I'll do it on my machine

validation recording attached;
[Screencast from 01-05-2024.webm](https://github.com/OpenNMS-Cloud/lokahi/assets/157733753/81df4b01-2425-4a7a-a709-b7700c28a330)

2024-05-03 18:04 UTC, smunir-onms reviewed
LGTM, needs to validate the changes.

2024-05-08 14:15 UTC, fooker approved these changes

2024-05-09 10:18 UTC, merged