LOK-2338:Added Syslog Parser
OpenNMS-Cloud/lokahi pull request #1825
Opened 2024-04-29 09:46 UTC by MusaidAli

## Description
Add Syslog parser in Minion

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2338

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-04-30 02:17 UTC, cgorantla requested changes

2024-04-30 02:17 UTC, cgorantla commented on minion/minion-syslog/listener/pom.xml
> +          <version>0.1.0-SNAPSHOT</version>
try to use project version

2024-04-30 02:17 UTC, cgorantla commented on shared-lib/protobuf/src/main/proto/syslog-config.proto
> +message SyslogConfig {
Don't assume that whatever works for TrapsConfig works for Syslog, Please try to understand syslog config from Classic

2024-04-30 02:17 UTC, cgorantla commented on minion/minion-syslog/listener/src/main/resources/OSGI-INF/blueprint/blueprint.xml
> +    <cm:property-placeholder id="syslogProperties"  persistent-id="org.opennms.horizon.minion.syslog.listener.syslog" update-strategy="reload">
we need to derive config from Inventory,  check how TrapConfig ( static for now) is send from Inventory service. see `TrapConfigService.java`

2024-04-30 11:33 UTC, MusaidAli commented on shared-lib/protobuf/src/main/proto/syslog-config.proto
> +message SyslogConfig {
removed snmpUser ,other configs added.

2024-04-30 11:34 UTC, MusaidAli commented on minion/minion-syslog/listener/src/main/resources/OSGI-INF/blueprint/blueprint.xml
> +    <cm:property-placeholder id="syslogProperties"  persistent-id="org.opennms.horizon.minion.syslog.listener.syslog" update-strategy="reload">
added task for syslog ,this should be seen in console like trap and flow config.currently not showing.any idea

2024-05-01 10:17 UTC, MusaidAli commented on minion/minion-syslog/listener/src/main/resources/OSGI-INF/blueprint/blueprint.xml
> +    <cm:property-placeholder id="syslogProperties"  persistent-id="org.opennms.horizon.minion.syslog.listener.syslog" update-strategy="reload">
It shows in inventory logs but not in minion console logs .

2024-05-03 10:18 UTC, MusaidAli commented on minion/minion-syslog/listener/src/main/resources/OSGI-INF/blueprint/blueprint.xml
> +    <cm:property-placeholder id="syslogProperties"  persistent-id="org.opennms.horizon.minion.syslog.listener.syslog" update-strategy="reload">
resolved.

2024-05-14 09:56 UTC, fooker commented
Has this PR been split up? It looks like it contains a lot of stuff similar to other PRs from you.

2024-05-24 13:05 UTC, smunir-onms commented
Covered under https://github.com/OpenNMS-Cloud/lokahi/pull/1887

2024-05-24 13:05 UTC, closed without merging