LOK : 2416 : Create a karaf command to execute a monitor from minion.
OpenNMS-Cloud/lokahi pull request #1826
Opened 2024-04-29 10:35 UTC by Junaid-Khan-Nant

## Description
- Add a karaf command which gets a service monitor name and a service config. This command executes the service monitor once and prints the result to screen. 
- Place this in minion/plugins/shell-commands and use MonitorRegistry to find the registered service monitor implementations.

## Jira link(s)
https://opennms.atlassian.net/browse/LOK-2416

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-04-30 15:48 UTC, fooker requested changes

2024-04-30 15:48 UTC, fooker commented on minion/plugins/shell-commands/src/main/java/org/opennms/horizon/minion/icmp/shell/MonitorsScanCommand.java
> +    private ServiceMonitor monitor;
Why is this a class field, not a variable?

2024-04-30 15:48 UTC, fooker commented on minion/plugins/shell-commands/src/main/java/org/opennms/horizon/minion/icmp/shell/MonitorCmdConstants.java
> +public interface MonitorCmdConstants {
Can we just use the name of the monitor to find the implementation from the `MonitorRegistry`. This would make new monitors work out of the box

2024-04-30 15:48 UTC, fooker commented on minion/plugins/shell-commands/src/main/java/org/opennms/horizon/minion/icmp/shell/MonitorsScanCommand.java
> +            description = "Ip address to be pinged",
Can you make this PR based on top of [LOK-2359](https://github.com/OpenNMS-Cloud/lokahi/pull/1758)? There we change the way addresses are handled.

2024-04-30 15:48 UTC, fooker commented on minion/plugins/shell-commands/src/main/java/org/opennms/horizon/minion/icmp/shell/MonitorsScanCommand.java
> +    String userAgent = "";
You need to find a way to generalize the config to be monitor implementation agnostic. Maybe we can just accept a json string.

2024-04-30 15:48 UTC, fooker commented on minion/plugins/shell-commands/src/main/java/org/opennms/horizon/minion/icmp/shell/MonitorsScanCommand.java
> +    public Object setUpMonitorRegistry() {
I don't understand the naming.

2024-04-30 15:48 UTC, fooker commented on minion/plugins/shell-commands/src/main/java/org/opennms/horizon/minion/icmp/shell/MonitorsScanCommand.java
> +        return response.toString();
This will NPE on failure

2024-04-30 15:48 UTC, fooker commented on minion/plugins/shell-commands/src/main/java/org/opennms/horizon/minion/icmp/shell/MonitorsScanCommand.java
> +                configuration = Any.pack(NTPMonitorRequest.newBuilder()
As mentioned above, this should be implementation agnostic somehow.

2024-04-30 15:48 UTC, fooker commented on minion/plugins/shell-commands/src/main/java/org/opennms/horizon/minion/icmp/shell/MonitorsScanCommand.java
> +        scannerManager = null;
Why is this a class field, not a local variable?

2024-05-02 19:25 UTC, fooker requested changes
Idea: Extend the `ServiceMonitorManager` interface with a getter returning the actual class expected in the configuration. The you could use this class to deserialize the json and call the monitor without actual knowledge about the monitor implementations.

2024-05-02 19:25 UTC, fooker commented on minion/plugins/shell-commands/src/main/java/org/opennms/horizon/minion/icmp/shell/MonitorsScanCommand.java
> +        switch (monitorName) {
Still, just pass `monitorName` into the `getService` call.

2024-05-08 18:05 UTC, smunir-onms commented
Please add unit tests

2024-05-08 18:19 UTC, smunir-onms commented on minion/plugins/plugins-api/src/main/java/org/opennms/horizon/minion/plugin/api/ServiceMonitorManager.java
> +public interface ServiceMonitorManager<T extends ServiceMonitor> {
this doesn't need "<T extends ServiceMonitor>" as per the current implementation

2024-05-13 14:14 UTC, fooker approved these changes

2024-05-13 16:19 UTC, merged