FE: Monitoring Policies: Bug when selectedPolicy is undefined
OpenNMS-Cloud/lokahi pull request #1834
Opened 2024-05-02 17:58 UTC by faizanjanjua

## Description
Description

In MonitoringPolicyBasicInformationEditAddForm and elsewhere, getting this error:

 

TypeError: Cannot read properties of undefined (reading 'name')
    at Proxy.<anonymous> (MonitoringPolicyBasicInformationEditAddForm-DU2WWxCH.js:1:824)
when trying to read store.selectedPolicy.name in v-model

Could be fixed by making sure monitoringPoliciesStore.selectedPolicy is always defined. But we will need a flag to note whether it's actually selected.

add isPolicySelected to store state

monitoringPolicyStore.clearSelectedPolicy should be as follows, and we need to update some cases where we check for store.selectedPolicy to instead check for store.isPolicySelected

clearSelectedPolicy() {
  this.selectedPolicy = cloneDeep(defaultPolicy)
  this.isPolicySelected = false
}
and and fix displayPolicyForm:

displayPolicyForm(policy?: Policy) {
  this.selectedPolicy = policy ? cloneDeep(policy) : cloneDeep(defaultPolicy)
  this.isPolicySelected = true
  this.selectedRule = undefined
}

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2469

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-05-02 19:17 UTC, synqotik requested changes
See comments.

When resetting the policy or rule, need to make a clone/copy of the default objects, otherwise those values will get changed.

Also I think we can just a simple object for `defaultRule`. The code from before makes API calls which is expensive and I don't it's needed. We will eventually remove that code when Legacy components are deleted.

2024-05-02 19:17 UTC, synqotik commented on ui/src/store/Views/monitoringPoliciesStore.ts
> +    selectedPolicy: defaultPolicy,
Change to `cloneDeep(defaultPolicy)`, we always want to make a clone of the `defaultPolicy`.

2024-05-02 19:17 UTC, synqotik commented on ui/src/store/Views/monitoringPoliciesStore.ts
> +      this.selectedRule = await getDefaultRule()
Add a `defaultRule` and then use `cloneDeep(defaultRule)` here.

Looks like we will probably get rid of `getDefaultRule()` and `getDefaultEventCondition()` eventually, they are only used in `Legacy` now.

```typescript
const defaultRule: PolicyRule = {
    id: 0,
    name: '',
    componentType: ManagedObjectType.Node,
    detectionMethod: DetectionMethod.Event,
    eventType: EventType.SnmpTrap,
    alertConditions: [],
    vendor: 'generic'
}

2024-05-02 19:17 UTC, synqotik commented on ui/src/store/Views/monitoringPoliciesStore.ts
> +      this.selectedRule = await getDefaultRule()
Change to `cloneDeep(defaultRule)`

2024-05-02 19:17 UTC, synqotik commented on ui/src/store/Views/monitoringPoliciesStore.ts
> +    async displayPolicyForm(policy?: Policy) {
Won't need `async` after below change.

2024-05-02 19:17 UTC, synqotik commented on ui/src/store/Views/monitoringPoliciesStore.ts
> +    async clearSelectedPolicy() {
Remove `async`, change line below to `this.selectedRule = cloneDeep(defaultRule)`

2024-05-02 19:17 UTC, synqotik commented on ui/src/store/Views/monitoringPoliciesStore.ts
> +      this.selectedPolicy = defaultPolicy
Should be `this.selectedPolicy = cloneDeep(defaultPolicy)`

2024-05-02 19:17 UTC, synqotik commented on ui/src/store/Views/monitoringPoliciesStore.ts
> +        this.selectedPolicy = defaultPolicy
Change to `this.selectedPolicy = cloneDeep(defaultPolicy)` and `this.selectedRule = cloneDeep(defaultRule)`

2024-05-02 19:17 UTC, synqotik commented on ui/src/store/Views/monitoringPoliciesStore.ts
> +      this.selectedRule = await getDefaultRule()
Same changes here.

2024-05-02 19:17 UTC, synqotik commented on ui/src/store/Views/monitoringPoliciesStore.ts
> -      this.selectedRule = undefined
Same changes as elsewhere

2024-05-02 19:17 UTC, synqotik commented on ui/tests/MonitoringPolicies/monitoringPolicies.test.ts
> +    expect(store.selectedRule).toBeDefined()
Do another check here that `id` is `0` and `name` is empty string, so we know it's the default rule.

2024-05-02 19:17 UTC, synqotik commented on ui/tests/MonitoringPoliciesLegacy/monitoringPoliciesLegacy.test.ts
> +    expect(store.selectedRule).toBeDefined()
Same as other test.

2024-05-03 11:48 UTC, faizanjanjua commented on ui/src/store/Views/monitoringPoliciesStore.ts
> +      this.selectedRule = await getDefaultRule()
Resolved

2024-05-03 11:49 UTC, faizanjanjua commented on ui/src/store/Views/monitoringPoliciesStore.ts
> +      this.selectedRule = await getDefaultRule()
Resolved , thanks

2024-05-03 11:49 UTC, faizanjanjua commented on ui/src/store/Views/monitoringPoliciesStore.ts
> +    selectedPolicy: defaultPolicy,
Resolved , thanks

2024-05-03 11:49 UTC, faizanjanjua commented on ui/src/store/Views/monitoringPoliciesStore.ts
> +    async clearSelectedPolicy() {
Resolved , thanks

2024-05-03 11:50 UTC, faizanjanjua commented on ui/src/store/Views/monitoringPoliciesStore.ts
> +        this.selectedPolicy = defaultPolicy
Resolved , thanks

2024-05-03 11:50 UTC, faizanjanjua commented on ui/src/store/Views/monitoringPoliciesStore.ts
> +      this.selectedRule = await getDefaultRule()
Resolved , thanks

2024-05-03 11:50 UTC, faizanjanjua commented on ui/tests/MonitoringPolicies/monitoringPolicies.test.ts
> +    expect(store.selectedRule).toBeDefined()
Resolved , thanks

2024-05-03 11:50 UTC, faizanjanjua commented on ui/tests/MonitoringPoliciesLegacy/monitoringPoliciesLegacy.test.ts
> +    expect(store.selectedRule).toBeDefined()
Resolved , thanks

2024-05-03 14:55 UTC, synqotik approved these changes
LGTM

2024-05-03 15:10 UTC, merged