FE: Monitoring Policies - Alert Rules - Get Trigger and Clear Events
OpenNMS-Cloud/lokahi pull request #1837
Opened 2024-05-06 13:24 UTC by Shahbaz-dataq

## Description
In Monitoring Policy, Alert Rules panel (for create or edit), after the user has chosen a Vendor for SNMP Trap event type, make a call to alertEventDefsByVendor passing the Vendor and EventType.SNMP_TRAP to get the event definitions. These will populate the Trigger Event and Clear Event dropdowns.

make call to alertEventDefsByVendor. May want to cache the responses in the monitoringPolicyStore, by vendor

Use the name field to populate the Trigger Event dropdown

The Clear Event should be an input text field. When a user selects a Trigger Event, the corresponding Clear Event should be populated.

The Clear Event will be displayed based on the clearKey for the selected Trigger Event, see below on how to parse it. Some clearKeys are empty, so display an empty string in the Clear Event text box.

Save the user selection in the Alert Rule

The clearKey, if present, will usually be in the form:

uei.opennms.org/vendor/cisco/bsnAPCoverageProfileFailed:%dpname%:%nodeid%:%interface%:%parm[#1]%:%parm[#2]%:%parm[#3]%

We want to get the last part of the UEI and display that. Can probably split the string on : to get the UEI, then split by / and pick the last part.

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2473

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-05-06 22:24 UTC, synqotik requested changes
Added comments.

2024-05-06 22:24 UTC, synqotik commented on ui/src/store/Views/monitoringPoliciesStore.ts
> +export async function getDefaultRule(): Promise<PolicyRule> {
I think this can be left as non-`export` - we are probably going to remove it or else have it just return `cloneDeep(defaultRule)`. It makes an API using `getDefaultEventCondition()` which we don't need if we just want an empty rule.

2024-05-06 22:24 UTC, synqotik commented on ui/src/store/Views/monitoringPoliciesStore.ts
> +    selectedPolicy: undefined,
We changed these to be `cloneDeep(defaultPolicy)` and `cloneDeep(defaultRule)` here and everywhere else, instead of setting to `undefined`, so they are always defined, otherwise we get errors if they a data-bound in Vue components. You should revert back to the `cloneDeep` versions unless you're sure it's ok to set these to `undefined` without any errors.

2024-05-06 22:24 UTC, synqotik commented on ui/src/store/Views/monitoringPoliciesStore.ts
> +      this.selectedRule = undefined
See my comment above, here and anywhere else that `selectedPolicy` or `selectedRule` are set to `undefined`

2024-05-06 22:24 UTC, synqotik commented on ui/src/store/Views/monitoringPoliciesStore.ts
> +          // this.refactorClearEvent(currentCondition.triggerEvent ?? {})
Remove commented-out line.

This method `updateCondition` doesn't end up doing anything, we may eventually remove it or fix it.

2024-05-06 22:24 UTC, synqotik commented on ui/src/store/Views/monitoringPoliciesStore.ts
> +        await this.getMonitoringPolicies()
I don't think we need `await` here, it can run in the background and not block here.

2024-05-06 22:24 UTC, synqotik commented on ui/src/store/Views/monitoringPoliciesStore.ts
> +      await this.getMonitoringPolicies()
Don't think we need `await` here.

2024-05-06 22:24 UTC, synqotik commented on ui/src/store/Views/monitoringPoliciesStore.ts
> -      this.selectedRule = cloneDeep(defaultRule)
Keep `cloneDeep()` version here and elsewhere.

2024-05-06 22:24 UTC, synqotik commented on ui/tests/MonitoringPoliciesLegacy/monitoringPoliciesLegacy.test.ts
> +    expect(store.selectedPolicy).toBeUndefined()
Leave this as it was if you revert back to the `cloneDeep()` versions.

2024-05-06 22:24 UTC, synqotik commented on ui/src/components/MonitoringPolicies/DetectionMethodComponents/SNMPTrapAlertConditions.vue
> +    if (monitoringPoliciesStore.selectedRule?.alertConditions[0].triggerEvent?.uei) {
I think remove this and change to 

```typescript
if (monitoringPoliciesStore.selectedRule?.alertConditions[0].triggerEvent?.clearKey) {
  clearEvent.value = monitoringPoliciesStore.refactorClearEvent(monitoringPoliciesStore.selectedRule?.alertConditions[0].triggerEvent.clearKey)
} else {
  clearEvent.value = ''
}
```

In other words, if the `triggerEvent` has a `clearKey`, we parse that and use that as the `clearEvent`, otherwise there's no clear event. At least let's go with this for now.

2024-05-07 17:03 UTC, Shahbaz-dataq commented on ui/src/store/Views/monitoringPoliciesStore.ts
> -const defaultRule: PolicyRule = {
As we discussed in meeting. We don't need `defaultRule`

2024-05-07 17:06 UTC, Shahbaz-dataq commented on ui/src/store/Views/monitoringPoliciesStore.ts
> +          // this.refactorClearEvent(currentCondition.triggerEvent ?? {})
We are using this function. See Line 55, 68 and 138 in `SNMPTrapAlertConditions`

2024-05-07 17:07 UTC, Shahbaz-dataq commented on ui/tests/MonitoringPoliciesLegacy/monitoringPoliciesLegacy.test.ts
> +    expect(store.selectedPolicy).toBeUndefined()
We need this if we want the policy in store to be `undefined`

2024-05-07 18:29 UTC, synqotik approved these changes

2024-05-08 08:55 UTC, merged