LOK-2477: New syslog config task set and publish to Minion.
OpenNMS-Cloud/lokahi pull request #1838
Opened 2024-05-06 15:53 UTC by MusaidAli

## Description

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2477

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-05-08 13:35 UTC, fooker requested changes

2024-05-08 13:35 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/SyslogConfigService.java
> +                //            .setUseAddressFromVarbind(config.shouldUseAddressFromVarbind())
Please remove

2024-05-08 13:35 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/syslogconfig/SyslogConfigBean.java
> +    private Map<String, Object> additionalProperties = new HashMap<String, Object>();
What are these used for?

2024-05-08 13:35 UTC, fooker commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/syslog/syslog-config.proto
> +   string syslog_address = 1;
Format

2024-05-08 15:53 UTC, MusaidAli commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/SyslogConfigService.java
> +                //            .setUseAddressFromVarbind(config.shouldUseAddressFromVarbind())
removed.

2024-05-08 15:53 UTC, MusaidAli commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/syslog/syslog-config.proto
> +   string syslog_address = 1;
formatted .

2024-05-08 15:53 UTC, MusaidAli commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/syslogconfig/SyslogConfigBean.java
> +    private Map<String, Object> additionalProperties = new HashMap<String, Object>();
removed ,no idea it is auto generated i think.

2024-05-09 13:40 UTC, smunir-onms commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/SyslogConfigService.java
> +        executorService.scheduleAtFixedRate(this::sendSyslogConfigToMinionAfterStartup, 900, 900, TimeUnit.SECONDS);
suggestion, 900, 900 should be configured values

2024-05-09 13:47 UTC, smunir-onms commented on inventory/main/src/test/java/org/opennms/horizon/inventory/service/SyslogConfigServiceTest.java
> +            .publishNewTasks(Mockito.anyString(), Mockito.eq(TEST_LOCATION_ID1), Mockito.any(List.class));*/
remove commented code

2024-05-09 15:59 UTC, MusaidAli commented on inventory/main/src/test/java/org/opennms/horizon/inventory/service/SyslogConfigServiceTest.java
> +            .publishNewTasks(Mockito.anyString(), Mockito.eq(TEST_LOCATION_ID1), Mockito.any(List.class));*/
resolved.removed commented code.

2024-05-09 16:00 UTC, MusaidAli commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/SyslogConfigService.java
> +        executorService.scheduleAtFixedRate(this::sendSyslogConfigToMinionAfterStartup, 900, 900, TimeUnit.SECONDS);
resolved.values from config.

2024-05-14 09:42 UTC, fooker approved these changes

2024-05-14 09:42 UTC, fooker commented
Looks good to me. Tests still failing

2024-05-15 11:59 UTC, merged