LOK-2478 :Syslog message from camel route to Syslog SinkModule
OpenNMS-Cloud/lokahi pull request #1839
Opened 2024-05-06 16:42 UTC by MusaidAli

## Description
Syslog message from camel route to Syslog SinkModule

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2478

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-05-14 09:55 UTC, fooker requested changes

2024-05-14 09:55 UTC, fooker commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/syslog/syslog.proto
> +  string syslogOID = 4;
What do these fields mean?

2024-05-14 09:55 UTC, fooker commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/syslog/syslog.proto
> +  string community = 6;
What is the `community`?

2024-05-14 09:55 UTC, fooker commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/syslog/syslog.proto
> +  string version = 7;
What is the `version`?

2024-05-14 09:55 UTC, fooker commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                                    .build();
I'm pretty sure this is non-sense.

2024-05-14 09:55 UTC, fooker commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                            LOG.info("Date:" + m_message.getDate().toString());
Do not info-log every message

2024-05-14 09:55 UTC, fooker commented on events/syslog/src/main/java/org/opennms/horizon/events/syslog/impl/SysLogProtoToEventLogXmlMapperImpl.java
> +        // TODO: Add metrics for Traps received/error/dropped.
??

2024-05-15 12:00 UTC, MusaidAli commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/syslog/syslog.proto
> +  string syslogOID = 4;
removed ,

2024-05-15 12:00 UTC, MusaidAli commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/syslog/syslog.proto
> +  string community = 6;
removed community ,community public belongs to snmp

2024-05-15 12:01 UTC, MusaidAli commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/syslog/syslog.proto
> +  string version = 7;
removed ,version

2024-05-15 12:01 UTC, MusaidAli commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                            LOG.info("Date:" + m_message.getDate().toString());
refactored.

2024-05-15 12:01 UTC, MusaidAli commented on events/syslog/src/main/java/org/opennms/horizon/events/syslog/impl/SysLogProtoToEventLogXmlMapperImpl.java
> +        // TODO: Add metrics for Traps received/error/dropped.
removed //TODO

2024-05-15 12:01 UTC, MusaidAli commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                                    .build();
yeah,it is removed.

2024-05-23 06:56 UTC, closed without merging