LOK-2446: Implement enable/disable Monitoring Policy
OpenNMS-Cloud/lokahi pull request #1846
Opened 2024-05-09 11:04 UTC by Syed-Bilal-Haider-Dataq

## Description
Implement enable/disable Monitoring Policy
## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2446

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-05-09 17:36 UTC, synqotik requested changes
I updated LOK-2446 with more details, please review and implement.

2024-05-09 17:36 UTC, synqotik commented on ui/src/components/MonitoringPolicies/MonitoringPolicyBasicInformationEditAddForm.vue
> +const formattedTags = computed(() => store?.selectedPolicy!.tags!.map((tag: string) => ({ name: tag, id: tag })))
Should not need `store?`, it's always defined. May you need: `store.selectedPolicy?.tags?.map(...) || []`

2024-05-09 17:36 UTC, synqotik commented on ui/src/store/Views/monitoringPoliciesStore.ts
> +    async enableAndDisableMonitoringPolicies(status: boolean) {
I updated LOK-2446, you can use that implementation and remove this.

2024-05-13 10:27 UTC, Syed-Bilal-Haider-Dataq commented on ui/src/components/MonitoringPolicies/MonitoringPolicyBasicInformationEditAddForm.vue
> +const formattedTags = computed(() => store?.selectedPolicy!.tags!.map((tag: string) => ({ name: tag, id: tag })))
I use the optional chaining method because it helps me address warnings thrown by the linter. ok, I resolve.

2024-05-13 17:33 UTC, synqotik approved these changes
LGTM

2024-05-13 18:07 UTC, merged