LOK-2487: Alert Rule Table Display fixes
OpenNMS-Cloud/lokahi pull request #1847
Opened 2024-05-09 13:49 UTC by Syed-Bilal-Haider-Dataq

## Description
Alert rule table displays, wherever they appear, should have following columns:

Name - name of the rule

Type - event type, friendly name, e.g. “Internal”, “SNMP Trap”, “Syslog”, “Metric Threshold”

Description - for now let's use Severity / Trigger Event name. For example: “Critical / SNMP Cold Start”

## Jira link(s)
https://opennms.atlassian.net/browse/LOK-2487

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-05-09 16:56 UTC, synqotik requested changes
I updated LOK-2487, please take a look. Note, you also need to fix the table header names.

2024-05-13 17:39 UTC, synqotik approved these changes
One typo to fix before merging, other than that looks good.

2024-05-13 17:39 UTC, synqotik commented on ui/src/components/MonitoringPolicies/MonitoringPoliciesAlertsRulesTable.vue
> +  { id: 'NameOdRule', label: 'Name' },
Should be `NameOfRule` or just `Name`

2024-05-13 17:51 UTC, Syed-Bilal-Haider-Dataq commented on ui/src/components/MonitoringPolicies/MonitoringPoliciesAlertsRulesTable.vue
> +  { id: 'NameOdRule', label: 'Name' },
Oh. I check it.

2024-05-13 18:15 UTC, merged