FE: Unit tests for monitoringPoliciesStore
OpenNMS-Cloud/lokahi pull request #1852
Opened 2024-05-10 15:07 UTC by faizanjanjua

## Description
Add tests/store/Views/monitoringPoliciesStore.test.ts and add tests for all methods.

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2413

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-05-10 18:28 UTC, synqotik requested changes
Added some comments.

In many cases, we can test the actual functionality. But let's get this approved and merged, then we can open another issue to make the tests more robust.

2024-05-10 18:28 UTC, synqotik commented on ui/tests/store/Views/monitoringPolicyStore.test.ts
> +    vi.spyOn(monitoringPolicies, 'displayPolicyForm')
Remove all these `vi.spyOn` if you can. When using `createTestingPinia`, all items in the `store` have spies automatically attached. Also in some cases, the `spyOn` doesn't match the method you are checking, so it's confusing.

2024-05-10 18:28 UTC, synqotik commented on ui/tests/store/Views/monitoringPolicyStore.test.ts
> +  let stubActionsFlag = false // Flag to control stubActions
Let's try this. Make 2 `describe` blocks under the main one - one where `stubActions` is `false`, the other when `stubActions` is `true`. You can call one `describe('when stubActions is false')` and `describe('when stubActions is true')`.

Then in `beforeEach`, just have `createTestingPinia({ stubActions: false })` (or `true`) and don't need `stubActionsFlag`.

Also remove any other `beforeAll(() => createTestingPinia())` unless it's absolutely needed.

2024-05-10 18:28 UTC, synqotik commented on ui/tests/store/Views/monitoringPolicyStore.test.ts
> +  it('monitoringPolicies.getMonitoringPolicies complete successfully', async () => {
See above comment, put these 2 items that have `stubActions: true` into a separate nested `describe`.

2024-05-10 18:28 UTC, synqotik commented on ui/tests/store/Views/monitoringPolicyStore.test.ts
> +  it('monitoringPolicies.deleteCondition complete successfully', async () => {
Should be called `test('monitoringPolicies.validateRule completes successfully'`

2024-05-10 18:28 UTC, synqotik commented on ui/tests/store/Views/monitoringPolicyStore.test.ts
> +  it('monitoringPolicies.addNewCondition complete successfully', async () => {
This looks like a duplicate, already implemented above, so you can delete it here.

2024-05-13 12:49 UTC, faizanjanjua commented on ui/tests/store/Views/monitoringPolicyStore.test.ts
> +  let stubActionsFlag = false // Flag to control stubActions
done

2024-05-13 12:49 UTC, faizanjanjua commented on ui/tests/store/Views/monitoringPolicyStore.test.ts
> +  it('monitoringPolicies.getMonitoringPolicies complete successfully', async () => {
done

2024-05-13 12:49 UTC, faizanjanjua commented on ui/tests/store/Views/monitoringPolicyStore.test.ts
> +  it('monitoringPolicies.deleteCondition complete successfully', async () => {
done

2024-05-13 12:49 UTC, faizanjanjua commented on ui/tests/store/Views/monitoringPolicyStore.test.ts
> +  it('monitoringPolicies.addNewCondition complete successfully', async () => {
done

2024-05-13 17:15 UTC, synqotik approved these changes

2024-05-14 10:40 UTC, merged