FE: Monitoring Policies - robust unit tests for monitoringPoliciesStore
OpenNMS-Cloud/lokahi pull request #1857
Opened 2024-05-14 13:51 UTC by faizanjanjua

## Description
Update the unit tests for monitoringPoliciesStore to test actual functionality, for example that deleteRule deletes the rule with the given id from the selectedPolicy, etc.

An example is here: [Example of monitoringPoliciesStore unit test by synqotik · Pull Request #1849 · OpenNMS-Cloud/lokahi](https://github.com/OpenNMS-Cloud/lokahi/pull/1849)

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2504

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-05-22 21:10 UTC, synqotik requested changes
Overall looks good. Added a couple cases where we can check a few more things.

2024-05-22 21:10 UTC, synqotik commented on ui/tests/store/Views/monitoringPoliciesStore.test.ts
> +        if (store.selectedRule.alertConditions && store.selectedRule.alertConditions?.length > 0) {
We can check that `alertConditions` now have 1 item:

```
expect(store.selectedRule.alertConditions.length).toBe(1)
```

2024-05-22 21:10 UTC, synqotik commented on ui/tests/store/Views/monitoringPoliciesStore.test.ts
> +        if (store.selectedRule.alertConditions && store.selectedRule.alertConditions?.length > 0) {
See above, can check there is 1 condition now

2024-05-22 21:10 UTC, synqotik commented on ui/tests/store/Views/monitoringPoliciesStore.test.ts
> +      expect(store.selectedPolicy.rules).length.lessThanOrEqual(0)
`length` should now be 0, can do:

```
expect(store.selectedPolicy.rules.length).toBe(0)
```

2024-05-23 12:09 UTC, faizanjanjua commented on ui/tests/store/Views/monitoringPoliciesStore.test.ts
> +      expect(store.selectedPolicy.rules).length.lessThanOrEqual(0)
`  await store.removeRule()
      expect(store.selectedRule).toBeUndefined()
       // @ts-ignore
      expect(store.selectedPolicy.rules.length).toBe(0)`
      
      
      i have changed it to this.. but for this we have to use @ts-ignore Warning 
      
      other possible solution could be 
     ` await store.removeRule()
      expect(store.selectedRule).toBeUndefined()
      if(store.selectedPolicy.rules !==undefined) {
      expect(store.selectedPolicy.rules.length).toBe(0)
      }`
      
      suggest me better option so  i can change and commit.

2024-05-29 18:00 UTC, synqotik approved these changes
LGTM!

2024-05-29 18:02 UTC, merged