LOK-2509: Monitoring Policies - save policy / enabled status
OpenNMS-Cloud/lokahi pull request #1863
Opened 2024-05-16 12:14 UTC by Syed-Bilal-Haider-Dataq

## Description
Issues with policy enabled status and saving a policy.

Sometimes clicking on Save Policy in the Edit Details panel doesn't do anything, doesn’t seem to send the graphQL request

If a user changes Enabled status in the Edit Details panel, then clicks Save Policy, the list should be refreshed and the enabled status should display correctly in the table, even while the user is still on the Edit Details panel

There should be a Save Policy button on the policy edit screen in Basic Information tab when in Edit mode (not just on the Alert Rules tab). Also when in Edit mode, remove the Next button in Basic Information and replace with this Save Policy button.
## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2509

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-05-17 15:31 UTC, synqotik requested changes
Looks good. I'm just requesting a couple of name changes to make it a little clearer.

2024-05-17 15:31 UTC, synqotik commented on ui/src/components/MonitoringPolicies/MonitoringPoliciesDetailPanel.vue
> +const savePolicyEnableDisable = computed(
Perhaps rename to `isSavePolicyDisabled`.

Also, let's change the name of `enableDisable` to be `isPolicyEnabled`.

Hopefully that will make it a little clearer what these properties do.

2024-05-20 18:22 UTC, synqotik requested changes
A couple of changes.

2024-05-20 18:22 UTC, synqotik commented on ui/src/components/MonitoringPolicies/MonitoringPoliciesEditPanel.vue
> +const savePolicyEnableDisable = computed(
This should also be renamed to `isSavePolicyDisabled`

2024-05-20 18:22 UTC, synqotik commented on ui/src/components/MonitoringPolicies/MonitoringPoliciesDetailPanel.vue
> +  const result = await store?.savePolicy({status: enableDisable.value})
Please also make this change, as requested:

change the name of `enableDisable` to be `isPolicyEnabled.`

2024-05-22 15:14 UTC, faizanjanjua commented
LGTM!

2024-05-22 15:15 UTC, faizanjanjua approved these changes
LGTM!

2024-05-22 20:26 UTC, synqotik approved these changes

2024-05-22 20:27 UTC, merged