LOK-2306: Send Alerts via eMail (Lokahi)
OpenNMS-Cloud/lokahi pull request #1865
Opened 2024-05-17 08:04 UTC by aurang-zeb313

## Description
As an IT Manager, I want to create a Monitoring Policy that delivers alerts and alert updates via e-mail to my most critical users.

We already have a mail-server container running on Tilt/Helm.  Enable it, and provide instructions on how to use it so that we can integrate it into a user’s mail environment.  sendmail or similar is fine.  Document clearly.

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2306

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-05-17 08:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1865) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1865) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenNMS-Cloud/lokahi?pullRequest=1865) it.</sub>

2024-05-17 08:15 UTC, fooker requested changes

2024-05-17 08:15 UTC, fooker commented on alert/src/main/java/org/opennms/horizon/alertservice/service/MonitorPolicyService.java
> +        policy.setEnabled(true);
Is this an accident? If not, remove the parameter as it is unused.

2024-05-17 08:15 UTC, fooker commented on alert/src/test/java/org/opennms/horizon/alertservice/grpc/MonitoringPolicyGrpcTest.java
> +                mockTagOperationProducer,
fmt

2024-05-17 08:15 UTC, fooker commented on notifications/src/main/java/org/opennms/horizon/notifications/api/email/SmtpEmailAPI.java
> -
Why?

2024-05-17 08:15 UTC, fooker commented on notifications/src/main/java/org/opennms/horizon/notifications/config/EmailConfig.java
> +import org.springframework.beans.factory.annotation.Autowired;
Revert

2024-05-17 08:15 UTC, fooker commented on notifications/src/main/java/org/opennms/horizon/notifications/service/NotificationService.java
> +import org.springframework.beans.factory.annotation.Value;
Revert

2024-05-17 08:15 UTC, fooker commented on notifications/src/main/java/org/opennms/horizon/notifications/service/NotificationService.java
> +
Revert

2024-05-17 08:15 UTC, fooker commented on notifications/src/main/resources/application.yml
> +
Revert

2024-05-17 08:15 UTC, fooker commented on notifications/src/test/java/org/opennms/horizon/notifications/service/NotificationServiceImplTest.java
> +                .thenReturn(policies);
Why altering this? If the list needs to be mutable for any reason, there are better ways to do this.

2024-05-17 10:16 UTC, aurang-zeb313 commented on alert/src/main/java/org/opennms/horizon/alertservice/service/MonitorPolicyService.java
> +        policy.setEnabled(true);
Done

2024-05-17 10:17 UTC, aurang-zeb313 commented on alert/src/test/java/org/opennms/horizon/alertservice/grpc/MonitoringPolicyGrpcTest.java
> +                mockTagOperationProducer,
Done

2024-05-17 10:34 UTC, aurang-zeb313 commented on notifications/src/main/resources/application.yml
> +
run spotless  and its reverted.

2024-05-17 10:35 UTC, aurang-zeb313 commented on notifications/src/main/java/org/opennms/horizon/notifications/service/NotificationService.java
> +
reverted

2024-05-17 10:35 UTC, aurang-zeb313 commented on notifications/src/main/java/org/opennms/horizon/notifications/api/email/SmtpEmailAPI.java
> -
reverted. run spotless

2024-05-17 10:35 UTC, aurang-zeb313 commented on notifications/src/main/java/org/opennms/horizon/notifications/service/NotificationService.java
> +import org.springframework.beans.factory.annotation.Value;
run spotless and reverted

2024-05-22 11:48 UTC, fooker approved these changes

2024-05-22 12:05 UTC, merged

2024-05-22 15:05 UTC, mershad-manesh commented on charts/lokahi/values.yaml
This change is not correct!
We shouldn't hardcode these values nor use this email server for development purpose