LOK-2503 : Create an GRPC and GraphQL interface to query Monitored Entities
OpenNMS-Cloud/lokahi pull request #1872
Opened 2024-05-20 15:07 UTC by Junaid-Khan-Nant

## Description
Create a new GRPC service in inventory exporting interface to query Monitored Entities:
    Query all Monitored Entities
    Query Monitored Entities by provider
Add filters to query by location.
Create a GraphQL interface which forwards requests to the new GRPC service.

## Jira link(s)
https://opennms.atlassian.net/browse/LOK-2503

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-05-20 17:55 UTC, smunir-onms commented on rest-server/src/main/java/org/opennms/horizon/server/service/grpc/InventoryClient.java
> +import org.opennms.horizon.inventory.dto.*;
avoid wildcard imports

2024-05-22 12:02 UTC, fooker requested changes
This does not use the existing monitored entity structure at all. Make sure to not create own instances but use existing services.

2024-05-22 12:02 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/model/DiscoveryMonitoredEntityProvider.java
> +    public List<MonitorEntityResponse> getAllMonitoredEntities(String tenantId) {
The whole method is just a copy of already existing code...

2024-05-22 12:02 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/model/DiscoveryMonitoredEntityProvider.java
> +    public List<MonitorEntityResponse> getMonitorEntitiesBySearchTerm(String tenantId, String searchTerm) {
Same

2024-05-23 10:02 UTC, fooker requested changes
Please separate monitored entity status API and monitored entity search API.
Also the endpoint for getting all monitored entities for an tenant is missing.

2024-05-27 11:08 UTC, fooker requested changes

2024-05-27 11:08 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/discovery/MonitoredEntitySearchGrpcService.java
> +    public void listAllMonitors(Int64Value request, StreamObserver<ListMonitorEntities> responseObserver) {
rename to `getAllMonitoredEntitiesByLocation`

2024-05-27 11:08 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/discovery/MonitoredEntitySearchGrpcService.java
> +    public void getAllMonitoredEntitiesByTenant(Empty request, StreamObserver<ListMonitorEntities> responseObserver) {
rename to `getAllMonitoredEntities`. Everything is by tenant.

2024-05-27 11:08 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/monitoring/MonitoredEntityProvider.java
> +    List<MonitoredEntity> getMonitoredEntitiesByTenant(final String tenantId);
I'm strongly against having such a method. Let the `MonitoredEntityService` figure all existing locations for a tenant and then call `getMonitoredEntities` for each of these locations.

2024-05-27 11:08 UTC, fooker commented on shared-lib/inventory/src/main/proto/monitoredEntitySearch.proto
> +  rpc getAllMonitoredEntitiesByTenant(google.protobuf.Empty) returns(ListMonitorEntities){};
Rename here, too

2024-05-27 11:08 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/monitoring/MonitoredEntityService.java
> +    public Stream<MonitoredEntity> getAllMonitoredEntitesByTenant(final String tenantId) {
Rename here, too

2024-05-27 11:08 UTC, fooker commented on shared-lib/inventory/src/main/proto/monitoredServiceStatus.proto
> +import "google/protobuf/any.proto";
Revert

2024-05-27 11:08 UTC, fooker commented on shared-lib/inventory/src/main/proto/monitoredServiceStatus.proto
> -
Revert.

2024-05-28 07:44 UTC, fooker requested changes
This also requires tests

2024-05-28 07:44 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/discovery/MonitoredEntitySearchGrpcService.java
> +        }
This is an outlier to the other behavior. Just return the empty list if no result could be found.

2024-05-28 07:44 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/monitoring/MonitoredEntityService.java
> +                        .flatMap(provider -> provider.getMonitoredEntities(tenantId, location.getId()).stream()));
You can optimize by swapping:

```suggestion
        return this.providers.stream()
            .flatMap(provider -> monitoringLocationRepository.findByTenantId(tenantId).stream()
                .map(location -> provider.getMonitoredEntities(tenantId, location.getId()));
```

2024-05-28 07:44 UTC, fooker commented on rest-server/src/main/java/org/opennms/horizon/server/service/GraphQLMonitoredEntityService.java
> +        return Flux.fromIterable(
There is a `Flux.fromStream` which can save you the `toList`

2024-05-28 07:44 UTC, fooker commented on shared-lib/inventory/src/main/proto/monitoredEntitySearch.proto
> +service MonitoredEntitySearchService {
```suggestion
service MonitoredEntityService {
```

2024-05-28 11:19 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/MonitoredEntityStatusGrpcService.java
> +    private final DiscoveryMonitoredEntityProvider discoveryMonitoredEntityProvider;
Done.

2024-05-28 11:20 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/MonitoredEntityStatusGrpcService.java
> +                    } catch (Exception e) {
Done.

2024-05-28 11:20 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/model/DiscoveryMonitoredEntityProvider.java
> +    public List<MonitorEntityResponse> getAllMonitoredEntities(String tenantId) {
removed.

2024-05-28 11:20 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/model/DiscoveryMonitoredEntityProvider.java
> +    public List<MonitorEntityResponse> getMonitorEntitiesBySearchTerm(String tenantId, String searchTerm) {
removed.

2024-05-28 11:20 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/discovery/MonitoredEntitySearchGrpcService.java
> +    public void listAllMonitors(Int64Value request, StreamObserver<ListMonitorEntities> responseObserver) {
Done.

2024-05-28 11:20 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/discovery/MonitoredEntitySearchGrpcService.java
> +    public void getAllMonitoredEntitiesByTenant(Empty request, StreamObserver<ListMonitorEntities> responseObserver) {
Done.

2024-05-28 11:21 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/monitoring/MonitoredEntityProvider.java
> +    List<MonitoredEntity> getMonitoredEntitiesByTenant(final String tenantId);
removed.

2024-05-28 11:21 UTC, Junaid-Khan-Nant commented on shared-lib/inventory/src/main/proto/monitoredEntitySearch.proto
> +  rpc getAllMonitoredEntitiesByTenant(google.protobuf.Empty) returns(ListMonitorEntities){};
Done.

2024-05-28 11:21 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/monitoring/MonitoredEntityService.java
> +    public Stream<MonitoredEntity> getAllMonitoredEntitesByTenant(final String tenantId) {
Done.

2024-05-28 11:21 UTC, Junaid-Khan-Nant commented on shared-lib/inventory/src/main/proto/monitoredServiceStatus.proto
> +import "google/protobuf/any.proto";
Done.

2024-05-28 11:21 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/discovery/MonitoredEntitySearchGrpcService.java
> +        }
removed.

2024-05-28 11:21 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/monitoring/MonitoredEntityService.java
> +                        .flatMap(provider -> provider.getMonitoredEntities(tenantId, location.getId()).stream()));
Done.

2024-05-28 11:21 UTC, Junaid-Khan-Nant commented on rest-server/src/main/java/org/opennms/horizon/server/service/GraphQLMonitoredEntityService.java
> +        return Flux.fromIterable(
Done.

2024-05-28 11:21 UTC, Junaid-Khan-Nant commented on shared-lib/inventory/src/main/proto/monitoredEntitySearch.proto
> +service MonitoredEntitySearchService {
Done.

2024-05-29 09:50 UTC, fooker requested changes

2024-05-29 09:50 UTC, fooker commented on rest-server/src/main/java/org/opennms/horizon/server/model/inventory/MonitoredDTO.java
> +public class MonitoredDTO {
Please rename to `MonitoredEntityDTO`

2024-05-29 09:50 UTC, fooker commented on rest-server/src/main/java/org/opennms/horizon/server/model/inventory/MonitoredDTO.java
> +    public Any config;
`Any` is not supported in a GraphQL response. You have multiple routes to choose from here:
- Serialize the config to JSON and make the field a string
- Go all in and figure out how to represent arbitrary scalar data in GraphQL (maybe a `JsonNode` could work)
- Create a follow up issue which we can defere until we know what UI needs there

2024-05-29 13:33 UTC, smunir-onms commented on rest-server/src/main/java/org/opennms/horizon/server/model/inventory/MonitoredDTO.java
> +    public Any config;
> `Any` is not supported in a GraphQL response. You have multiple routes to choose from here:
> 
> * Serialize the config to JSON and make the field a string
> * Go all in and figure out how to represent arbitrary scalar data in GraphQL (maybe a `JsonNode` could work)
> * Create a follow up issue which we can defere until we know what UI needs there
Issue created: https://opennms.atlassian.net/browse/LOK-2545

2024-05-29 13:37 UTC, Junaid-Khan-Nant commented on rest-server/src/main/java/org/opennms/horizon/server/model/inventory/MonitoredDTO.java
> +public class MonitoredDTO {
Done

2024-05-29 15:53 UTC, fooker commented on rest-server/src/main/java/org/opennms/horizon/server/service/GraphQLMonitoredEntityService.java
> +// @GraphQLApi
Remove

2024-05-29 15:55 UTC, fooker commented on inventory/main/src/test/java/org/opennms/horizon/inventory/monitoring/MonitoredEntityServiceTest.java
> +        MonitoredEntityProvider provider1 = mock(MonitoredEntityProvider.class);
I think you are better of creating a real impl of the `MonitoredEntityProvider` interface in the test. Let it serve some static data that you can test against.

2024-06-04 10:56 UTC, fooker approved these changes

2024-06-04 11:20 UTC, merged