LOK-2478 : Syslog message from camel route to Syslog SinkModule
OpenNMS-Cloud/lokahi pull request #1885
Opened 2024-05-23 06:20 UTC by MusaidAli

## Description
Syslog message from camel route to Syslog SinkModule

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2478

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-05-23 09:36 UTC, fooker commented on minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/server/syslog/SyslogKafkaForwarder.java
> +            @Value("${traps.results.kafka-topic:" + DEFAULT_TRAP_RESULTS_TOPIC + "}") String kafkaTopic) {
Same here. This ain't not traps

2024-05-23 09:37 UTC, fooker commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                            LOG.info("content" + content);
Please reduce log level and amount of messages

2024-05-23 09:38 UTC, fooker commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                                    .setEnterpriseId("EntID")
Still no enterprise ID for syslog.

2024-05-23 09:39 UTC, fooker commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                            SyslogMessage m_message = syslogParser.parse(content);
Variable naming: `m_` in members is a pity, but as a variable it's a no-no.

2024-05-23 09:40 UTC, fooker commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                            Identity identity1 = Identity.newBuilder()
What is this identity and where is `identity2`?

2024-05-23 09:42 UTC, fooker commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                                    .setRawMessage(ByteString.copyFrom(
You go the whole loop from bytes to string to parsed message to string to bytes for nothing

2024-05-23 09:42 UTC, fooker commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                            LOG.info("Message sent");
Remove useless log messages

2024-05-23 09:43 UTC, fooker commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                        } catch (final Exception ex) {
Again, do not catch raw exception!

2024-05-23 09:44 UTC, fooker commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/parser/SyslogMessage.java
> +    // will add
Why date and separate fields?

2024-05-23 09:45 UTC, fooker commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/parser/SyslogParser.java
> +    private static final String datePattern = "((19|20)\\d{2})-([1-9]|0[1-9]|1[0-2])-(0[1-9]|[1-9]|[12][0-9]|3[01])";
Does this replace `m_datePattern`. What about the comment above - why drop the performance improvement?

2024-05-23 09:47 UTC, fooker commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/parser/SyslogParser.java
> +        }*/
What about this code?

2024-05-23 09:49 UTC, fooker commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/parser/SyslogParser.java
> -        entry.setMessage(parts[5]);
THB, I don't get why this change is necessary. Is this ported from classic?

2024-05-23 09:51 UTC, fooker commented on minion/minion-syslog/listener/src/main/resources/OSGI-INF/blueprint/blueprint.xml
> +            <cm:property name="syslog.m_matchingGroupMessage" value="8" />
Please remove `m_`

2024-05-23 09:52 UTC, fooker commented on minion/minion-syslog/listener/src/main/resources/OSGI-INF/blueprint/blueprint.xml
> +        <property name="m_matchingGroupMessage" value="${syslog.m_matchingGroupMessage}" />
Please remove `m_`

2024-05-23 09:53 UTC, fooker commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/syslog/syslog.proto
> +  string syslogOID = 4;
What is all this? AFAIK there is no enterpriseId of OID in syslog. And what does generic and specific even mean?

2024-05-23 09:53 UTC, fooker commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/syslog/syslog.proto
> +  string community = 6;
No community in syslog.

2024-05-23 09:53 UTC, fooker commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/syslog/syslog.proto
> +  string version = 7;
What version is this?

2024-05-23 09:54 UTC, fooker commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/syslog/tenantLocationSyslog.proto
> +  string syslogAddress = 2;
What is `syslogAddress`? Reveiver address? sender address?

2024-05-23 12:11 UTC, MusaidAli commented on minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/server/syslog/SyslogKafkaForwarder.java
> +    public static final String DEFAULT_TRAP_RESULTS_TOPIC = "traps";
added new topic syslog.please check latest commit.

2024-05-23 12:11 UTC, MusaidAli commented on minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/server/syslog/SyslogKafkaForwarder.java
> +            @Value("${traps.results.kafka-topic:" + DEFAULT_TRAP_RESULTS_TOPIC + "}") String kafkaTopic) {
resolved.

2024-05-23 12:12 UTC, MusaidAli commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                            SyslogMessage m_message = syslogParser.parse(content);
resolved.

2024-05-23 12:12 UTC, MusaidAli commented on minion/minion-syslog/listener/src/main/resources/OSGI-INF/blueprint/blueprint.xml
> +        <property name="m_matchingGroupMessage" value="${syslog.m_matchingGroupMessage}" />
resolved.

2024-05-23 12:12 UTC, MusaidAli commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/syslog/syslog.proto
> +  string syslogOID = 4;
resolved.please check latest commit.

2024-05-23 12:12 UTC, MusaidAli commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/syslog/syslog.proto
> +  string version = 7;
resolved.

2024-05-23 12:12 UTC, MusaidAli commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/syslog/tenantLocationSyslog.proto
> +  string syslogAddress = 2;
resolved.

2024-05-23 12:13 UTC, MusaidAli commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/syslog/syslog.proto
> +  string community = 6;
resolved.

2024-05-23 12:27 UTC, fooker requested changes
I don't see the point in duplicating the whole event sending code. Can you make the existing one shared?

2024-05-23 12:27 UTC, fooker commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/syslog/syslog.proto
> +  string listenPort = 2 ;
Sending back the listening address and port here sounds useless. Do you mean to send the sender infos?

2024-05-23 12:27 UTC, fooker commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/syslog/tenantLocationSyslog.proto
> +  string listenAddress = 2;
If we have this info here and in the repeated inner message, which one do we use?

2024-05-23 12:27 UTC, fooker commented on events/syslog/src/main/java/org/opennms/horizon/events/syslog/impl/EventXmlToProtoMapperImpl.java
> +public class EventXmlToProtoMapperImpl implements EventXmlToProtoMapper {
We already have these somewhere. share them

2024-05-23 13:30 UTC, closed without merging

2024-06-03 15:13 UTC, MusaidAli commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/syslog/tenantLocationSyslog.proto
> +  string syslogAddress = 2;
added senderAddress