LOK-2477 :New syslog config task set and publish to minion.
OpenNMS-Cloud/lokahi pull request #1886
Opened 2024-05-23 08:26 UTC by MusaidAli

## Description

## Jira link(s)
-https://opennms.atlassian.net/browse/LOK-2477

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-05-23 09:58 UTC, fooker requested changes

2024-05-23 09:58 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/syslogconfig/SyslogConfigBean.java
> +    private Integer syslogPort;
Consider renaming to `listenAddress` and `listenPort` for more concise naming.

2024-05-23 11:31 UTC, MusaidAli commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/syslogconfig/SyslogConfigBean.java
> +    private Integer syslogPort;
renamed these parameters .

2024-05-23 11:45 UTC, cgorantla requested changes
This config task needs to be published on Minion and Syslog listener should use syslog port passed from here.

2024-05-24 13:02 UTC, closed without merging

2024-05-24 13:02 UTC, smunir-onms commented
replaced with https://github.com/OpenNMS-Cloud/lokahi/pull/1888