LOK-2478 : Syslog message from camel route to Syslog SinkModule
OpenNMS-Cloud/lokahi pull request #1887
Opened 2024-05-23 13:32 UTC by MusaidAli

## Description
Syslog message from camel route to Syslog SinkModule

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2478
- 

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-05-23 13:52 UTC, fooker requested changes

2024-05-23 13:52 UTC, fooker commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                        LOG.info("Message received : {}", exchange.getIn().getBody());
Reduce this to level debug or even trace

2024-05-23 13:52 UTC, fooker commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                            LOG.info("content{}", content);
Same. remove or reduce level

2024-05-23 13:52 UTC, fooker commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                            SyslogMessage m_message = syslogParser.parse(content);
Still the same: broken naming and doing full-cycle parsing for nothing

2024-05-23 13:52 UTC, fooker commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                                    .setSystemId("SyslogID")
Again, what is this ID?

2024-05-23 13:52 UTC, fooker commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                                    .setSyslogAddress(source.getHostName())
Setting address twice

2024-05-23 13:52 UTC, fooker commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                        } catch (final Exception ex) {
See old comments

2024-05-23 13:52 UTC, fooker commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                            LOG.info("Message sent");
See old comments

2024-05-23 13:52 UTC, fooker commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/parser/SyslogMessage.java
> +    // will add
See old comments

2024-05-23 13:52 UTC, fooker commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/parser/SyslogParser.java
> +    private static final String datePattern = "((19|20)\\d{2})-([1-9]|0[1-9]|1[0-2])-(0[1-9]|[1-9]|[12][0-9]|3[01])";
See old comments

2024-05-23 13:52 UTC, fooker commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/parser/SyslogParser.java
> +        }*/
See old comments

2024-05-23 13:52 UTC, fooker commented on minion/minion-syslog/listener/src/main/resources/OSGI-INF/blueprint/blueprint.xml
> +            <cm:property name="syslog.forwardingPattern" value="^.*\s*(19|20)\d\d([-/.])(0[1-9]|1[012])\2(0[1-9]|[12][0-9]|3[01])(\s+)(\S+)(\s)(\S.+)" />
What does this forwarding pattern do and why does it need to be configurable?

2024-05-23 13:52 UTC, fooker commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/java/org/opennms/horizon/shared/grpc/syslog/contract/mapper/impl/TenantLocationSpecificSyslogMessageDTOMapperImpl.java
> +public class TenantLocationSpecificSyslogMessageDTOMapperImpl implements TenantLocationSpecificSyslogMessageDTOMapper {
Why is this not generated by mapstruct?

2024-05-23 14:00 UTC, MusaidAli commented on minion/minion-syslog/listener/src/main/resources/OSGI-INF/blueprint/blueprint.xml
> +            <cm:property name="syslog.forwardingPattern" value="^.*\s*(19|20)\d\d([-/.])(0[1-9]|1[012])\2(0[1-9]|[12][0-9]|3[01])(\s+)(\S+)(\s)(\S.+)" />
it was configurable in classic ,and there is todo task for it ,currently not handled.

2024-05-23 14:01 UTC, MusaidAli commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/java/org/opennms/horizon/shared/grpc/syslog/contract/mapper/impl/TenantLocationSpecificSyslogMessageDTOMapperImpl.java
> +public class TenantLocationSpecificSyslogMessageDTOMapperImpl implements TenantLocationSpecificSyslogMessageDTOMapper {
same was like for traps ,we follow traps

2024-05-23 15:34 UTC, MusaidAli commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                        LOG.info("Message received : {}", exchange.getIn().getBody());
reduced to log.trace.

2024-05-23 15:35 UTC, MusaidAli commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                            LOG.info("content{}", content);
reduced to log.trace.

2024-05-23 15:38 UTC, MusaidAli commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/SyslogRoute.java
> +                                    .setSyslogAddress(source.getHostName())
removed ,other

2024-05-23 15:39 UTC, MusaidAli commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/parser/SyslogParser.java
> +    private static final String datePattern = "((19|20)\\d{2})-([1-9]|0[1-9]|1[0-2])-(0[1-9]|[1-9]|[12][0-9]|3[01])";
where are old comment ,i didn't find would you share here.thanks

2024-05-28 07:55 UTC, fooker requested changes

2024-05-28 07:55 UTC, fooker commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/java/org/opennms/horizon/shared/grpc/syslog/contract/mapper/impl/TenantLocationSpecificSyslogMessageDTOMapperImpl.java
> +public class TenantLocationSpecificSyslogMessageDTOMapperImpl implements TenantLocationSpecificSyslogMessageDTOMapper {
Just you've copied crappy code does not mean you do not have to correct it. Please verify if it is possible to use mapstruct here.

2024-05-28 07:55 UTC, fooker commented on minion/minion-syslog/listener/src/main/java/org/opennms/horizon/minion/syslog/listener/parser/SyslogParser.java
> +    private static final String datePattern = "((19|20)\\d{2})-([1-9]|0[1-9]|1[0-2])-(0[1-9]|[1-9]|[12][0-9]|3[01])";
Took me a whole 30 secs to find these...

- https://github.com/OpenNMS-Cloud/lokahi/pull/1885/files/1b299134a109ce1c36d7105be38474a17c3a1b58#r1611367579
- https://github.com/OpenNMS-Cloud/lokahi/pull/1885/files/1b299134a109ce1c36d7105be38474a17c3a1b58#r1611369657
- https://github.com/OpenNMS-Cloud/lokahi/pull/1885/files/1b299134a109ce1c36d7105be38474a17c3a1b58#r1611372598

2024-06-11 15:00 UTC, closed without merging