LOK-2477 :
OpenNMS-Cloud/lokahi pull request #1888
Opened 2024-05-23 13:40 UTC by MusaidAli

## Description
New syslog config task set and publish to minion.

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2477

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-05-23 14:25 UTC, fooker requested changes
See comments in old PR

2024-05-23 14:38 UTC, MusaidAli commented
> See comments in old PR

previous pr comments resolved ,renamed variable.

2024-05-23 16:37 UTC, cgorantla reviewed
LGTM!   Syslog listener should be configured based on config received from Inventory, created this task for it https://opennms.atlassian.net/browse/LOK-2532

2024-05-23 17:11 UTC, smunir-onms commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/syslog/syslog-config.proto
> +  int32  syslog_port = 2;
resolved the posted [comment  ](https://github.com/OpenNMS-Cloud/lokahi/pull/1868#discussion_r1606998282)

2024-05-27 10:01 UTC, fooker requested changes

2024-05-27 10:01 UTC, fooker commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/syslog/syslog-config.proto
> +  int32  syslog_port = 2;
`listen_address`

2024-05-27 10:01 UTC, fooker commented on shared-lib/protobuf/src/main/proto/syslog-config.proto
> +  int32  syslog_port = 2;
`listen_address`

2024-05-27 12:24 UTC, MusaidAli commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/ConfigUpdateService.java
> +        } catch (Exception e) {
what is suggestion here .

2024-05-27 12:30 UTC, MusaidAli commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/syslogconfig/SyslogConfigBean.java
> +    public String getListenAddress() {
resolved.

2024-05-27 12:30 UTC, MusaidAli commented on shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/syslog/syslog-config.proto
> +  int32  syslog_port = 2;
removed used in protobuf.same file

2024-05-27 12:30 UTC, MusaidAli commented on shared-lib/protobuf/src/main/proto/syslog-config.proto
> +  int32  syslog_port = 2;
renamed.

2024-06-11 15:00 UTC, closed without merging