LOK-2499: Assign Monitored Entity ID to Monitored Service in GRPC interface
OpenNMS-Cloud/lokahi pull request #1900
Opened 2024-05-31 11:33 UTC by smunir-onms

## Description
Add a field monitoredEntityId to MonitoredServiceDTO in monitoredService.proto containing the monitored entity ID for the particular service. Alter all creations of MonitoredServiceDTO to fill the field.

To determine the correct value, create a static helper method that creates a reproducible monitored entity ID and use it to fill the property and also create the IDs in the MonitoredEntityProvider implementation.

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2499

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-06-03 15:42 UTC, aurang-zeb313 reviewed
LGTM.

2024-06-04 11:04 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/taskset/response/ScannerResponseService.java
> +                .build();
I don't think we need to touch this code. It's just a very strange way to transport the tenant into the create method.

2024-06-04 11:07 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/model/DiscoveryMonitoredEntityProvider.java
> +    }
This in not sufficient for multiple reasons:
- The monitored entity ID we need in the DTO must be fully qualified (it must include the provider id prefix - see `MonitoredEntity#getId()`)
- The triple of (tenantId, locationId and serviceName) is not unique: There can be multiple nodes with the same service name, there can be multiple interfaces on the same node with the same service name and in future, there can be multiple services with the name on the same interface - using the service id is sufficient here.

2024-06-05 11:21 UTC, smunir-onms commented
> The `monitored_entity_id` field is not set in the mappers and therefore missing in almost all query responses. You have to update the mapper or find a clever way to inject the value somehow (i.e. you can try and add a method to the monitored service entity)

Hi @fooker, the monitoredEntityId is added in the MonitoredService Entity class, and MonitoredServiceMapper Impl is updated accordingly.

2024-06-05 11:27 UTC, smunir-onms commented on inventory/main/src/main/java/org/opennms/horizon/inventory/model/DiscoveryMonitoredEntityProvider.java
> +    }
OK, now serviceId is used, so MonitoredEntity#getId() would be like "discovery:entity:{serviceId} is that fine?

2024-06-07 09:24 UTC, fooker requested changes

2024-06-07 09:24 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/model/DiscoveryMonitoredEntityProvider.java
> +    }
Why is this required?

2024-06-07 09:24 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/model/MonitoredService.java
> +    private String monitoredEntityId;
Where is this set? I think this needs to be a `getMonitoredEntityId` method which calls the provider to get the return value.

2024-06-07 09:24 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitoredServiceService.java
> +    public MonitoredService createSingle(String monitorType, IpInterface ipInterface) {
Changing the signature is required, but not part of this issue. Is this a git-fuckup somehow?

2024-06-07 10:24 UTC, smunir-onms commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitoredServiceService.java
> +    public MonitoredService createSingle(String monitorType, IpInterface ipInterface) {
No, as I added a commit for LOK-2574,  it could be in the new branch/PR whereas I accommodated the changes here.

2024-06-07 10:41 UTC, smunir-onms commented on inventory/main/src/main/java/org/opennms/horizon/inventory/model/DiscoveryMonitoredEntityProvider.java
> +    }
This is not required, as a suggestion I asked in the last [comment](https://github.com/OpenNMS-Cloud/lokahi/pull/1900#discussion_r1627570669). Ok, I turn it to just return Long.toString(serviceId);

2024-06-07 11:11 UTC, smunir-onms commented on inventory/main/src/main/java/org/opennms/horizon/inventory/model/MonitoredService.java
> +    private String monitoredEntityId;
This is the confusion, when I started, changes as per the task description, I was not sure where this would be used, I think something missed to be addressed. Need clarification.

2024-06-12 11:24 UTC, fooker requested changes

2024-06-12 11:24 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/monitoring/MonitoredEntity.java
> +
Remove newline

2024-06-12 11:24 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitoredServiceService.java
> +    public MonitoredService createSingle(String monitorType, IpInterface ipInterface) {
Then at least switch the parameters

2024-06-12 11:24 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitoredServiceService.java
> -            MonitoredService monitoredService = mapper.dtoToModel(newMonitoredService);
`dtoToModel` can be removed then?

2024-06-12 11:49 UTC, smunir-onms commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitoredServiceService.java
> -            MonitoredService monitoredService = mapper.dtoToModel(newMonitoredService);
Yes, previously the mapper was transforming just tenantId;
![image](https://github.com/OpenNMS-Cloud/lokahi/assets/157733753/e5adbb82-d0c1-42bd-bc52-d2997a8ec597)

2024-06-12 11:57 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitoredServiceService.java
> -            MonitoredService monitoredService = mapper.dtoToModel(newMonitoredService);
I mean, can it be removed from the Mapper class?

2024-06-12 11:58 UTC, smunir-onms commented on inventory/main/src/main/java/org/opennms/horizon/inventory/monitoring/MonitoredEntity.java
> +
newline removed.

2024-06-12 12:10 UTC, smunir-onms commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitoredServiceService.java
> -            MonitoredService monitoredService = mapper.dtoToModel(newMonitoredService);
You are right, it can be, so removed.

2024-06-12 12:28 UTC, fooker approved these changes

2024-06-12 13:12 UTC, merged