Updated Unit Test for MonitoringPolicies
OpenNMS-Cloud/lokahi pull request #1903
Opened 2024-05-31 13:17 UTC by faizanjanjua

## Description

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-XXXX

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-05-31 17:11 UTC, Shahbaz-dataq reviewed
Just a small change

2024-05-31 17:12 UTC, Shahbaz-dataq commented on ui/tests/MonitoringPolicies/monitoringPolicies.test.ts
>      expect(store.selectedPolicy).toBeTruthy()
Create a `defaultPolicy` with wrapper just like in `monitoringPolicyStore` and check it here for `toBeStrickEqual`

2024-05-31 17:18 UTC, faizanjanjua commented on ui/tests/MonitoringPolicies/monitoringPolicies.test.ts
>      expect(store.selectedPolicy).toBeTruthy()
done

2024-05-31 17:24 UTC, Shahbaz-dataq approved these changes
Looks good.

2024-05-31 18:29 UTC, synqotik requested changes
Looks good, just a few small changes.

2024-05-31 18:29 UTC, synqotik commented on ui/src/containers/MonitoringPolicies.vue
> +            data-test="MonitoringPoliciesTable"
Indent 2 spaces

2024-05-31 18:29 UTC, synqotik commented on ui/src/containers/MonitoringPolicies.vue
> +            data-test="MonitoringPoliciesDetailPanel"
Indent 2 spaces

2024-05-31 18:29 UTC, synqotik commented on ui/tests/MonitoringPolicies/monitoringPolicies.test.ts
> +
Remove blank line, here and at end of this definition

2024-05-31 18:29 UTC, synqotik commented on ui/tests/MonitoringPolicies/monitoringPolicies.test.ts
> +  test('Test if the create-policy-btn exist' , () => {
`exist` -> `exists`

2024-05-31 18:29 UTC, synqotik commented on ui/tests/MonitoringPolicies/monitoringPolicies.test.ts
> +  test('Test if the MonitoringPoliciesTable component to exist' , () => {
`to exist` -> `exists`

2024-05-31 18:29 UTC, synqotik commented on ui/tests/MonitoringPolicies/monitoringPolicies.test.ts
> +  test('Test if the MonitoringPoliciesDetailPanel component to exist' , () => {
`to exist` -> `exists`

2024-06-03 09:17 UTC, faizanjanjua commented on ui/tests/MonitoringPolicies/monitoringPolicies.test.ts
> +  test('Test if the create-policy-btn exist' , () => {
done

2024-06-03 13:02 UTC, synqotik approved these changes

2024-06-03 13:12 UTC, merged