LOK-2547:  Service Discovery - parsing and nice display of Discovery …
OpenNMS-Cloud/lokahi pull request #1910
Opened 2024-06-04 13:01 UTC by Syed-Bilal-Haider-Dataq

…Targets

## Description
In the Service Discovery configuration panel, Discovery Targets is just a textbox where user can enter hostnames, IP address or IP ranges, separated by either comma, semicolon or line break.

When user saves a discovery, we should parse out that string, break it up into a string array, then when this panel is displayed, it should have each item on its own line, with any commas or semicolons removed.
## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2547

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-06-04 14:33 UTC, Shahbaz-dataq commented on ui/src/components/Discovery/DiscoveryMetaInformation.vue
> +
Remove line break

2024-06-04 14:35 UTC, Shahbaz-dataq commented on ui/src/components/Discovery/DiscoveryMetaInformation.vue
> +
Remove line break

2024-06-04 14:36 UTC, Shahbaz-dataq commented on ui/src/components/Discovery/DiscoveryMetaInformation.vue
> +
Remove line break

2024-06-04 14:56 UTC, Shahbaz-dataq commented on ui/src/components/Discovery/DiscoveryMetaInformation.vue
> +  const parsedTargets = discoveryTargets?.split(/[\n,;/]+/)
Remove `/` from this regex as it will never let the user to enter IP range

2024-06-04 14:58 UTC, Shahbaz-dataq commented on ui/src/types/discovery.d.ts
> +  discoveryTargets?: string | string[];
Make it just `string[]` if their is only one string we will send it in Array.

2024-06-04 18:25 UTC, synqotik requested changes
Added some comments.

2024-06-04 18:25 UTC, synqotik commented on ui/src/components/Discovery/DiscoveryMetaInformation.vue
> +              <p>Services associate with discovery.</p>
Should be `associated`

2024-06-04 18:25 UTC, synqotik commented on ui/src/components/Discovery/DiscoveryMetaInformation.vue
> +function parseDiscoveriesTargets(discoveryTargets: string | undefined): string[]  {
This and the other `function` below should be changed to be in `const name = () => {}` style instead, so we are consistent.

Also name should be `parseDiscoveryTargets`, and should be `(discoveryTargets?: string)`

2024-06-04 18:25 UTC, synqotik commented on ui/src/components/Discovery/DiscoveryMetaInformation.vue
> +  if (!discoveryTargets) return []
Use braces around `if` statement blocks, even if it's just one line.

2024-06-04 18:25 UTC, synqotik commented on ui/src/components/Discovery/DiscoveryMetaInformation.vue
> +    .map((target: string) => target)
This `.map` doesn't do anything. Though maybe you could call `trim(target)` here.

2024-06-05 16:11 UTC, synqotik approved these changes
One more item to fix, then you can merge.

2024-06-05 16:11 UTC, synqotik commented on ui/src/components/Discovery/DiscoveryMetaInformation.vue
> +function convertDiscoveryTargetsToString() {
Convert this to `const convertDiscoveryTargetsToString() = () => {}` format.

2024-06-06 10:56 UTC, Shahbaz-dataq approved these changes
Looks good

2024-06-06 13:22 UTC, merged