BE : LOK-2545 : Follow Up to LOK-2503 task, requires UI requirement
OpenNMS-Cloud/lokahi pull request #1915
Opened 2024-06-05 13:52 UTC by Junaid-Khan-Nant

## Description
Any is not supported in a GraphQL response. You have multiple routes to choose from here:

Serialize the config to JSON and make the field a string
Go all in and figure out how to represent arbitrary scalar data in GraphQL (maybe a JsonNode could work)
Create a follow up issue which we can defere until we know what UI needs there

## Jira link(s)
https://opennms.atlassian.net/browse/LOK-2545

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-06-07 09:19 UTC, fooker requested changes
IMO, this does not solve the Issue we have here. There is no need to change the type of the proto send to minion but we need to serialize for the GraphQL interfaces.

2024-06-07 09:19 UTC, fooker commented on rest-server/src/main/java/org/opennms/horizon/server/model/inventory/MonitoredEntityDTO.java
> -    // public Any config; // TODO : need to be change LOK-2545
We still need this to be added. That was the whole point of the issue after all.

2024-06-07 09:19 UTC, fooker commented on shared-lib/inventory/src/main/proto/monitoredEntitySearch.proto
> +  string config = 4;
I don't see why we need to change the proto here. Using `Any` in protobuf is perfectly fine.

2024-06-07 09:19 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/monitoring/MonitoredEntityService.java
> +                        .setConfiguration(getMonitorConfiguration(entity.getType(), entity.getConfig()))
This is confusing. I don't understand why the roundtrip for using JSON in the monitored entity API is required.
From my understanding the transformation from `Any` to JSON is only required in the GraphQL interface.

2024-06-07 09:19 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/monitoring/MonitoredEntityService.java
> +        switch (monitorType) {
The generic implementation must not depend on the monitor type. But I think this is not required anyways.

2024-06-12 11:44 UTC, fooker requested changes
Please remove the commented out line. I still would like to see this not transported as a string. Maybe @scthompsonopen has a clue how this works.

2024-06-12 12:21 UTC, Junaid-Khan-Nant commented
> Please remove the commented out line. I still would like to see this not transported as a string. Maybe @scthompsonopen has a clue how this works.

With response type as a JsonObject :
![Screenshot from 2024-06-12 17-13-02](https://github.com/OpenNMS-Cloud/lokahi/assets/157728179/e77d311e-fc86-4257-9e7d-f508561d14f7)
With response type as a string :
![str](https://github.com/OpenNMS-Cloud/lokahi/assets/157728179/9672e36e-66b8-4afe-be86-b44c102e61f8)

2024-06-12 12:48 UTC, fooker requested changes

2024-06-12 12:48 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/mapper/MonitorEntityMapper.java
> +    Logger LOGGER = LoggerFactory.getLogger(MonitorEntityMapper.class);
LOGGER is not used.

2024-06-12 12:48 UTC, fooker commented on shared-lib/inventory/src/main/proto/monitoredEntitySearch.proto
> +  google.protobuf.Struct config = 4;
By comments to remove, I mean this.

2024-06-12 12:48 UTC, fooker commented on rest-server/src/main/java/org/opennms/horizon/server/model/inventory/MonitoredEntityDTO.java
> +    public String config;
By comments to remove, I mean this.

2024-06-17 09:37 UTC, fooker commented
@Junaid-Khan-Nant I will convert this to a draft and move this to backlog until we have clear requirements.

2024-08-27 14:27 UTC, closed without merging