FE: Monitoring Policies - unit tests for MonitoringPolicyBasicInforma…
OpenNMS-Cloud/lokahi pull request #1918
Opened 2024-06-06 15:06 UTC by faizanjanjua

…tionEditAddForm

## Description
Add unit tests for MonitoringPolicyBasicInformationEditAddForm.vue

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2580

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-06-06 17:04 UTC, Shahbaz-dataq reviewed
Approve

2024-06-06 18:46 UTC, synqotik requested changes
Added a few comments.

Also, wait to merge this until I have merged LOK-2576. Then get latest from `develop`, you will probably need to make a few small changes:

- `Policy` has been replaced with `@/types/policies/MonitoringPolicy`
- there are some more required fields in that, so you'll need to add to `mockMonitoringPolicy`

2024-06-06 18:46 UTC, synqotik commented on ui/tests/MonitoringPolicies/MonitoringPolicyBasicInformationEditAddForm.test.ts
> +  beforeEach(()=>{
Should be `beforeEach(() => {` (spaces around arrow)

2024-06-06 18:46 UTC, synqotik commented on ui/tests/MonitoringPolicies/MonitoringPolicyBasicInformationEditAddForm.test.ts
> +    const policyDesriptionInput = wrapper.findComponent('[data-test="policy-Description"]');
`policyDesriptionInput` -> `policyDescriptionInput`

2024-06-06 18:46 UTC, synqotik commented on ui/tests/MonitoringPolicies/MonitoringPolicyBasicInformationEditAddForm.test.ts
> +  test('ormattedTags computed property returns correctly formatted tags', async () => {
`formattedTags`

2024-06-06 18:46 UTC, synqotik commented on ui/tests/MonitoringPolicies/MonitoringPolicyBasicInformationEditAddForm.test.ts
> +    expect(policyNameInput.vm.modelValue).toBe(mockMonitoringPolicy.name); // Verify initial val
Remove comment, here and elsewhere

2024-06-06 18:46 UTC, synqotik commented on ui/tests/MonitoringPolicies/MonitoringPolicyBasicInformationEditAddForm.test.ts
> +    let store = useMonitoringPoliciesStore()
If you use `beforeEach`, then you can add `let store` inside `describe` and then inside `beforeEach` can be `store = useMonitoringPoliciesStore()`. Then remove the `let store` inside all the `test` blocks.

**or else** remove the `beforeEach`, and have have `const store = useMonitoringPoliciesStore()` inside each `test` block.

2024-06-07 13:08 UTC, synqotik approved these changes

2024-06-07 16:27 UTC, merged