LOK-2570-GraphQL Node Service - add pagination and sorting for findAllNodes
OpenNMS-Cloud/lokahi pull request #1921
Opened 2024-06-07 12:00 UTC by Mohammad-Junid

## Description
Need to add pagination and sorting to the findAllNodes query of the GraphQLNodeService, or add a separate call.

This is needed by the front end, since we will need to handle thousands of nodes.

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2570

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-06-07 12:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1921) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1921) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenNMS-Cloud/lokahi?pullRequest=1921) it.</sub>

2024-06-07 13:11 UTC, synqotik commented on inventory/main/src/main/java/org/opennms/horizon/inventory/repository/NodeRepository.java
> +            @Param("searchLabelOrAliad") String searchLabelOrAliad,
Should be: `searchLabelOrAlias`

2024-06-07 14:48 UTC, Mohammad-Junid commented on inventory/main/src/main/java/org/opennms/horizon/inventory/repository/NodeRepository.java
> +            @Param("searchLabelOrAliad") String searchLabelOrAliad,
Got it . Thanks

2024-06-10 12:34 UTC, aurang-zeb313 requested changes

2024-06-10 12:34 UTC, aurang-zeb313 commented on inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/NodeStepDefinitions.java
> +            "set sorting request of  sortBy {string} , ascending sort flag {string} , search typ {string} and search value {string}")
replace the word typ to type.

2024-06-10 12:34 UTC, aurang-zeb313 commented on inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/node.feature
> +    Then fetch node pagable response and verify that total 1 node are retrieved in response
Replace typ with type

2024-06-10 13:31 UTC, Mohammad-Junid commented
Default search 
![image](https://github.com/OpenNMS-Cloud/lokahi/assets/161852172/0cc50b08-2941-4506-affb-f569d52b8803)

Search with Label Like  
![image](https://github.com/OpenNMS-Cloud/lokahi/assets/161852172/48e7b513-0ce8-420d-bb3a-7ef636a32182)
Search with tag id  
![image](https://github.com/OpenNMS-Cloud/lokahi/assets/161852172/e3272704-3c87-4bff-a4f3-35e0d430abb4)
Sort by **nodeLabel** 
![image](https://github.com/OpenNMS-Cloud/lokahi/assets/161852172/4745635c-edbd-4191-8e56-f8da3c8dfa22)

2024-06-10 13:58 UTC, Mohammad-Junid commented on inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/NodeStepDefinitions.java
> +            "set sorting request of  sortBy {string} , ascending sort flag {string} , search typ {string} and search value {string}")
Done

2024-06-11 13:42 UTC, smunir-onms commented on shared-lib/inventory/src/main/proto/nodeService.proto
> +message NodeSearchResponse {
to avoid confusion with the model "NodeSearchResponse", please rename it to NodeSearchResponseDTO

2024-06-11 15:23 UTC, smunir-onms commented on inventory/main/src/main/java/org/opennms/horizon/inventory/repository/NodeRepository.java
> +    Page<Node> findByTenantIdAndNodeLabelOrAliasLikeOrTagIds(
I suggest splitting down the query based on isSearchStringValue, to lighten the query "isSearchStringValue" shouldn't be included in the query.

2024-06-11 16:38 UTC, Mohammad-Junid commented on inventory/main/src/main/java/org/opennms/horizon/inventory/repository/NodeRepository.java
> +    Page<Node> findByTenantIdAndNodeLabelOrAliasLikeOrTagIds(
Done

2024-06-11 16:38 UTC, Mohammad-Junid commented on shared-lib/inventory/src/main/proto/nodeService.proto
> +message NodeSearchResponse {
Done

2024-06-11 16:38 UTC, Mohammad-Junid commented on inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/node.feature
> +@node-scan
Done

2024-06-11 17:44 UTC, cgorantla approved these changes
LGTM!

2024-06-12 09:20 UTC, aurang-zeb313 approved these changes

2024-06-12 09:24 UTC, merged