ja/jira/LOK-2577
OpenNMS-Cloud/lokahi pull request #1925
Opened 2024-06-10 13:47 UTC by jahanzebdataq

## Description
Define UEI(e.g. lowThresholdExceeded,highThresholdExceeded,highThresholdRearmed,lowThresholdRearmed) for metric threshold while creating monitoring policy.

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2577

2024-06-12 11:35 UTC, jahanzebdataq commented
Screen shots
![Screenshot from 2024-06-12 16-33-57](https://github.com/OpenNMS-Cloud/lokahi/assets/159922670/032dba50-afab-4a54-b0f0-578f041dc846)
![Screenshot from 2024-06-12 16-33-37](https://github.com/OpenNMS-Cloud/lokahi/assets/159922670/6ab3b028-7be3-47ac-b69c-a6e50ead6407)
![Screenshot from 2024-06-12 16-33-11](https://github.com/OpenNMS-Cloud/lokahi/assets/159922670/583a102b-45b1-486c-aa78-9689d8282cc8)
![Screenshot from 2024-06-12 16-32-53](https://github.com/OpenNMS-Cloud/lokahi/assets/159922670/c42c7de2-e7f7-4463-9233-ae558c118e9d)
![Screenshot from 2024-06-12 16-32-10](https://github.com/OpenNMS-Cloud/lokahi/assets/159922670/1f4433cd-fff7-4417-845a-056863533135)
![Screenshot from 2024-06-12 16-31-56](https://github.com/OpenNMS-Cloud/lokahi/assets/159922670/0b89ffe1-5b2f-4a38-9513-702e33839a4a)
![Screenshot from 2024-06-12 16-31-38](https://github.com/OpenNMS-Cloud/lokahi/assets/159922670/e8b7c239-8edc-41d6-a353-dd1fa248506a)

2024-06-18 08:36 UTC, fooker requested changes

2024-06-18 08:36 UTC, fooker commented on alert/src/main/java/org/opennms/horizon/alertservice/service/MonitorPolicyService.java
> +            eventDefinition.setId(1140L);
This hard-coded value seems suspicious.

2024-06-19 08:42 UTC, jahanzebdataq commented on alert/src/main/java/org/opennms/horizon/alertservice/service/MonitorPolicyService.java
> +            eventDefinition.setId(1140L);
As per discussion with @cgorantla for now we are using hard-coded entry for trigger event

2024-06-24 14:03 UTC, cgorantla reviewed
Possible to add this alert conditions in DB itself ?

2024-06-25 12:34 UTC, jahanzebdataq commented
> Possible to add this alert conditions in DB itself ?

Added

2024-07-10 13:02 UTC, jahanzebdataq commented
Merged these changes in LOK-2540

2024-07-10 13:02 UTC, closed without merging