FE: Monitoring Policies - unit tests for MonitoringPoliciesRules
OpenNMS-Cloud/lokahi pull request #1926
Opened 2024-06-10 14:39 UTC by faizanjanjua

## Description
Add unit tests for MonitoringPoliciesRules.vue

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2582

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-06-11 17:12 UTC, Shahbaz-dataq reviewed
Add a new test where you should check if the policy has no rules. Then `MonitoringPoliciesCreateAlertRules` should be loaded

2024-06-11 17:12 UTC, Shahbaz-dataq commented on ui/tests/MonitoringPolicies/MonitoringPolicesRules.test.ts
> +beforeEach(() => {
Small changes

2024-06-11 17:12 UTC, Shahbaz-dataq commented on ui/tests/MonitoringPolicies/MonitoringPolicesRules.test.ts
> +beforeEach(() => {
Run `yarn lint:fix` to fix lint issues

2024-06-11 17:12 UTC, Shahbaz-dataq commented on ui/tests/MonitoringPolicies/MonitoringPolicesRules.test.ts
> +  test('renders MonitoringPoliciesCreateAlertRules when policy has no rules', async () => {
test name should be `renders MonitoringPoliciesCreateAlertRules when policy has rules`

2024-06-11 17:12 UTC, Shahbaz-dataq commented on ui/src/components/MonitoringPolicies/MonitoringPoliciesRules.vue
> +                 data-test="handleCancel-btn"
Remove extra space in start

2024-06-13 11:10 UTC, Shahbaz-dataq reviewed
Approve. Just make these changes

2024-06-13 12:59 UTC, faizanjanjua commented on ui/tests/MonitoringPolicies/MonitoringPolicesRules.test.ts
> +    let isCheckAlertRuleCondition=   await wrapper.vm.isCheckAlertRule
thanks resolved

2024-06-13 12:59 UTC, faizanjanjua commented on ui/tests/MonitoringPolicies/MonitoringPolicesRules.test.ts
> +    let isCheckAlertRuleCondition=   await wrapper.vm.isCheckAlertRule
thanks resolved

2024-06-20 17:50 UTC, synqotik requested changes
A couple of comments.

2024-06-20 17:50 UTC, synqotik commented on ui/tests/MonitoringPolicies/MonitoringPolicesRules.test.ts
> +  beforeEach(() => {
If you are going to create a store inside the tests below, then remove this `beforeEach` since it's never used.

2024-06-20 17:50 UTC, synqotik commented on ui/tests/MonitoringPolicies/MonitoringPolicesRules.test.ts
> +    store.selectedPolicy = {
Make this monitored policy data a constant outside of all tests, then do a `cloneDeep` when using it in the test, and just change the items in the data that are different.

2024-06-24 11:20 UTC, faizanjanjua commented on ui/tests/MonitoringPolicies/MonitoringPolicesRules.test.ts
> +  beforeEach(() => {
Thanks Resolved

2024-06-25 19:21 UTC, synqotik approved these changes

2024-06-25 19:21 UTC, merged