FE: Node Details: Graphs for Node CPU and Memory
OpenNMS-Cloud/lokahi pull request #1933
Opened 2024-06-11 14:19 UTC by Shahbaz-dataq

## Description
Implement line graphs for CPU and Memory utilization for the Node Status page.

Use the Graphs/LineGraph.vue component. Will need to determine what the metric names (from the back end / Cortex labels) are for these 2 items. See the Graphs button in the SNMP Interfaces table on Node Status page for example.

Implement the Download and Refresh icons. Download doesn’t need to work yet; Refresh can refresh the graphQL call for the metric data.

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2289

2024-06-11 14:40 UTC, Syed-Bilal-Haider-Dataq commented on ui/src/components/NodeStatus/NodeGraph.vue
> +  if (hasMetricData.value) return
Add an "if" block.
 ```
if (hasMetricData.value) {
return
}
```

2024-06-11 14:45 UTC, Syed-Bilal-Haider-Dataq commented on ui/src/components/NodeStatus/NodeGraph.vue
> +      <LineGraphForUtilizations ref="graphRef" :graph="graphProps" :type="$props.type" @has-data="displayEmptyMsgIfNoData" />
Break into multiple lines for clear understanding.
 <LineGraphForUtilizations 
ref="graphRef" :graph="graphProps" 
:type="$props.type" 
@has-data="displayEmptyMsgIfNoData" />

2024-06-11 14:46 UTC, Syed-Bilal-Haider-Dataq commented on ui/src/components/NodeStatus/NodeGraph.vue
> +          <FeatherButton v-bind="attrs" v-on="on" icon="Refresh" class="refresh-icon" @click="graphRef.loadMetricDataAndRenderGraph()">
Break into multiple lines for clear understanding.
  <FeatherButton
   v-bind="attrs" v-on="on" 
   icon="Refresh" class="refresh-icon" 
   @click="graphRef.loadMetricDataAndRenderGraph()"
>

2024-06-11 14:52 UTC, Syed-Bilal-Haider-Dataq commented on ui/src/components/Graphs/LineGraphForUtilizations.vue
> +let chart: any = {}
Use a chart with the "ref" attribute.
const chart: any = ref({})

2024-06-11 16:51 UTC, Shahbaz-dataq commented on ui/src/components/NodeStatus/NodeGraph.vue
> +  if (hasMetricData.value) return
Done

2024-06-11 16:53 UTC, Shahbaz-dataq commented on ui/src/components/NodeStatus/NodeGraph.vue
> +import { GraphProps } from '@/types/graphs';
Done

2024-06-11 16:55 UTC, Shahbaz-dataq commented on ui/src/components/NodeStatus/NodeGraph.vue
> +          <FeatherButton v-bind="attrs" v-on="on" icon="Refresh" class="refresh-icon" @click="graphRef.loadMetricDataAndRenderGraph()">
Done

2024-06-12 20:32 UTC, synqotik requested changes
I've thought about this a bit more. Let's use `LineGraph` and make updates to it if needed. I'd like to just standardize using one component for all these type of graphs if possible.

Let's use a real metric instead of dummy data. It does seem like adding dummy data is more involved. If the metrics for CPU and Memory utilization don't work or don't exist yet, then use another one and put a TODO comment to fix it.

I think `LineGraph` already has a download button, so we don't need that in `NodeGraph`. 

You could add that `loadMetricDataAndRenderGraph` to `LineGraph` and either add a refresh button to `LineGraph` or to `NodeGraph` to cal that function.

In `NodeGraph`, add a prop like `metricName`, this will be the metric to query, then pass it in the `graphProps.metrics` to `LineGraph`

`NodeGraph` `type` prop should be same as `LineGraph` `prop.type`, it's `'bytes'` or `'percentage'`.

We can always update CSS styles in `LineGraph` if needed, to be conditional based on props passed in (i.e. whether it's in a modal or not). I think you can set `width` in `NodeStatusTableContent.vue` in the `div` enclosing the `NodeGraph`. It's ok if styling isn't perfect for now.

2024-06-13 15:52 UTC, synqotik approved these changes
LGTM! Thanks for changes.

2024-06-13 16:48 UTC, merged