Add nodeAlias property to topNNode model
OpenNMS-Cloud/lokahi pull request #1936
Opened 2024-06-12 14:24 UTC by faizanjanjua

## Description
LOK-2239: Add nodeAlias property to topNNode model
DONE
 will add node alias as part of model, when available show node alias on Top Node table on the Home screen ( when not available use label)

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2304

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-06-12 16:46 UTC, Shahbaz-dataq commented on ui/src/types/graphql.ts
> +
Remove these extra spaces

2024-06-12 16:46 UTC, Shahbaz-dataq commented on ui/src/types/graphql.ts
> +
Same remove extra spaces

2024-06-12 19:20 UTC, synqotik requested changes

2024-06-12 19:20 UTC, synqotik commented on ui/src/components/Dashboard/DashboardTopNodesTable.vue
> +              <td>{{ topNode.nodeAlias == "" ? topNode.nodeLabel  : topNode.nodeAlias  }}</td>
Can just be:

```
topNode.nodeAlias || topNode.nodeLabel
```

2024-06-14 20:17 UTC, synqotik approved these changes
LGTM

2024-06-17 19:54 UTC, merged