BE: LOK-2498 : Create a timer task to re-send monitor tasks.
OpenNMS-Cloud/lokahi pull request #1937
Opened 2024-06-13 10:36 UTC by Junaid-Khan-Nant

## Description
Create a timer that re-publishes all tasks for all tenants/locations on a regular interval.
The timer can just call MonitoredEntityService#publishTaskSet.

## Jira link(s)
https://opennms.atlassian.net/browse/LOK-2498

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-06-14 10:52 UTC, fooker requested changes
This is a little bit basic. The service should scan over **all** tenants and **all** of each tenant. The interval should be configurable.

Where is the service initialized? Can this be a spring boot service?

2024-06-14 10:52 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/taskset/publisher/MonitorTaskTimer.java
> +    private void republished(String tenantId) {
```suggestion
    private void republish(String tenantId) {
```

2024-06-14 12:19 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/taskset/publisher/MonitorTaskTimer.java
> +    private void republished(String tenantId) {
Done.

2024-06-17 09:39 UTC, fooker commented
> > This is a little bit basic. The service should scan over **all** tenants and **all** of each tenant. The interval should be configurable.
> > Where is the service initialized? Can this be a spring boot service?
> 
> @fooker, I am not sure from where it should be invoke. Do u have any suggestion about this?

I don't know, too. I guess this can be a spring service that is started on application boot.

2024-06-21 12:27 UTC, fooker requested changes

2024-06-21 12:27 UTC, fooker commented on inventory/main/src/main/resources/application.yml
> -    web:
??

2024-06-21 12:27 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitorTaskTimerService.java
> +        if (executed) {
This limits the whole thing to a single execution.

2024-06-21 12:27 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitorTaskTimerService.java
> +        stop();
Why stop on each run?

2024-06-21 12:27 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitorTaskTimerService.java
> +        }
Forcefully shutting down the scheduler is not required. Just drain it and let it die.

2024-06-21 12:27 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitorTaskTimerService.java
> +    public void stop() {
Need this to be hooked to an event, too.

2024-06-21 12:27 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitorTaskTimerService.java
> +                .forEach(loc -> monitoredEntityService.publishTaskSet(loc.getTenantId(), loc.getId()));
Why flat-mapping over the locations again. `list` already contains all the locations you need.

2024-06-21 12:27 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitorTaskTimerService.java
> +        }
No need to warn here. Just make sure your code works on an empty list, too.

2024-06-21 12:27 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitorTaskTimerService.java
> +    public void executeTimer() {
```suggestion
    public void start() {
```

2024-06-21 14:21 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitorTaskTimerService.java
> +    public void executeTimer() {
Done.

2024-06-21 14:21 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitorTaskTimerService.java
> +        }
Done.

2024-06-21 14:21 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitorTaskTimerService.java
> +                .forEach(loc -> monitoredEntityService.publishTaskSet(loc.getTenantId(), loc.getId()));
Done.

2024-06-21 14:21 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitorTaskTimerService.java
> +    public void stop() {
Done.

2024-06-21 14:21 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitorTaskTimerService.java
> +        }
Done.

2024-06-21 14:21 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitorTaskTimerService.java
> +        stop();
Done.

2024-06-21 14:22 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitorTaskTimerService.java
> +        if (executed) {
Done.

2024-06-21 14:22 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/resources/application.yml
> -    web:
Done.

2024-06-25 14:04 UTC, fooker requested changes

2024-06-25 14:04 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/monitoring/MonitoredEntityService.java
> +        log.info("PublishTaskSet executed with tenantId :::: {}", tenantId);
```suggestion
        log.info("PublishTaskSet executed with tenantId={}, locationId={}", tenantId, locationID);
```

2024-06-25 14:04 UTC, fooker commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitorTaskTimerService.java
> +public class MonitorTaskTimerService {
Call it `MonitoredEntityTimer` and move it to the `monitoring` package.

2024-06-25 14:52 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/monitoring/MonitoredEntityService.java
> +        log.info("PublishTaskSet executed with tenantId :::: {}", tenantId);
Done

2024-06-25 14:53 UTC, Junaid-Khan-Nant commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitorTaskTimerService.java
> +public class MonitorTaskTimerService {
Done

2024-06-26 11:51 UTC, fooker approved these changes

2024-06-26 12:00 UTC, merged