LOK-2500 - Select correct instance for queries in node status
OpenNMS-Cloud/lokahi pull request #1939
Opened 2024-06-13 18:25 UTC by smunir-onms

## Description
Currently, the monitor execution results are stored with the INSTANCE label set to the Monitored Entity ID of the executed monitor. The queries to determine the node status in NodeStatusService do not reflect that.

Ensure the INSTACE field in the queries is set to the correct value.

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2500

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-06-14 10:49 UTC, fooker requested changes
While the changes are correct, they are incomplete. There is also `getNodeStatus` that needs fixing in a similar fashinon

2024-06-20 18:42 UTC, smunir-onms commented on rest-server/src/main/java/org/opennms/horizon/server/service/NodeStatusService.java
> -            return getStatusMetric(node.getId(), "azure-node-" + node.getId(), AZURE_MONITOR_TYPE, env)
not sure about azure node, if it will work as unique instance like the monitored service's entity id

2024-07-01 12:33 UTC, fooker commented on rest-server/src/main/java/org/opennms/horizon/server/service/NodeStatusService.java
> -            return getStatusMetric(node.getId(), "azure-node-" + node.getId(), AZURE_MONITOR_TYPE, env)
This is okay for now. Can you use the constant from `AzureMonitoredEntityProvider` as prefix and the Method `MonitoredEntity#joinId` to build the ID?

2024-07-01 12:56 UTC, smunir-onms commented on rest-server/src/main/java/org/opennms/horizon/server/service/NodeStatusService.java
> -            return getStatusMetric(node.getId(), "azure-node-" + node.getId(), AZURE_MONITOR_TYPE, env)
Sure, thanks!

2024-07-01 14:28 UTC, smunir-onms commented on rest-server/src/main/java/org/opennms/horizon/server/service/NodeStatusService.java
> -            return getStatusMetric(node.getId(), "azure-node-" + node.getId(), AZURE_MONITOR_TYPE, env)
Alright, thanks!

2024-07-01 14:57 UTC, smunir-onms commented on rest-server/src/main/java/org/opennms/horizon/server/service/NodeStatusService.java
> -            return getStatusMetric(node.getId(), "azure-node-" + node.getId(), AZURE_MONITOR_TYPE, env)
Change done, follow up issue created, please review and correct the description of the [issue](https://opennms.atlassian.net/browse/LOK-2653)

2024-07-02 12:19 UTC, fooker approved these changes

2024-07-02 12:20 UTC, merged