BE: Initial BFF for Windows Services by Node
OpenNMS-Cloud/lokahi pull request #1947
Opened 2024-06-21 16:37 UTC by Shahbaz-dataq

## Description
Create a BFF GraphQL endpoint for querying Windows Service inventory data by Node (tenant id / node id combination).

Should include pagination and sorting on at least the Name column (this can be a separate task if needed).

Should also support search on at least the Name column.

This can return mock data for now, if the actual data is not yet available in the database. We can open separate tasks for the actual data if needed.

Data will contain: Service Name, Service Type (Microsoft SQL Server, Internet Information Services, Active Directory, etc.), Node Id, Node Label, Node Alias, Description, Memory usage, Reachability, Uptime, status (Running, Not Running, Has Errors).

See https://opennms.atlassian.net/browse/LOK-2559 for example of type of data.

IMPORTANT NOTE for all these BFF items, they may be separate calls, or a single call where user passes in:

node id or else null for all nodes

a flag whether to get Windows Services or Hosted Services

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2592

2024-06-21 16:53 UTC, aurang-zeb313 requested changes
Please include screenshots from your tests.

2024-06-21 16:53 UTC, aurang-zeb313 commented on rest-server/src/main/java/org/opennms/horizon/server/service/grpc/InventoryClient.java
> +import org.opennms.horizon.inventory.dto.*;
Avoid using wildcards when importing

2024-06-21 16:53 UTC, aurang-zeb313 commented on inventory/main/src/main/java/org/opennms/horizon/inventory/model/WsService.java
> +
Avoid using wildcards when importing

2024-06-21 16:53 UTC, aurang-zeb313 commented on shared-lib/inventory/src/main/proto/wsmanService.proto
> +  WsServiceType serviceType = 5;
keep same format like service_type

2024-06-21 16:53 UTC, aurang-zeb313 commented on shared-lib/inventory/src/main/proto/wsmanService.proto
> +  WsEnvironmentType environmentType = 6;
keep same format

2024-06-21 17:09 UTC, smunir-onms commented on inventory/main/src/main/java/org/opennms/horizon/inventory/mapper/WsServiceMapper.java
> +    @Mapping(target = "node", source = "node")
No need to add mapping for the same attributes of the source and target

2024-06-21 17:09 UTC, smunir-onms commented on inventory/main/src/main/java/org/opennms/horizon/inventory/mapper/WsServiceMapper.java
> +    @Mapping(target = "nodeLabel", source = "nodeLabel")
same here

2024-06-21 17:21 UTC, Shahbaz-dataq commented
![Screenshot from 2024-06-21 22-12-15](https://github.com/OpenNMS-Cloud/lokahi/assets/159028986/dd0aaf58-bd79-4b65-a6f9-4c6d8e1250b6)
![Screenshot from 2024-06-21 22-15-48](https://github.com/OpenNMS-Cloud/lokahi/assets/159028986/0f8cf232-0a45-49f7-a345-ed20aa39a61d)
![Screenshot from 2024-06-21 22-08-55](https://github.com/OpenNMS-Cloud/lokahi/assets/159028986/28d9cb3a-a6f9-4c24-9296-9f9cf4de33aa)
![Screenshot from 2024-06-21 22-06-15](https://github.com/OpenNMS-Cloud/lokahi/assets/159028986/be6bf94b-34d0-48c3-a7a7-d401fca108ea)
![Screenshot from 2024-06-21 22-01-26](https://github.com/OpenNMS-Cloud/lokahi/assets/159028986/08c7a10f-dd78-4723-a54e-4cd61214ffb9)

2024-06-21 17:29 UTC, smunir-onms commented on shared-lib/inventory/src/main/proto/wsmanService.proto
> +}
please follow the convention for enums, capital letters with underscore _ 

```
enum WsServiceStatus {
  RUNNING = 0;
  NOT_RUNNING = 1;
  HAS_ERRORS = 2;
}
```

2024-06-21 17:36 UTC, smunir-onms commented on shared-lib/inventory/src/main/proto/wsmanService.proto
> +  string node_id = 3;
please change type of node_id from string to int64, update references 

`int64 node_id = 3;`

2024-06-24 15:39 UTC, smunir-onms commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/WsmanGrpcService.java
@Shahbaz-dataq as discussed, this should be a generic name like "ServiceInventoryGrpcService" as per the common model you created for Windows and Hosted services.

Further discussion is required with @cgorantla

2024-06-25 18:16 UTC, synqotik commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/WsmanGrpcService.java
> +        int pageSize = request.getPageSize() != 0 ? request.getPageSize() : PAGE_SIZE_DEFAULT;
Probably should be `> 0` instead of `!= 0` to screen out (erroneous) negative numbers.

2024-06-25 20:07 UTC, cgorantla reviewed
Looks fine.
How do we associate node info with Windows service here ?

I would opt to start with Windows discovery first and then have these services defined.

Also we may have to change some of this once we merge Monitored entities PR.

2024-06-25 20:07 UTC, cgorantla commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/WsmanGrpcService.java
> +            LOG.error("Error while creating response for ListServiceResponse");
Always log the exception

2024-06-25 20:07 UTC, cgorantla commented on inventory/main/src/main/java/org/opennms/horizon/inventory/model/WsService.java
> +    @ManyToOne(fetch = FetchType.EAGER)
don't think you need FetchType.EAGER here

2024-07-22 12:54 UTC, smunir-onms commented on inventory/main/src/main/resources/db/changelog/hs-0.1.0/tables/ws-service.xml
> +    <changeSet author="tbigg" id="0.1.0-node">
the author should be your GitHub username, id should be unique, like 0.1.0-ws-service-table

2024-07-30 18:19 UTC, cgorantla requested changes
Please work with @naeem-afzal to make sure you are not duplicating his work and understand  how to integrate wsman with existing monitored entity framework.

2024-07-30 18:19 UTC, cgorantla commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/WsmanGrpcService.java
> +            LOG.error(e.getLocalizedMessage());
have proper log message here.

2024-07-30 18:19 UTC, cgorantla commented on shared-lib/inventory/src/main/proto/wsmanService.proto
> +
we don't need any of the above, use existing monitor service status

2024-07-30 18:19 UTC, cgorantla commented on shared-lib/inventory/src/main/proto/wsmanService.proto
> +}
don't need separate Node message, have to use existing Node

2024-07-30 18:19 UTC, cgorantla commented on inventory/main/src/main/resources/db/changelog/hs-0.1.0/tables/ws-service.xml
> +                                 referencedTableName="node" referencedColumnNames="id"/>
Don't need a separate table for this. Use existing discovery table to persist wsman related services.

2024-08-13 11:54 UTC, closed without merging