LOK-2540: Create a service "metrics-threshold-processor" to handle cortex alert for metrics thresholds
OpenNMS-Cloud/lokahi pull request #1953
Opened 2024-06-25 10:47 UTC by aurang-zeb313

## Description
    - Will create alert in cortex ruler.
    - Expose web-hook API  to listen for alert notification when fired in cortex based  on define rule in cortex ruler.
    - Convert alert notification to events.

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2540

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-06-25 10:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1953) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1953) before we can accept your contribution.<br/>**2** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: jahanzebdataq<br/>:white_check_mark: Umairk95<br/>:x: aurang-zeb313<br/>:x: Mohammad-Junid<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenNMS-Cloud/lokahi?pullRequest=1953) it.</sub>

2024-06-26 12:17 UTC, smunir-onms commented on alert/src/main/java/org/opennms/horizon/alertservice/service/MonitorPolicyService.java
> +                    .findByEventUei("uei.opennms.org/threshold/highThresholdExceeded")
please use constant HIGH_THRESHOLD_EVENT_UEI

2024-07-04 01:15 UTC, cgorantla reviewed
Good work.  Looks good overall, some comments from my initial review. Will validate more.

2024-07-04 01:15 UTC, cgorantla commented on metrics-threshold-processor/src/main/java/org/opennms/metrics/threshold/MetricsThresholdProcessorApplication.java
> +@EnableCaching(proxyTargetClass = true)
do we need this ?

2024-07-04 01:15 UTC, cgorantla commented on metrics-threshold-processor/src/main/java/org/opennms/metrics/threshold/api/MetricsRulerExpressionGenerator.java
> +            default:
I think we should have a way to generate expression for any metric, we can take care of this in next iteration

2024-07-04 01:15 UTC, cgorantla commented on metrics-threshold-processor/src/main/java/org/opennms/metrics/threshold/config/KafkaConfig.java
> +        System.out.println("Compact: " + topic.getCompact());
log, not stdout

2024-07-04 01:15 UTC, cgorantla commented on minion/assembly/server-ca.crt
> +-----BEGIN CERTIFICATE-----
remove

2024-07-05 09:02 UTC, aurang-zeb313 commented on alert/src/main/java/org/opennms/horizon/alertservice/service/MonitorPolicyService.java
> +                thresholdRuleProducer.deleteThresholdAlertRule(metricsThresholdAlertRule);
To create an alert in Cortex Ruler, you need the following:
    Namespace of Alert: This corresponds to the policy name that will be used.
    Alert Group: This relates to the policy rule that will be applied.
    Alert Name: This corresponds to the alert condition ID that will be used.
According to our mapping:
    Namespace maps to the policy name.
    Alert Group maps to the policy rule.
    Alert Name maps to the alert condition ID.
If the policy name is renamed, it's necessary to delete the existing alert from Cortex Ruler and create a new alert with the updated policy name.

2024-07-05 13:39 UTC, aurang-zeb313 commented on metrics-threshold-processor/src/main/java/org/opennms/metrics/threshold/api/MetricsRulerExpressionGenerator.java
> +            default:
ok

2024-07-05 16:06 UTC, aurang-zeb313 commented on metrics-threshold-processor/src/main/java/org/opennms/metrics/threshold/config/KafkaConfig.java
> +        System.out.println("Compact: " + topic.getCompact());
Ya it was added for debugging to investigate one issue but no need so i will remove it.

2024-07-05 16:07 UTC, aurang-zeb313 commented on metrics-threshold-processor/src/main/java/org/opennms/metrics/threshold/MetricsThresholdProcessorApplication.java
> +@EnableCaching(proxyTargetClass = true)
No, let me change it.

2024-07-05 16:18 UTC, aurang-zeb313 commented on metrics-threshold-processor/src/main/java/org/opennms/metrics/threshold/config/KafkaConfig.java
> +        System.out.println("Compact: " + topic.getCompact());
changed from stdout to log

2024-07-05 16:19 UTC, aurang-zeb313 commented on minion/assembly/server-ca.crt
> +-----BEGIN CERTIFICATE-----
Done

2024-07-08 14:22 UTC, Mohammad-Junid commented on events/traps/src/main/java/org/opennms/horizon/events/traps/ThresholdAlertToEventMapper.java
> +/*
Should we move all the mapping  and consumer  logic   to **consumer module** in the  events

2024-07-10 14:15 UTC, aurang-zeb313 commented on alert/src/main/java/org/opennms/horizon/alertservice/db/repository/AlertDefinitionRepository.java
> +            + "LEFT JOIN FETCH d.alertCondition.rule.policy "
Acknowledged

2024-07-10 14:15 UTC, aurang-zeb313 commented on alert/src/main/java/org/opennms/horizon/alertservice/service/routing/ThresholdRuleProducer.java
> +    @PostUpdate
Acknowledged

2024-07-11 16:45 UTC, synqotik requested changes
Added some comments for the UI part.

2024-07-11 16:45 UTC, synqotik commented on ui/src/store/Views/monitoringPoliciesStore.ts
> +      if (this.eventTypes === EventType.MetricThreshold) {
Instead of using `delete` here, include this in `mapToMonitorPolicyInput` instead. Need to pass in a param like `isMetricThreshold: boolean` to `mapToMonitorPolicyInput`.

2024-07-11 16:45 UTC, synqotik commented on ui/src/types/index.ts
> +  CPU_USAGE = 'cpuUtilization'
Rename `CPU_USAGE` to `CpuUtilization`

2024-07-11 16:45 UTC, synqotik commented on ui/tests/MonitoringPolicies/MonitoringPolicyBasicInformationEditAddForm.test.ts
> +  tags: [ 'default' ],
Leave as `tags: ['default'],`

2024-07-11 16:45 UTC, synqotik commented on ui/tests/MonitoringPolicies/MonitoringPolicyBasicInformationEditAddForm.test.ts
> +        'id': 'default',
Do we need the `'` here? Should be find as `id: 'default'` instead of `'id': 'default'`, etc.

2024-07-11 16:45 UTC, synqotik commented on ui/src/components/MonitoringPolicies/DetectionMethodComponents/MetricThresholdAlertConditions.vue
> +  if (selectedRule?.alertConditions) {
May need to be:

```
if (selectedRule?.alertConditions?.length > 0) {
```

2024-07-11 16:45 UTC, synqotik commented on ui/src/components/MonitoringPolicies/DetectionMethodComponents/AlertConditions.vue
> +const dummyAlertConditionThresholdMetrics = reactive<thresholdMetric[]>([
I'm not sure this should be `reactive`. Also, this instance will be modified if it is used more than once.

Consider making it a function that returns a new object every time it is called:

```
const getDummyAlertConditionThresholdMetrics = () => {
  return [
    { id: 1, ... },
    { id: 2, ... },
    ...
  ]
}
```

You might have to use `cloneDeep` instead, but hopefully the above works.

2024-07-11 16:45 UTC, synqotik commented on ui/src/components/MonitoringPolicies/DetectionMethodComponents/AlertConditions.vue
> +          filterAndPushConditions(alertCondition.thresholdMetric?.condition)
Should not have side effects when using `.map()`. Maybe use `forEach` instead, then also you don't need `filter`:

```
const alertConditionsThresholdMetricUpdate = []

monitoringPoliciesStore.selectedRule?.alertConditions.forEach((alertCondition: any) => {
  if (alertCondition?.thresholdMetric) {
    filterAndPushConditions(alertCondition.thresholdMetric.condition)
    
    const condition = {
      id: alertCondition.thresholdMetric.id,
      ...
    }
    
    alertConditionsThresholdMetricUpdate.push(condition)
  }
})
```

Don't need `filter(items => items !== null)`

2024-07-11 17:00 UTC, Mohammad-Junid commented on alert/src/main/java/org/opennms/horizon/alertservice/api/AbstractAlertUtil.java
> +    public static final String THRESHOLD_ALERT_NAME = "thrholdalertname";
Yes . I update it

2024-07-11 17:01 UTC, Mohammad-Junid commented on events/traps/src/main/java/org/opennms/horizon/events/traps/ThresholdAlertToEventMapper.java
> +/*
Done . Create a new module for it

2024-07-12 16:43 UTC, synqotik approved these changes
The UI part looks good, all the important issues I raised have been addressed.

Does need someone to approve the back end part before merging.

2024-07-12 16:49 UTC, aurang-zeb313 commented
> The UI part looks good, all the important issues I raised have been addressed.
> 
> Does need someone to approve the back end part before merging.

@cgorantla  we have implemented the changes you suggested. Do you want to validate more or should i merged to develop??

2024-07-15 21:14 UTC, cgorantla approved these changes
LGTM, please handle couple of things I pointed here.

2024-07-15 21:14 UTC, cgorantla commented on shared-lib/lokahi-common-utils/src/main/java/org/opennms/horizon/shared/utils/SystemInfoUtils.java
> +    public static final String HIGH_THRESHOLD_EVENT_UEI = "uei.opennms.org/threshold/highThresholdExceeded";
move these constants to different file

2024-07-15 21:14 UTC, cgorantla commented on minion/assembly/generate_location.sh
> +echo "Certificate Password = ${CERTIFICATE_PASSWORD}"
remove all the changes under minion/

2024-07-19 11:59 UTC, merged