FE: Initial Service Inventory page
OpenNMS-Cloud/lokahi pull request #1955
Opened 2024-06-26 13:31 UTC by atif1019

## Description
Create a new (empty) Service Inventory page. This is a new screen which will display Windows and Hosted Services for all nodes.

Service Inventory item on AppRail

URL: /services

Title: “List of all Discovered Services”

Tabs should be: All Services, Windows Services, Hosted Services, Standalone Services

Do not implement the search or table here, will do that in a separate ticket.

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2598

2024-06-26 13:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1955) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=1955) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenNMS-Cloud/lokahi?pullRequest=1955) it.</sub>

2024-06-26 15:56 UTC, Shahbaz-dataq requested changes
Run `yarn lint:fix` to fix any other lint issue

2024-06-26 15:56 UTC, Shahbaz-dataq commented on ui/src/containers/ServiceInventory.vue
> +        <div class="tab-menu">
remove empty div

2024-06-26 15:56 UTC, Shahbaz-dataq commented on ui/src/containers/ServiceInventory.vue
> +        <div class="tab-menu">
remove empty div

2024-06-26 15:56 UTC, Shahbaz-dataq commented on ui/src/containers/ServiceInventory.vue
> +          <div class="table-heading"> List of all Discovered Services
move `List of all Discovered Services` to next line. And remove 3 spaces before starting of div tag

2024-06-26 15:56 UTC, Shahbaz-dataq commented on ui/src/containers/ServiceInventory.vue
> +           <Icon :icon="warningIcon" />
Remove 3 space before starting icon tag

2024-06-26 15:56 UTC, Shahbaz-dataq commented on ui/src/containers/ServiceInventory.vue
> +            Hosted Services
Remove 1 space before starting `Hosted Service`

2024-06-26 15:56 UTC, Shahbaz-dataq commented on ui/src/containers/ServiceInventory.vue
> +       Standalone Services
Indent 2 spaces

2024-06-26 15:56 UTC, Shahbaz-dataq commented on ui/src/containers/ServiceInventory.vue
> +import { FeatherTextBadge, BadgeTypes } from '@featherds/badge'
Remove unused import `BadgeTypes`

2024-06-26 15:56 UTC, Shahbaz-dataq commented on ui/src/containers/ServiceInventory.vue
> +
Remove extra space

2024-06-26 15:56 UTC, Shahbaz-dataq commented on ui/src/containers/ServiceInventory.vue
> +
Remove extra space

2024-06-26 15:56 UTC, Shahbaz-dataq commented on ui/src/containers/ServiceInventory.vue
> +
Remove extra space

2024-06-26 15:56 UTC, Shahbaz-dataq commented on ui/src/containers/ServiceInventory.vue
> +
Remove extra space

2024-06-27 10:12 UTC, Shahbaz-dataq commented on ui/components.d.ts
> +    BarCharts: typeof import('./src/components/ServiceInventory/BarCharts.vue')['default']
Remove this components. Its not being for this component

2024-06-27 10:15 UTC, Shahbaz-dataq requested changes
Replace `ui/components.d.ts` with the one on develop and add your component in it `ServiceInventoryFilter: typeof import('./src/components/ServiceInventory/ServiceInventoryFilter.vue')['default']`

2024-06-27 10:33 UTC, Shahbaz-dataq requested changes

2024-06-27 10:33 UTC, Shahbaz-dataq commented on ui/src/containers/ServiceInventory.vue
> +      <div class="gap"></div>
Remove this div

2024-06-27 10:33 UTC, Shahbaz-dataq commented on ui/src/containers/ServiceInventory.vue
> +.gap {
this css class is not being used remove it

2024-06-27 10:33 UTC, Shahbaz-dataq commented on ui/src/containers/ServiceInventory.vue
> +.download-icon {
remove this css class its not being used

2024-06-27 10:33 UTC, Shahbaz-dataq commented on ui/src/containers/ServiceInventory.vue
> +.no-padding {
remove this css class its not being used

2024-06-27 10:33 UTC, Shahbaz-dataq commented on ui/src/containers/ServiceInventory.vue
> +.padding {
remove this css class its not being used

2024-06-27 10:33 UTC, Shahbaz-dataq commented on ui/src/containers/ServiceInventory.vue
> +.tag-manager {
remove this css class its not being used

2024-06-27 10:33 UTC, Shahbaz-dataq commented on ui/src/containers/ServiceInventory.vue
> +    <div class="flex">
remove `flex` css class and its declaration in css. No need for flex here.

2024-06-27 10:33 UTC, Shahbaz-dataq commented on ui/src/containers/ServiceInventory.vue
> +.flex {
remove this flex class

2024-06-27 10:33 UTC, Shahbaz-dataq commented on ui/src/containers/ServiceInventory.vue
> +  border-left: 2px solid #e8e8e8;
use Featherds `vars` for color here. so that they can work better in dark theme.

2024-06-27 10:33 UTC, Shahbaz-dataq commented on ui/src/containers/ServiceInventory.vue
> +.icons-container {
remove this css class

2024-06-27 10:33 UTC, Shahbaz-dataq commented on ui/src/containers/ServiceInventory.vue
> +.table-heading-container {
remove this css class

2024-06-27 10:33 UTC, Shahbaz-dataq commented on ui/src/containers/ServiceInventory.vue
> +.flex-container {
remove this css class

2024-06-27 10:33 UTC, Shahbaz-dataq commented on ui/src/containers/ServiceInventory.vue
> +  .tab-navigation {
remove this css class

2024-06-27 17:07 UTC, Shahbaz-dataq reviewed
LGTM!

2024-06-27 18:14 UTC, synqotik requested changes
See comment.

2024-06-27 18:14 UTC, synqotik commented on ui/components.d.ts
> +    ServiceInventoryFilter: typeof import('./src/components/ServiceInventory/ServiceInventoryFilter.vue')['default']
I don't see this file anywhere, is it new, or didn't get pushed?

Also, please put this entry in alphabetical order.

2024-07-02 08:59 UTC, Shahbaz-dataq reviewed
LGTM

2024-07-03 17:48 UTC, synqotik approved these changes
LGTM

2024-07-08 09:27 UTC, Shahbaz-dataq approved these changes
LGTM

2024-07-08 09:28 UTC, merged