LOK-2462:  Node Inventory Table: Sorting and pagination
OpenNMS-Cloud/lokahi pull request #1956
Opened 2024-06-26 17:53 UTC by Syed-Bilal-Haider-Dataq

## Description
Implement sorting and pagination on Node Inventory table.-->

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2462

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-07-01 13:49 UTC, Shahbaz-dataq requested changes
Other than these changes their is a major problem. After updating `BuildNetworkInventoryPageDocument` to support pagination and sorting. This same document is being used for `Card` Tab content for nodes. Due to no pagination on `Card` tab only 10 nodes will be displayed initially. And their is no way to change the page until you go to `Table` Tab change page and come back to `Card` Tab. 
My suggestion apply pagination on `Card` Tab as well just as it is in `Table` Tab.

2024-07-01 13:49 UTC, Shahbaz-dataq commented on ui/src/components/Inventory/InventoryFilter.vue
> +        :options="[{ id: 1, name: 'label' }, { id: 2, name: 'Tag' }]" :modelValue="inventoryStore.searchType"
Create a `Comparator` for `options` (see `monitoringPolicies.constants.ts`). Keep the old names and don't send them to graphQL query send `id`

2024-07-01 13:49 UTC, Shahbaz-dataq commented on ui/src/components/Inventory/InventoryFilter.vue
> +      <FeatherAutocomplete v-if="inventoryStore.searchType.name === 'Tag'" type="multi"
See first comment and after creating `Comparator` use that here. Move each prop in its own line for better readability

2024-07-01 13:49 UTC, Shahbaz-dataq commented on ui/src/components/Inventory/InventoryFilter.vue
> +      <FeatherInput v-if="inventoryStore.searchType.name === 'label'" @update:model-value="searchNodesByLabel"
See first comment and after creating `Comparator` use that here. Move each prop in its own line for better readability

2024-07-01 13:49 UTC, Shahbaz-dataq commented on ui/src/components/Inventory/InventoryTabTable.vue
> +const hasAlerts = computed(() => {
Rename this variable to `hasNodes`

2024-07-01 13:49 UTC, Shahbaz-dataq commented on ui/src/store/Views/inventoryStore.ts
> +    searchType: { id: 1, name: 'label' },
See first comment and after creating `Comparator` use that here.

2024-07-01 13:49 UTC, Shahbaz-dataq commented on ui/src/store/Views/inventoryStore.ts
>      setSearchType(searchType: { id: number, name: string }) {
Remove the destructure object its node being used

2024-07-01 13:49 UTC, Shahbaz-dataq commented on ui/src/components/Inventory/InventoryTabTable.vue
>    NodeName: SORT.ASCENDING,
Set sorting for `NodeName` to `Sort.None`. Initially nodes are being sorted on `id`

2024-07-01 13:49 UTC, Shahbaz-dataq commented on ui/src/components/Inventory/InventoryTabTable.vue
> +    const sortByAlerts = { sortAscending, sortBy: columnId }
Rename this variable to something like `sortByNode` declare it after `startSpinner()` initialize it in `if` and `else`

2024-07-01 13:49 UTC, Shahbaz-dataq commented on ui/src/components/Inventory/InventoryFilter.vue
>        <FeatherSelect class="filter-type-selector" label="Search Type" textProp="name"
Move each prop in its own line for better readability

2024-07-01 13:49 UTC, Shahbaz-dataq commented on ui/src/components/Inventory/InventoryTabTable.vue
> +        <div v-if="!hasAlerts || total === 0">
Rename this variable `hasAlerts`

2024-07-03 18:16 UTC, synqotik requested changes
Looks good, just a few small name fixes needed

2024-07-03 18:16 UTC, synqotik commented on ui/src/store/Views/inventoryStore.ts
> +    setInventeriesByNodePage(page: number) {
Rename to: `setInventoriesByNodePage`

2024-07-03 18:16 UTC, synqotik commented on ui/src/store/Views/inventoryStore.ts
> +    setInventeriesByNodePageSize(pageSize: number) {
Rename to: `setInventoriesByNodePageSize`

2024-07-03 18:16 UTC, synqotik commented on ui/src/store/Views/inventoryStore.ts
> +    inventeriesByNodeSortChanged(sortObj: any) {
Rename to: `inventoriesByNodeSortChanged`

2024-07-03 18:16 UTC, synqotik commented on ui/src/types/inventory.d.ts
> +interface InventoryItemsFilters {
Rename to: ` InventoryItemFilters`

2024-07-08 14:46 UTC, synqotik approved these changes
LGTM

2024-07-08 18:04 UTC, Shahbaz-dataq approved these changes

2024-07-08 18:23 UTC, merged