FE: User Management - add initial table
OpenNMS-Cloud/lokahi pull request #1963
Opened 2024-06-28 16:42 UTC by faizanjanjua

## Description
Description

In the new Settings page, User Management tab, add the initial User Management components:

title and text

Add User button, doesn't do anything yet (just console.log output is fine)

User Management table with mock data for now. The data should be stored in the store. Edit, Resend Email and Revoke Access just have a console.log output for now

Add pagination, client side for now

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2621

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-06-28 17:29 UTC, Shahbaz-dataq requested changes
Make these changes and run `yarn lint:fix` for lint fixes

2024-06-28 17:29 UTC, Shahbaz-dataq commented on ui/src/components/Settings/UserManagement.vue
> +      <div class="container card table-card card border">
Remove `card` css class. It's assigned twice

2024-06-28 17:29 UTC, Shahbaz-dataq commented on ui/src/components/Settings/UserManagement.vue
> +            <div class="flex justify-content-between">
Create 1 class `heading` and add both `  display: flex;` and `  justify-content: space-between;` in it

2024-06-28 17:29 UTC, Shahbaz-dataq commented on ui/src/components/Settings/UserManagement.vue
> +.justify-content-between{
Merge both `.flex` and `.justify-content-between` in 1 class name `.heading`

2024-06-28 17:29 UTC, Shahbaz-dataq commented on ui/src/components/Settings/UserManagement.vue
> +      <h2 class="heading_inside p-2">User Management</h2>
Remove `p-2` here. Padding already exit in `.heading_inside`. And rename `.heading_inside` to `.heading-inside`

2024-06-28 17:29 UTC, Shahbaz-dataq commented on ui/src/components/Settings/UserManagement.vue
> +
Remove extra space

2024-06-28 17:29 UTC, Shahbaz-dataq commented on ui/src/components/Settings/UserManagement.vue
> +<section class="container ">
Remove extra space

2024-06-28 17:29 UTC, Shahbaz-dataq commented on ui/src/components/Settings/UserManagement.vue
> +    height: 442px;
Remove static `height`

2024-06-28 17:29 UTC, Shahbaz-dataq commented on ui/src/components/Settings/UserManagement.vue
> +        div {
Remove this `div` css here if it's not beign used.

2024-06-28 17:29 UTC, Shahbaz-dataq commented on ui/src/components/Settings/UserManagement.vue
> +const icons = markRaw({
remove unused variable also associated imports

2024-06-28 17:29 UTC, Shahbaz-dataq commented on ui/src/containers/Settings.vue
> +import UserManagement from "@/components/Settings/UserManagement.vue";
Remove this import we don't need it.

2024-06-28 17:33 UTC, Shahbaz-dataq commented on ui/src/components/Settings/UserManagement.vue
> +
remove extra space

2024-07-01 10:38 UTC, faizanjanjua commented on ui/components.d.ts
> +    UserManagement: typeof import('./src/components/Settings/UserManagement.vue')['default']
done

2024-07-01 12:57 UTC, faizanjanjua commented on ui/src/components/Settings/UserManagement.vue
> +            <div class="flex justify-content-between">
resolved

2024-07-01 12:59 UTC, faizanjanjua commented on ui/src/components/Settings/UserManagement.vue
> +
done

2024-07-01 14:05 UTC, Shahbaz-dataq requested changes
Just this small change. Pagination logic also needs some work but we'll work on it when we have real data.

2024-07-01 14:05 UTC, Shahbaz-dataq commented on ui/src/components/Settings/UserManagement.vue
> +const unSortedColumns = [
Remove this variable

2024-07-01 14:05 UTC, Shahbaz-dataq commented on ui/src/components/Settings/UserManagement.vue
> +              <th v-for="col of unSortedColumns"
Add simple `th` tag other unSorted columns

2024-07-01 14:12 UTC, Shahbaz-dataq requested changes

2024-07-01 14:12 UTC, Shahbaz-dataq commented on ui/src/components/Settings/UserManagement.vue
> +.flex{
Remove this css class. It's not being used

2024-07-01 14:12 UTC, Shahbaz-dataq commented on ui/src/components/Settings/UserManagement.vue
> +.heading{
Move this `.heading` inside `.user-management-wrapper > .header > .title-container`

2024-07-01 14:12 UTC, Shahbaz-dataq commented on ui/src/components/Settings/UserManagement.vue
> +.heading-inside{
Same move this `.heading-inside` inside `.user-management-wrapper`

2024-07-01 17:06 UTC, Shahbaz-dataq reviewed
LGTM

2024-07-03 17:28 UTC, synqotik requested changes
Looks good, just one comment.

However, wait until this PR is done: https://github.com/OpenNMS-Cloud/lokahi/pull/1974

Then rebase onto that to get the changes in that PR for getting user list from BFF.

2024-07-03 17:28 UTC, synqotik commented on ui/src/components/Settings/UserManagement.vue
> +              <td>{{ data.firstName }}</td>
Should be  `<td>{{ data.firstName }} {{ data.lastName }}</td>`

2024-07-08 13:46 UTC, Shahbaz-dataq approved these changes
Approve. just this small change

2024-07-08 13:46 UTC, Shahbaz-dataq commented on ui/src/components/Settings/UserManagement.vue
> +              <td>{{ data.firstName }} {{ data.firstName }}</td>
change the last `firstName` to `lastName`

2024-07-08 14:14 UTC, synqotik approved these changes
LGTM

2024-07-08 14:31 UTC, merged