LOK-2551 : Wsman Collector Development
OpenNMS-Cloud/lokahi pull request #1972
Opened 2024-07-03 12:16 UTC by MusaidAli

## Description

## Jira link(s)
-https://opennms.atlassian.net/browse/LOK-2551

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-07-08 13:54 UTC, MusaidAli commented
FreePhysicalMemory metric .
![Screenshot from 2024-07-08 18-50-58](https://github.com/OpenNMS-Cloud/lokahi/assets/157728237/2d609e20-db9d-4d5f-b496-ebc22ac112ef)

![Screenshot from 2024-07-08 18-50-49](https://github.com/OpenNMS-Cloud/lokahi/assets/157728237/e099bb90-9c12-43ca-a12a-6755b42cae06)

FreeVirtualMemory metric .
![Screenshot from 2024-07-08 18-53-55](https://github.com/OpenNMS-Cloud/lokahi/assets/157728237/b6e1b280-e1df-499b-a2c9-188fc5100010)
![Screenshot from 2024-07-08 18-53-50](https://github.com/OpenNMS-Cloud/lokahi/assets/157728237/c4481e44-25f4-40d9-8151-9a3e3b165d1e)

2024-07-09 14:44 UTC, naeem-afzal commented
You are suppose to receive followings from core system (Inventory):

1. WsmanAgentConfig (configurations like target system, credentials, authentication etc)
2. List of Groups against which we need to get metrics. Fined sample groups here: "https://github.com/OpenNMS/opennms/blob/48eb29e7d784e422f236656471e13eabdba305d2/opennms-base-assembly/src/main/filtered/etc/wsman-datacollection.d/microsoft-windows.xml"
3. List of System Definations having rule and groups to select if rule expression is true.
3. Apply above rule and collect data against those groups only.

You need to update collector command as mentioned under here:
1. Remove resource-uri from the commands parameters.
2. Get/ configure list of groups in parameters, also update Collection request in Proto.
3. Get list of system-definitions having a rule to include list of groups for collection, also update Collection request in Proto.
You need to loop through all selected groups one by one and add metrics in response.

You can debug/ explore OpenNMS Horizon/ Classic code for more deep understanding.

2024-07-09 15:10 UTC, smunir-onms commented
> @MusaidAli You are suppose to receive followings from core system (Inventory):
> 
> 1. WsmanAgentConfig (configurations like target system, credentials, authentication etc)
> 2. List of Groups against which we need to get metrics. Find sample groups here: "https://github.com/OpenNMS/opennms/blob/48eb29e7d784e422f236656471e13eabdba305d2/opennms-base-assembly/src/main/filtered/etc/wsman-datacollection.d/microsoft-windows.xml"
> 3. List of System Definations having rule and groups to select if rule expression is true.
> 4. Apply above rule and collect data against those groups only.
> 
> You need to update collector command as mentioned under here:
> 
> 1. Remove resource-uri from the commands parameters.
> 2. Get/ configure list of groups in parameters, also update Collection request in Proto.
> 3. Get list of system-definitions having a rule to include list of groups for collection, also update Collection request in Proto.
>    You need to loop through all selected groups one by one and add metrics in response.
> 
> You can debug/ explore OpenNMS Horizon/ Classic code for more deep understanding.

@cgorantla can you please review this, any suggestions/corrections?

2024-07-09 15:27 UTC, MusaidAli commented
> 1. WsmanAgentConfig (configurations like target system, credentials, authentication etc)

this was supposed to be saved in db as json like snmp agent config. from UI.

2024-07-09 17:36 UTC, MusaidAli commented
![Screenshot from 2024-07-09 22-34-27](https://github.com/OpenNMS-Cloud/lokahi/assets/157728237/745599f6-f9b6-4158-858d-7994ae23dc3a)

2024-07-10 14:46 UTC, naeem-afzal reviewed
Make sure to bring in all business logic from Classic for collection

2024-07-10 15:48 UTC, MusaidAli commented on minion/plugins/shell-commands/src/main/java/org/opennms/horizon/minion/icmp/shell/WsmanCollectorCommand.java
> +       --resource-uri "http:/schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk" -rt 1   */
resolved ,added update command.

2024-07-10 15:48 UTC, MusaidAli commented on minion/plugins/shell-commands/src/main/java/org/opennms/horizon/minion/icmp/shell/WsmanCollectorCommand.java
> +                        .addIncludeGroup("winrm-logical-disk")
resolved,updated "winrm-network-interface"

2024-07-10 15:48 UTC, MusaidAli commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanCollector.java
> +                Map<String, String> selectors = new HashMap<>();
removed,

2024-07-10 15:50 UTC, MusaidAli commented on minion/plugins/shell-commands/src/main/java/org/opennms/horizon/minion/icmp/shell/WsmanCollectorCommand.java
> +                        .setPassword("Onm$2K24!@#")
there was a reason ,password were copy upto $ remaining was skipped when enter karaf command ,thats why i hard coded it.resolved

2024-07-10 15:51 UTC, MusaidAli commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanCollector.java
> +    public Map<String, String> processEnumerationResults(WSMANGroup group, List<Node> nodes) {
final NodeLevelResource nodeResource = new NodeLevelResource(agent.getNodeId());
        final AtomicInteger instanceId = new AtomicInteger();
        Supplier<Resource> resourceSupplier = () -> nodeResource;
        if (!"node".equalsIgnoreCase(group.getResourceType())) {
        
        for this we have to add alots of code ,like NodeLevelResource and it also extends and interfaces.

2024-07-10 15:54 UTC, MusaidAli commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanCollector.java
> +    private final ThreadFactory threadFactory = new ThreadFactoryBuilder()
resolved.

2024-07-10 16:01 UTC, MusaidAli commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanCollector.java
> +    public Map<String, String> processEnumerationResults(WSMANGroup group, List<Node> nodes) {
@XmlJavaTypeAdapter(NodeLevelResourceAdapter.class)
public class NodeLevelResource extends AbstractResource {

2024-07-10 16:03 UTC, MusaidAli commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanCollector.java
> +    public Map<String, String> processEnumerationResults(WSMANGroup group, List<Node> nodes) {
I think we don't need to add xml thing

2024-07-11 17:18 UTC, naeem-afzal commented
@smunir-onms , Now PR seems fine, you can proceed for further reviews, thanks!

2024-07-11 17:49 UTC, aurang-zeb313 requested changes

2024-07-11 17:49 UTC, aurang-zeb313 commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanCollector.java
> +            System.out.println(">>> IllegalArgumentException: " + e.toString());
Please use logger instead of sysout

2024-07-11 17:49 UTC, aurang-zeb313 commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanCollector.java
> +            System.out.println(">>> Exception: " + e.toString());
Same here, use logger instead of sysout

2024-07-12 12:25 UTC, smunir-onms commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanCollector.java
> +            LOG.debug(">>> IllegalArgumentException: " + e);
remove >> in the logs.

LOG.debug("IllegalArgumentException: {}", e);

2024-07-12 12:25 UTC, smunir-onms commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanCollector.java
> +            LOG.debug(">>> Exception: " + e);
same here

2024-07-22 21:17 UTC, cgorantla requested changes

2024-07-22 21:17 UTC, cgorantla commented on shared-lib/protobuf/src/main/proto/wsman.proto
> +  map<string, string> labels = 4;
This is not the format we store metrics on Prometheus/Cortex.

2024-07-22 21:17 UTC, cgorantla commented on shared-lib/protobuf/src/main/proto/wsman.proto
> +  int64 node_id = 14;
we may not have node_id for wsman. Any device info should stay out of Collector and should only be used to append as labels

2024-07-22 21:17 UTC, cgorantla commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/core/wsman/resource/Resource.java
> +public interface Resource {
we shouldn't be using these resources here.

2024-07-23 17:54 UTC, MusaidAli commented on shared-lib/protobuf/src/main/proto/wsman.proto
> +  map<string, string> labels = 4;
![Screenshot from 2024-07-23 22-53-00](https://github.com/user-attachments/assets/c21420e0-3d37-40d4-a3e3-18e1db9f76f0)

2024-07-23 18:05 UTC, cgorantla commented on shared-lib/protobuf/src/main/proto/wsman.proto
> +  google.protobuf.Any result = 2;
why this is Any ?  Metric can be double.
We also have to understand which labels we need to use and add them here.

2024-07-23 18:07 UTC, MusaidAli commented on shared-lib/protobuf/src/main/proto/wsman.proto
> +  google.protobuf.Any result = 2;
WE have to store 3 diff types values ,i.e Gauge ,Counter and String types .so we can store all of these in Any type

2024-07-24 07:50 UTC, MusaidAli commented on shared-lib/protobuf/src/main/proto/wsman.proto
> +  google.protobuf.Any result = 2;
added uint64 value for metrics and tested.
![Screenshot from 2024-07-24 12-49-37](https://github.com/user-attachments/assets/df4f5732-a4ce-4ba0-96f5-8da14dc13bf0)

2024-07-24 20:58 UTC, cgorantla requested changes

2024-07-24 20:58 UTC, cgorantla commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanCollector.java
> +
may want to log and return Error response here.

2024-07-24 20:58 UTC, cgorantla commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanCollector.java
> +                            return WsmanResultMetric.newBuilder()
How does this work ? Do you just return one result for all the nodes

2024-07-24 20:58 UTC, cgorantla commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanCollector.java
> +                retryLoop.takeException(e);
log the exception

2024-07-25 08:06 UTC, MusaidAli commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanCollector.java
> +                            return WsmanResultMetric.newBuilder()
Please check error resolved ,will work for all nodes now.added break statement after match.and added to WsmanResultMetric list.

2024-07-25 08:06 UTC, MusaidAli commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanCollector.java
> +                retryLoop.takeException(e);
logged the exception.

2024-07-25 10:27 UTC, MusaidAli commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanCollector.java
> +
Logged the exception.

2024-07-31 09:34 UTC, MusaidAli commented
![Screenshot from 2024-07-31 14-29-24](https://github.com/user-attachments/assets/1b0082d3-c1d5-493f-a15d-02a89199cb00)

One Resource URI for network Interface ,Metrics compared with Lokahi and Horizon.

2024-08-05 10:13 UTC, aurang-zeb313 commented on shared-lib/protobuf/src/main/proto/wsman.proto
> +  string indexOf =4;
it should be index_of. keep same format

2024-08-05 10:14 UTC, aurang-zeb313 commented on shared-lib/protobuf/src/main/proto/wsman.proto
> +  uint64 timestamp = 4;
same here, it should be time_stamp

2024-08-05 10:15 UTC, aurang-zeb313 requested changes

2024-08-05 10:15 UTC, aurang-zeb313 commented on shared-lib/protobuf/src/main/proto/wsman.proto
> +  uint64 timestamp = 5;
it should be time_stamp

2024-08-06 13:25 UTC, naeem-afzal reviewed
For now, the collection process appears satisfactory. We can make minor adjustments during the integration phase with Cortex/Prometheus.

2024-08-08 02:37 UTC, cgorantla commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanCollector.java
> +                            .setMonitorServiceId(1)
why would this be fixed as 1 ?

2024-08-08 02:37 UTC, cgorantla commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanCollector.java
> +            assert wsmanCollectorRequest != null;
Is this assert required ?

2024-08-08 02:37 UTC, cgorantla commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanCollector.java
> +            LOG.debug("IllegalArgumentException: " + e);
you are already logging exception in above line, why do you need another log here ?

2024-08-08 02:37 UTC, cgorantla commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanCollector.java
> +            LOG.debug("Exception: " + e);
you are already logging before this line and why do you need `+` in  LOG ?

2024-08-08 02:37 UTC, cgorantla commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanCollector.java
> +        return CompletableFuture.supplyAsync(() -> {
There is no need for another CompletableFuture inside another CompletableFuture.

2024-08-08 02:37 UTC, cgorantla commented on shared-lib/protobuf/src/main/proto/wsman.proto
> +  string ip_address = 1;
don't need ip_address here after recent monitored entity related changes

2024-08-08 02:37 UTC, cgorantla commented on shared-lib/protobuf/src/main/proto/wsman.proto
> +  uint64 monitor_service_id= 3;
don't need monitor_service_id here after recent monitored entity related changes.

2024-08-08 10:37 UTC, MusaidAli commented on shared-lib/protobuf/src/main/proto/wsman.proto
> +  uint64 monitor_service_id= 3;
Removed.

2024-08-08 10:37 UTC, MusaidAli commented on shared-lib/protobuf/src/main/proto/wsman.proto
> +  string ip_address = 1;
Removed.

2024-08-08 10:37 UTC, MusaidAli commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanCollector.java
> +            LOG.debug("Exception: " + e);
removed redundant.

2024-08-08 10:37 UTC, MusaidAli commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanCollector.java
> +                            .setMonitorServiceId(1)
Removed.

2024-08-08 10:38 UTC, MusaidAli commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanCollector.java
> +            assert wsmanCollectorRequest != null;
Removed.

2024-08-08 10:38 UTC, MusaidAli commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanCollector.java
> +            LOG.debug("IllegalArgumentException: " + e);
Removed,

2024-08-14 14:23 UTC, MusaidAli commented
it is being covered in [PR-2044](https://github.com/OpenNMS-Cloud/lokahi/pull/2044) so closing this PR

2024-08-14 14:23 UTC, closed without merging