BE : LOK-2565 Monitored Entities Test Cases.
OpenNMS-Cloud/lokahi pull request #1986
Opened 2024-07-10 14:59 UTC by Junaid-Khan-Nant

## Description
End to End Test Cases.

## Jira link(s)

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-07-10 16:05 UTC, smunir-onms commented on rest-server/src/main/java/org/opennms/horizon/server/service/GraphQLNodeService.java
> +            @GraphQLArgument(name = "id") long id,
should be @GraphQLArgument(name = "nodeId") long nodId,

2024-07-10 16:10 UTC, smunir-onms commented on rest-server/src/main/java/org/opennms/horizon/server/service/metrics/QueryService.java
> +            String rangeQuerySuffix = "&start=" + start + "&end=" + end + "&step=1m";
don't change this, add a new one for SYS_RESPONSE_TIME
String rangeQuerySuffixSysResponseTime = "&start=" + start + "&end=" + end + "&step=1m";

2024-07-11 14:34 UTC, Junaid-Khan-Nant commented
@fooker , For now i will skipped tests cases related to metrics and node status. I will reward it once it get green.

2024-07-11 15:51 UTC, fooker requested changes

2024-07-11 15:52 UTC, fooker commented
AFAIR, we already have a monitored service endpoint that gives us the monitored entity ID for that service.

2024-07-12 06:46 UTC, fooker requested changes

2024-07-12 06:46 UTC, fooker commented on rest-server/src/main/java/org/opennms/horizon/server/service/metrics/QueryService.java
> +                    }
I do not understand, why this is needed. As far as I understand, this will produce the same query as the default code-path

2024-07-12 06:46 UTC, fooker commented on test-automation/integration-tests/src/main/java/org/opennms/horizon/it/DiscoveryTestSteps.java
> -            if (!currentStatus.equals(expectedStatus)) {
Yeah, this will make all tests pass, you've removed the check.

2024-07-12 06:46 UTC, fooker commented on rest-server/src/main/java/org/opennms/horizon/server/service/GraphQLNodeService.java
> +    @GraphQLQuery(name = "getMonitoredService")
This is not REST. Should be named `monitoredService` if required after all.

2024-07-12 06:46 UTC, fooker commented on test-automation/integration-tests/src/main/java/org/opennms/horizon/it/InventoryTestSteps.java
> +        this.discoveryId = "discovery:"+val2;
We should not create the monitored entity ID here but get it from the API.

2024-07-12 12:48 UTC, fooker requested changes

2024-07-12 12:48 UTC, fooker commented on minion/plugins/http-plugin/src/test/java/org/opennms/horizon/minion/http/HttpsMonitorTest.java
> +                "www.opennms.org", "201-202", "https://www.opennms.org/", Arrays.asList(443), 3, 3000);
Please revert and rebase on upstream

2024-07-23 11:03 UTC, closed without merging