FE: Add "Revoke Access" functionality for user in user management table
OpenNMS-Cloud/lokahi pull request #1987
Opened 2024-07-10 18:04 UTC by faizanjanjua

## Description
Edit/Update user work is being done in ticket https://opennms.atlassian.net/browse/LOK-2623. Once it is complete we need to add “Revoke access“ functionality in User management for a single user. 

It is same as Edit/Update user but with updated value of enabled in User(inside users.d.ts)

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2662

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-07-10 18:08 UTC, Shahbaz-dataq approved these changes
LGTM. Just make this change before merge

2024-07-10 18:08 UTC, Shahbaz-dataq commented on ui/src/components/Settings/UserManagement.vue
> +
Remove extra space

2024-07-10 18:10 UTC, faizanjanjua commented on ui/src/components/Settings/UserManagement.vue
> +
done

2024-07-10 18:56 UTC, synqotik requested changes
Requesting a change.

2024-07-10 18:56 UTC, synqotik commented on ui/src/store/Views/userStore.ts
> +      return userList?.find((user) => user.email.toLowerCase() === this.selectedUser?.email.toLowerCase() ||
We should return a `boolean` from this instead of a `User`:

```
return !userList?.find((user) => user.email.toLowerCase() === this.selectedUser?.email.toLowerCase() ||
  user.username.toLowerCase() === this.selectedUser?.username.toLowerCase())
```

Then fix the other cases below.

2024-07-10 18:56 UTC, synqotik commented on ui/src/store/Views/userStore.ts
> +      if (this.checkForDuplicateUsernameOrEmail()?.email.toLowerCase() === this.selectedUser.email.toLowerCase()) {
See comment above, then this and similar cases below can just be:

```
if (!this.checkForDuplicateUsernameOrEmail()) {
  showSnackbar ...
}
```

2024-07-11 10:19 UTC, faizanjanjua commented on ui/src/store/Views/userStore.ts
> +      if (this.checkForDuplicateUsernameOrEmail()?.email.toLowerCase() === this.selectedUser.email.toLowerCase()) {
actually we had to show validation message for username or email separately as we are handling this in front end and we are checking here that what entry is duplicate here
 but as per your instruction i have changed function checkForDuplicateUsernameOrEmail so now it is returning us boolean 
 thanks

2024-07-11 19:18 UTC, synqotik commented on ui/src/store/Views/userStore.ts
> +      if (this.checkForDuplicateUsernameOrEmail()?.email.toLowerCase() === this.selectedUser.email.toLowerCase()) {
Another way would be to have this return an object with 2 booleans, one for email and one for username. Better yet, have it all done in `validateUser` and return an object with the specific errors.

Anyway, this is fine.

2024-07-11 19:20 UTC, synqotik approved these changes
Looks good, just rename `handleRemoveUser` to `handleRevokeUser` before merging, thanks!

2024-07-11 19:20 UTC, synqotik commented on ui/src/components/Settings/UserManagement.vue
> +const handleRemoveUser = (selectedUser: User) => {
Rename to `handleRevokeUser`. Can just do this before merging.

2024-07-12 09:21 UTC, faizanjanjua commented on ui/src/components/Settings/UserManagement.vue
> +const handleRemoveUser = (selectedUser: User) => {
resolved

2024-07-12 09:49 UTC, merged