FE: Unit tests for userStore
OpenNMS-Cloud/lokahi pull request #2002
Opened 2024-07-19 17:49 UTC by faizanjanjua

## Description
Units test for all methods in userStore

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2665
## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-07-19 19:23 UTC, synqotik requested changes
A few comments.

2024-07-19 19:23 UTC, synqotik commented on ui/tests/store/Views/userStore.test.ts
> +    store.selectedUser = { ...UserDummyData, email: 'updated@example.com', username: 'updateduser' }
`store.updateUser` should have already set `store.selectedUser`, so we shouldn't set it here - though should probably check that it was set correctly.

2024-07-19 19:23 UTC, synqotik commented on ui/tests/store/Views/userStore.test.ts
> +  let userStore: ReturnType<typeof useUserStore>
I don't see `userStore` being used anywhere, should probably remove it.

2024-07-19 19:23 UTC, synqotik commented on ui/tests/store/Views/userStore.test.ts
> +  beforeEach(() => {
Remove this, since `userStore` isn't used and `store` is being created in each test.

2024-07-19 19:23 UTC, synqotik commented on ui/tests/store/Views/userStore.test.ts
> +    expect(dummy).toEqual(cloneDeep(defaultUser))
Don't think we need `cloneDeep` here.

We probably need a better test here. In `defaultUser` above, set the ID and createdTimestamp to `new Date().getTime()` (ID should be a string).

Then here, after `store.createUser()` is called, can get the current timestamp (`new Date().getTime()`), make sure the newly-created user has ID and `createdTimestamp` that are both numbers (or a string of a number) and that the values are between `defaultUser` values and the current timestamp values.

```
const defaultUser = {
    id: (new Date()).getTime().toString(),
    username: '',
    firstName: '',
    lastName: '',
    password: '',
    email: '',
    roles: [],
    enabled: false,
    createdTimestamp: new Date().getTime()
  }
```

and

```
store.createUser()

const currentTime = new Date().getTime()

expect(store.selectedUser.username).toBe('')
// ...check all other empty strings, etc.

// check id and createdTimestamp
expect(Number(store.selectedUser.id)).toBeGreaterThan(Number(defaultUser.id))
expect(Number(store.selectedUser.id)).toBeLessThan(currentTime)

// similar for createdTimestamp
```

2024-07-19 19:23 UTC, synqotik commented on ui/tests/store/Views/userStore.test.ts
> +    expect(store.selectedUser).toEqual(cloneDeep(user))
Don't think we need `cloneDeep` here.

2024-07-22 13:41 UTC, faizanjanjua commented on ui/tests/store/Views/userStore.test.ts
> +    store.selectedUser = { ...UserDummyData, email: 'updated@example.com', username: 'updateduser' }
it('should update user data', async () => {
    const { updateUser } = useUsersMutations()
    userStore.selectedUser = { ...UserDummyData, email: 'updated@example.com', username: 'updateduser' }
    userStore.updateUser(userStore.selectedUser)

    await userStore.updateUserData()

    expect(userStore.validationErrors).toEqual({})
    expect(userStore.isModalVisible).toBe(false)
    expect(updateUser).toHaveBeenCalled()
  })


thanksnow i am just giving it store.selectedUser instead of setting value in store,.selectedUser

2024-07-22 13:43 UTC, faizanjanjua commented on ui/tests/store/Views/userStore.test.ts
> +    expect(store.selectedUser).toEqual(cloneDeep(user))
removed thanks

2024-07-22 13:57 UTC, faizanjanjua commented on ui/tests/store/Views/userStore.test.ts
> +    expect(dummy).toEqual(cloneDeep(defaultUser))
_Actually i have tried this now . but main issue is , because we are using time.now which fetch the time of system . sometime due to difference of miliseconds it is giving me false positive results and some time it is failing tests due to miliseconds of difference ._




**_i wrote the new test like this_**


`it('should create a new user on createUser', () => {

  userStore.createUser()

  const currentTime = new Date().getTime()



_this part was working fine_ 
  expect(store.selectedUser.username).toBe('')
  expect(store.selectedUser.firstName).toBe('')
  expect(store.selectedUser.lastName).toBe('')
  expect(store.selectedUser.password).toBe('')
  expect(store.selectedUser.email).toBe('')
  expect(store.selectedUser.roles).toEqual([])
  expect(store.selectedUser.enabled).toBe(false)

  })`
 

_this part was creating issue_ 
  // check id and createdTimestamp
  expect(Number(store.selectedUser.id)).toBeGreaterThan(Number(defaultUser.id))
  expect(Number(store.selectedUser.id)).toBeLessThan(currentTime)
  expect(Number(store.selectedUser.createdTimestamp)).toBeGreaterThan(Number(defaultUser.createdTimestamp))
  expect(Number(store.selectedUser.createdTimestamp)).toBeLessThan(currentTime)


this was default value which i was keeping 

const defaultUser = {
    id: (new Date()).getTime().toString(),
    username: '',
    firstName: '',
    lastName: '',
    password: '',
    email: '',
    roles: [],
    enabled: false,
    createdTimestamp: new Date().getTime()
  }



_After knowing the test is failing
so till now i have gave defaultUser  predefined id and createdTImeStamp  like previous as below_


 const defaultUser = {
    id: 'test-id',
    username: '',
    firstName: '',
    lastName: '',
    password: '',
    email: '',
    roles: [],
    enabled: false,
    createdTimestamp: new Date('2012-12-12T00:00:00Z').getTime()
  }
  
   it('should create a new user on createUser', () => {

    userStore.createUser()

    expect(userStore.userEditMode).toBe(CreateEditMode.Create)
    const dummy = userStore.selectedUser
    
    _here i am getting userStore.selectedUser to be saved in dummy array
    
    as our real function in createUser() is creating id and timestamp so we are chaning those for our predefine values_
    if (dummy) {
      dummy.id = 'test-id'
         dummy.createdTimestamp = new Date('2012-12-12T00:00:00Z').getTime()
    }

    expect(dummy).toEqual(defaultUser)
    
    _now checking if my defaultUser which is to be same like my defaultUser in store with difference in two fields id and timeStamp are same as we getting the userStore.selectedUser_ 
    
  })

  
  
  **_i would be very thankfull if you could suggest me any other solution for this problem so i can try that_**

2024-07-22 17:36 UTC, synqotik commented on ui/tests/store/Views/userStore.test.ts
> +    expect(dummy).toEqual(cloneDeep(defaultUser))
I agree, dates and times are often difficult to do unit tests on.

Can you try `toBeGreaterThanOrEqualTo` and `toBeLessThanOrEqualTo` instead?

Another thing would be to set `currentTime` to a date clearly in the past, like January 1, 2024, and just make sure the `id` and `createdTimestamp` are integers and greater than that time.

If none of those work, just checking that `id` and `createdTimestamp` are integers (or a string that can be converted to an integer).

We are mainly just checking that those values are filled in with some kind of large number, that isn't 0.

2024-07-23 13:16 UTC, synqotik commented
Looking at this a little more... we should change `createUser` in `userStore.ts` to:

```
    createUser() {
      this.userEditMode = CreateEditMode.Create
      this.selectedUser = {
        ...cloneDeep(defaultUser),
        id: `${createId()}`,
        createdTimestamp: new Date().getTime()
      }
    }, 
```

This way it has a unique ID. It doesn't matter too much since both `id` and `createdTimestamp` fields are replaced when actually saving, but at least makes sure there are no conflicts until then.

Then change the test:

```
expect(Number(userStore.selectedUser!.id)).toBeGreaterThanOrEqual(Number(defaultUser.id))
expect(Number(userStore.selectedUser!.id)).toBeLessThanOrEqual(currentTime)
    expect(Number(userStore.selectedUser!.createdTimestamp)).toBeGreaterThanOrEqual(Number(defaultUser.createdTimestamp))
expect(Number(userStore.selectedUser!.createdTimestamp)).toBeLessThanOrEqual(currentTime) 
```

2024-07-23 18:18 UTC, synqotik approved these changes
LGTM, thanks for changes.

2024-07-23 18:44 UTC, merged