jira: https://opennms.atlassian.net/browse/LOK-2610, WSMAN Discovery process.
OpenNMS-Cloud/lokahi pull request #2011
Opened 2024-07-26 11:31 UTC by naeem-afzal

## Description

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-XXXX

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-07-26 11:54 UTC, naeem-afzal commented
![Screenshot from 2024-07-26 15-31-39](https://github.com/user-attachments/assets/b67c23ed-56a9-4cf0-a169-0f04724cb39a)
New single task sent to Minion with multiple discoveries

2024-07-29 11:35 UTC, smunir-onms commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/discovery/WsManActiveDiscoveryGrpcService.java
> +import org.opennms.horizon.inventory.discovery.*;
please avoid wildcard imports

2024-07-29 11:48 UTC, aurang-zeb313 requested changes

2024-07-29 11:48 UTC, aurang-zeb313 commented on rest-server/src/main/java/org/opennms/horizon/server/service/grpc/InventoryClient.java
> +import org.opennms.horizon.inventory.discovery.*;
avoid wildcard imports

2024-07-29 11:48 UTC, aurang-zeb313 commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanDetector.java
> +        System.out.println("Minion-wsmanDetectorRequest: " + wsmanDetectorRequest);
use logger instead of SYSOUT

2024-07-29 12:22 UTC, smunir-onms commented on inventory/main/src/main/java/org/opennms/horizon/inventory/model/discovery/active/WsManActiveDiscovery.java
> +    private String userPasswords;
probably it should be userPassword instead of userPasswords

2024-07-29 13:14 UTC, smunir-onms commented on inventory/main/src/main/resources/db/changelog/hs-0.1.0/tables/discovery-inheritance.xml
> +        <createTable tableName="wsman_active_discovery">
For now it can work until environment is setup, generally, there should be a new changeset file.

2024-08-12 13:41 UTC, naeem-afzal commented on rest-server/src/main/java/org/opennms/horizon/server/service/grpc/InventoryClient.java
> +import org.opennms.horizon.inventory.discovery.*;
fixed

2024-08-12 13:42 UTC, naeem-afzal commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/discovery/WsManActiveDiscoveryGrpcService.java
> +import org.opennms.horizon.inventory.discovery.*;
fixed

2024-08-12 17:30 UTC, cgorantla commented on shared-lib/inventory/src/main/proto/wsmanActiveDiscovery.proto
> +  repeated string ip_addresses = 5;
why is this ip_addresses ?  Should this be hostnames ?

2024-08-12 17:30 UTC, cgorantla commented on shared-lib/inventory/src/main/proto/wsmanActiveDiscovery.proto
> +  string user_passwords = 8;
if we are only accepting one username and password, just name it as username/password

2024-08-12 17:30 UTC, cgorantla commented on shared-lib/inventory/src/main/proto/wsmanActiveDiscovery.proto
> +  string protocol = 6;
Will the protocol be different other than WSMAN fr WsManDiscovery ?

2024-08-12 18:07 UTC, naeem-afzal commented on shared-lib/inventory/src/main/proto/wsmanActiveDiscovery.proto
> +  string protocol = 6;
Currently front-end team has placed a drop down on WSMAN Discovery UI, with label as "Protocol" it include values like WMI, WSMAN etc.
So we have added protocol field to hold these values.

2024-08-12 18:10 UTC, naeem-afzal commented on shared-lib/inventory/src/main/proto/wsmanActiveDiscovery.proto
> +  string user_passwords = 8;
We need to change these string values to lists in future to hold multiple credentials, but currently Front-end is sending only one value, once UI will be updated we need to change strings to list of strings, however names will remain same.

2024-08-12 18:13 UTC, naeem-afzal commented on shared-lib/inventory/src/main/proto/wsmanActiveDiscovery.proto
> +  repeated string ip_addresses = 5;
its values can be and an individual IP address, or complete WSMAN web service URL or a partial URL or a DNS name

2024-08-13 01:11 UTC, cgorantla commented on minion/plugins/wsman-plugin/src/main/resources/OSGI-INF/blueprint/wsman-plugins.xml
> +    <!-- Below Detector is no more needed, moved detector inside Scanner
just delete all of it if it is no longer needed

2024-08-13 01:11 UTC, cgorantla commented on minion/plugins/wsman-plugin/src/main/java/org/opennms/lokahi/minion/wsman/WsmanScanner.java
> +        LOG.debug("New WSMAN scanner request received ...... ");
this should be either a trace or  remove

2024-08-13 01:11 UTC, cgorantla commented on minion/plugins/shell-commands/src/main/java/org/opennms/horizon/minion/icmp/shell/WSManScannerCommand.java
> +        //        wsmanScannerRequests.add(WsmanDetectorRequest.newBuilder()
pls don't keep any commented code

2024-08-13 01:11 UTC, cgorantla commented on inventory/main/src/main/resources/db/changelog/hs-0.1.0/tables/discovery-inheritance.xml
> +
I think credential management can be done as an object which can be json column and we can encrypt that column.

2024-08-16 16:44 UTC, naeem-afzal commented on shared-lib/inventory/src/main/proto/wsmanActiveDiscovery.proto
> +  string user_passwords = 8;
Credentials has been added with an array of BasicAuth

2024-08-16 16:44 UTC, naeem-afzal commented on shared-lib/inventory/src/main/proto/wsmanActiveDiscovery.proto
> +  repeated string ip_addresses = 5;
ip_addresses has been renamed to hosts

2024-08-16 16:45 UTC, naeem-afzal commented on shared-lib/inventory/src/main/proto/wsmanActiveDiscovery.proto
> +  string protocol = 6;
protocol field has been removed

2024-08-16 16:46 UTC, naeem-afzal commented on minion/plugins/wsman-plugin/src/main/resources/OSGI-INF/blueprint/wsman-plugins.xml
> +    <!-- Below Detector is no more needed, moved detector inside Scanner
removed WSMAN detector stuff

2024-08-16 16:46 UTC, naeem-afzal commented on minion/plugins/shell-commands/src/main/java/org/opennms/horizon/minion/icmp/shell/WSManScannerCommand.java
> +        //        wsmanScannerRequests.add(WsmanDetectorRequest.newBuilder()
Comments has been removed

2024-08-16 16:48 UTC, naeem-afzal commented on inventory/main/src/main/resources/db/changelog/hs-0.1.0/tables/discovery-inheritance.xml
> +
username and password fields has been removed and added basic_auth field as combination of both fields and stored as encrypted value

2024-08-16 16:57 UTC, cgorantla commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/discovery/WsManActiveDiscoveryGrpcService.java
> +                    scannerTaskSetService.removeDiscoveryScanTask(
we can always update, tasks with same id gets replaced if there is any change in config.

2024-08-16 16:57 UTC, cgorantla commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/discovery/WsManActiveDiscoveryGrpcService.java
> +                    throw new IllegalArgumentException("Invalid Ip Address entry " + ipAddressEntry);
I believe these are host names, hostnames could contain `-` and ` /`

2024-08-16 16:57 UTC, cgorantla commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/discovery/WsManActiveDiscoveryGrpcService.java
> +            } else if (ipAddressEntry.contains("-")) {
same here.

2024-08-16 16:57 UTC, cgorantla commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/discovery/active/WsManActiveDiscoveryService.java
> +        discovery = repository.save(discovery);
where are we setting basic_auth here ?

2024-08-16 17:02 UTC, naeem-afzal commented on inventory/main/src/main/java/org/opennms/horizon/inventory/service/discovery/active/WsManActiveDiscoveryService.java
> +        discovery = repository.save(discovery);
we are converting/ setting basic_auth in mapper

2024-08-20 09:57 UTC, naeem-afzal commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/discovery/WsManActiveDiscoveryGrpcService.java
> +            } else if (ipAddressEntry.contains("-")) {
Host validation function has been updated

2024-08-20 09:58 UTC, naeem-afzal commented on inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/discovery/WsManActiveDiscoveryGrpcService.java
> +                    scannerTaskSetService.removeDiscoveryScanTask(
removed removeDiscoveryScanTask, as we are sending same task ID to Minion, so it will update existing task

2024-08-25 21:24 UTC, cgorantla approved these changes
LGTM.

2024-08-26 12:16 UTC, aurang-zeb313 approved these changes
LGTM

2024-08-26 12:18 UTC, merged