Bh/jira/lok 2710
OpenNMS-Cloud/lokahi pull request #2019
Opened 2024-07-30 17:52 UTC by Syed-Bilal-Haider-Dataq

## Description
Update the inventoryStore with a Map of node ID to boolean status.

In inventoryStore.init() in addition to making a call to buildNetworkInventory , also make a call to Node Status Service, allNodeStatus. 

Ideally, make parallel calls to these, refactor to use Promise.all, etc.

When that returns, fill the inventoryStore.nodeStatusMap.

Then on the Node Status page, use that value to display the node’s Status in both the table and the card.

Ideally, the topNNode call in dashboardStore should save any node status it finds into the inventoryStore.nodeStatusMap.

Eventually we may need to set up polling of the node status so that they update in semi-realtime.

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2710

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-07-31 17:50 UTC, Shahbaz-dataq requested changes
Make discussed changes and let me know

2024-08-05 13:26 UTC, Shahbaz-dataq requested changes
Just small fixes. Let me know when you are done.

2024-08-05 13:26 UTC, Shahbaz-dataq commented on ui/src/components/Inventory/InventoryTabContent.vue
> +const metricsAsTextBadges = (metrics?: RawMetric, nodeId?: string) => {
this function is common in `Table` and `Card` component. Move it to `inventory.utils.ts`

2024-08-05 13:26 UTC, Shahbaz-dataq commented on ui/src/components/Inventory/InventoryTabContent.vue
> +  if (label?.trim().toLocaleLowerCase() === 'up') {
change `.toLocaleLowerCase()` to `.toLowerCase()` if you are not passing `Locale` here

2024-08-05 13:26 UTC, Shahbaz-dataq commented on ui/src/components/Inventory/InventoryTabTable.vue
> +const metricsAsTextBadges = (metrics?: RawMetric, nodeId?: string | undefined) => {
Move this function to `inventory.utils.ts`

2024-08-05 14:08 UTC, Shahbaz-dataq approved these changes
LGTM

2024-08-06 19:35 UTC, synqotik approved these changes
LGTM

2024-08-06 19:35 UTC, synqotik commented on ui/src/store/Views/inventoryStore.ts
> +        const [data, allNodesStatus] = await Promise.all([
Good use of `Promise.all` !

2024-08-07 10:56 UTC, merged