FE: Integrate BFF for Service Discovery
OpenNMS-Cloud/lokahi pull request #2029
Opened 2024-08-02 11:27 UTC by faizanjanjua

## Description
BFF for saving Service Monitor Discovery for HTTP/HTTPS is complete.

Create Mutation using this function upsertSimpleMonitoredEntity 

This is sample graphQL 

mutation {
  upsertSimpleMonitoredEntity(entity: {
    locationId: 1,
    name: "https://google.com/",
    type: "HTTPS",
    config: "{\"inetAddress\":\"www.google.com\",\"responseCode\":\"200-201\",\"url\":\"https://www.google.com/\",\"ports\":[443],\"hostName\":\"www.google.com\"}"
  }) {
    id
    locationId
    name
    type
    config
    monitoredEntityId
  }
} 

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2716

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-08-02 17:21 UTC, Shahbaz-dataq requested changes
For now validation for `config` or `discoveryTargets` do not need to be strict but It should validate for number of urls, ip or if its empty

2024-08-02 17:21 UTC, Shahbaz-dataq commented on ui/src/types/graphql.ts
> +export type MutationCreateServiceDiscoveryArgs = {
remove this unused type

2024-08-02 17:21 UTC, Shahbaz-dataq commented on ui/src/types/discovery.d.ts
> +export interface ServiceDiscovery {
remove unused interface

2024-08-02 17:21 UTC, Shahbaz-dataq commented on ui/src/store/Views/discoveryStore.ts
> +          if ((this.selectedDiscovery.meta as ServiceDiscovery).services?.port === 80 || (this.selectedDiscovery.meta as ServiceDiscovery).services?.port === 443) {
Make this condition short by creating a new variable
`const services = (this.selectedDiscovery.meta as ServiceDiscovery).services`

2024-08-02 17:21 UTC, Shahbaz-dataq commented on ui/src/dtos/discovery.dto.ts
> +  locationId: yup.string().trim().required('Location required.')
Validation for config is missing

2024-08-02 17:26 UTC, faizanjanjua commented on ui/src/store/Views/discoveryStore.ts
> +          if ((this.selectedDiscovery.meta as ServiceDiscovery).services?.port === 80 || (this.selectedDiscovery.meta as ServiceDiscovery).services?.port === 443) {
resolved

2024-08-02 18:55 UTC, faizanjanjua commented on ui/src/dtos/discovery.dto.ts
> +  console.log('111111111111')
done

2024-08-02 19:00 UTC, faizanjanjua commented on ui/src/types/discovery.d.ts
> +export interface ServiceDiscovery {
Done

2024-08-02 19:01 UTC, faizanjanjua commented on ui/src/dtos/discovery.dto.ts
> +  locationId: yup.string().trim().required('Location required.')
@synqotik should we use any regex for this

2024-08-08 19:14 UTC, synqotik approved these changes
LGTM - please fix the issue with `label` not being on the same line before merging.

We can open separate issue re my other comment.

2024-08-08 19:14 UTC, synqotik commented on ui/src/components/Discovery/DiscoveryMetaInformation.vue
> +        abel="Enter Community String (optional)" />
`label` should be on the same line

2024-08-08 19:14 UTC, synqotik commented on ui/src/dtos/discovery.dto.ts
> +    config: `{"inetAddress":"${meta.discoveryTargets}","responseCode":"200-201","url":"${meta.services.type?.toLocaleLowerCase()}://${meta.discoveryTargets}/","ports":[${meta.services?.port}],"hostNa
Instead of doing this inline string, we should make different Typescript interfaces for the different config types, then using `JSON.stringify()` to convert them to a string for the BFF. Note, we will need those config interface types when deserializing back from BFF.

For now, it's ok to have this inline string (so we can start using Service Discovery), but let's open a separate ticket to fix it to make those interfaces, etc.

2024-08-12 11:26 UTC, merged