Jira/lok 2683
OpenNMS-Cloud/lokahi pull request #2031
Opened 2024-08-05 12:24 UTC by atif1019

## Description
On the Node Status Page, Recent Alert says "CLEAR". I think it is not using the right field.
Make the following updates to the front end:

For the first column “Alert Type”, display the Alarm uei field (and should be sortable on that field)

Add a second column named “Count”, this should display the Alarm counter field

Rename the “TIME” column to “Last Updated”. It should be sortable on lastUpdatedTimeMs 

Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2683

2024-08-05 14:04 UTC, Shahbaz-dataq approved these changes
Small change. Otherwise LGTM

2024-08-05 14:04 UTC, Shahbaz-dataq commented on ui/src/components/NodeStatus/NodeAlerts.vue
> +  { id: 'eventUei', label: 'Alert Type' },
remane this lable 'UEI'

2024-08-05 15:45 UTC, synqotik requested changes
Added a comment.

2024-08-05 15:45 UTC, synqotik commented on ui/src/components/NodeStatus/NodeAlerts.vue
> +                    <div class="name headline alert-type" data-test="name">{{ alert?.uei?.slice(0, 20)+"..." || alert.label || 'Unknown' }}
If `alert.uei` is <= 20 characters, don't display the `...`. May want to change this to a function.

2024-08-07 18:14 UTC, synqotik approved these changes
LGTM

2024-08-07 18:15 UTC, merged