LOK-2746 Add Monitored Entity Id to Service Unavailable/reachable events
OpenNMS-Cloud/lokahi pull request #2048
Opened 2024-08-13 18:08 UTC by Mohammad-Junid

## Description
Add Monitored Entity Id to Service Unavailable/reachable events in order to  create events/alert  for up/down monitor entities

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2746

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-08-13 18:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=2048) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenNMS-Cloud/lokahi?pullRequest=2048) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenNMS-Cloud/lokahi?pullRequest=2048) it.</sub>

2024-08-14 12:41 UTC, aurang-zeb313 commented on events/consumer/src/main/java/org/opennms/horizon/events/consumer/EventsConsumer.java
> +        event.setMonitoredEntityId(eventProto.getMonitorServiceId());
In eventProto  it should be monitored_entity_id, just like in event entity

2024-08-14 12:51 UTC, aurang-zeb313 requested changes
Please implement the suggested changes.

2024-08-14 12:51 UTC, aurang-zeb313 commented on shared-lib/events/src/main/proto/events.proto
> +  string  monitor_service_id=17;
replace monitor_service_id with monitored_entity_id

2024-08-14 14:55 UTC, Mohammad-Junid commented on events/consumer/src/main/java/org/opennms/horizon/events/consumer/EventsConsumer.java
> +        event.setMonitoredEntityId(eventProto.getMonitorServiceId());
Done

2024-08-14 14:55 UTC, Mohammad-Junid commented on shared-lib/events/src/main/proto/events.proto
> +  string  monitor_service_id=17;
Done

2024-08-14 14:56 UTC, Mohammad-Junid commented
> Please implement the suggested changes.

Done

2024-08-15 01:01 UTC, cgorantla commented on alert/src/main/resources/db/changelog/hs-0.1.0/data/event_definition_data.csv
> +7,uei.opennms.org/internal/node/serviceUnreachable,Device Unreachable,%uei%:%dpname%:%nodeid%:%interface%:%monitor_entity_id% ,,INTERNAL
since monitor entity id is unique across nodes/interfaces, we can remove nodeid and interface here completely.  The only thing then misses for the user is which service and which host, we can add service_name as optional field in the Event.

2024-08-15 17:19 UTC, cgorantla approved these changes
Looks good.  

Can you try to validated this with ICMP service and see if you can get alerts properly.

2024-08-15 17:38 UTC, Mohammad-Junid commented
> Looks good.
> 
> Can you try to validated this with ICMP service and see if you can get alerts properly.

I just do discovery of multiple  node through ICMP and it  generate alerts for the  down nodes 

![image](https://github.com/user-attachments/assets/1543dd6f-db1d-4d66-94c6-ea1439f722e9)

2024-08-15 17:43 UTC, aurang-zeb313 approved these changes
Approved

2024-08-15 17:43 UTC, merged