Basic UI Ready for validations
OpenNMS-Cloud/lokahi pull request #2053
Opened 2024-08-16 12:45 UTC by faizanjanjua

## Description

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2748

## Flagged for review

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

2024-08-19 17:51 UTC, Shahbaz-dataq requested changes
Need these changes

2024-08-19 17:51 UTC, Shahbaz-dataq commented on ui/src/dtos/discovery.dto.ts
> +  console.log(convertedDiscovery , 'converted Discovery')
Remove log

2024-08-19 17:51 UTC, Shahbaz-dataq commented on ui/src/components/Discovery/ServiceDiscoveryModal.vue
> +<template>
Rename file to `DiscoveryTargetModal.vue`

2024-08-19 17:51 UTC, Shahbaz-dataq commented on ui/src/components/Discovery/ServiceDiscoveryModal.vue
> +// onMounted(() => {
remove commented code

2024-08-19 17:51 UTC, Shahbaz-dataq commented on ui/src/types/discovery.d.ts
> +export interface ServiceConfigCollection {
remove unused interface `ServiceConfigCollection`

2024-08-19 17:51 UTC, Shahbaz-dataq commented on ui/src/types/discovery.d.ts
> +  ServicesAndPortNumbers : Array<any>;
Remove `ServicesAndPortNumbers`

2024-08-19 17:51 UTC, Shahbaz-dataq commented on ui/src/types/discovery.d.ts
> +  SelectedDiscoveryServices : newServiceDiscoveryInModal;
Rename `SelectedDiscoveryServices` to `selectedServiceDiscoverytarget`

2024-08-19 17:51 UTC, Shahbaz-dataq commented on ui/src/types/discovery.d.ts
> +export interface newServiceDiscoveryInModal{
Rename `newServiceDiscoveryInModal` to `newServiceDiscoveryTarget`

2024-08-19 17:51 UTC, Shahbaz-dataq commented on ui/src/types/discovery.d.ts
> +  status? : string
rename `status` to `responseCode`

2024-08-19 17:51 UTC, Shahbaz-dataq commented on ui/src/components/Discovery/ServiceDiscoveryModal.vue
> +          label="Status"
Changes label from `Status` to `responseCode`

2024-08-20 17:54 UTC, synqotik approved these changes
Overall LGTM. I have a few nitpicks, but they aren't that important. Let's get this merged so we can do the demo this week.

2024-08-20 18:28 UTC, Shahbaz-dataq approved these changes

2024-08-20 18:29 UTC, merged